<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contained GTIN</name>
   <tag></tag>
   <elementGuidId>af717a1d-80b3-4cfd-90ec-2de5fac56929</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id, 'ContainedGTIN')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ProductCommercialStatusId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d300cfef-f3a8-4581-863a-e21fa43e4e43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ss input-Commercial</value>
      <webElementGuid>8a3e362a-f104-4d28-9834-2bfbc426fd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ac476ab9-b5ed-4da3-85fa-cfa5c0829934</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProductCommercialStatusId field is required.</value>
      <webElementGuid>368f0d94-35c2-4326-9044-e21914e99278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductCommercialStatusId</value>
      <webElementGuid>1e9d5efa-ef2e-4efe-b749-7dd82f39c807</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductCommercialStatusId</value>
      <webElementGuid>13fb0f71-c199-4840-a9fa-d9f814219a42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Commercial StatusAlternate items availableIn MarketItems no longer stockedPhase outWithdrawn</value>
      <webElementGuid>db14f7e2-cb28-4fba-801e-493fe0cc6d25</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductCommercialStatusId&quot;)</value>
      <webElementGuid>59db4b02-abc2-4165-b4b6-bf426dd59782</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ProductCommercialStatusId']</value>
      <webElementGuid>7019fd7f-7d03-493d-a9a6-0da5f750fd82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductDetail']/div/div/div/div[5]/div[2]/div/div[2]/select</value>
      <webElementGuid>a250c58e-ddd7-47a9-bda3-00c1f1f3a07b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Commercial Status'])[1]/following::select[1]</value>
      <webElementGuid>0753f247-f4fc-4d12-bfe2-ec219e18b9e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZW - Zimbabwe'])[2]/following::select[1]</value>
      <webElementGuid>a2f0830d-3514-4c3c-a91d-fff618c04943</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Identifiers'])[1]/preceding::select[1]</value>
      <webElementGuid>8ae71e51-d9c9-4c67-a05b-2d745006f848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Identifier'])[1]/preceding::select[1]</value>
      <webElementGuid>682b03b5-35cb-4297-8985-d65feddee845</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>3c625062-ea00-47aa-bad2-98e78de4acd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ProductCommercialStatusId' and @name = 'ProductCommercialStatusId' and (text() = 'Select Commercial StatusAlternate items availableIn MarketItems no longer stockedPhase outWithdrawn' or . = 'Select Commercial StatusAlternate items availableIn MarketItems no longer stockedPhase outWithdrawn')]</value>
      <webElementGuid>1e4c3f71-de1d-4922-b566-a4e96e4521b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
