<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GS1 Company Prefix Length</name>
   <tag></tag>
   <elementGuidId>845e23ae-7eb5-4b9e-94ec-dd1a7df62b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TradeItem[0].GS1CompanyPrefixId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>285e448a-aa90-459a-a5f7-69a3908ae052</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ml-3 input-ms gcplength</value>
      <webElementGuid>7ed14789-9fd0-40a1-90fa-19ace5a1f7f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].GS1CompanyPrefixId</value>
      <webElementGuid>a15f4265-27e7-43f3-bf88-acc59ecf8406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].GS1CompanyPrefixId</value>
      <webElementGuid>4e55c27e-c556-41b4-86c7-4d90479391e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>957335b1-ac14-43bc-b9e5-e7b41fbc9912</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GS1CompanyPrefixId field is required.</value>
      <webElementGuid>0a4896ea-04f3-4054-b5db-fd7288790d3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Company Prefix Length456789101112</value>
      <webElementGuid>e6bc9a19-a620-4137-806d-a9de143c5d8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].GS1CompanyPrefixId&quot;)</value>
      <webElementGuid>958d5ae9-aca5-4cbf-b0ac-63519e798818</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TradeItem[0].GS1CompanyPrefixId']</value>
      <webElementGuid>ee7d76c1-128a-4a95-b75f-b1831b2546d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[4]/div[2]/select</value>
      <webElementGuid>fa2462ca-1a4a-4233-8f61-99414d474069</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix Length'])[1]/following::select[1]</value>
      <webElementGuid>ba3c9813-b0e7-4b02-9ba6-961ae1fe85ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/following::select[1]</value>
      <webElementGuid>1f010732-6ea0-4264-97e3-3716ad04a010</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU'])[1]/preceding::select[1]</value>
      <webElementGuid>886def0b-59a3-4bc3-a507-dee9f1d06003</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit of Use GTIN'])[1]/preceding::select[1]</value>
      <webElementGuid>2f84caac-6a3c-4390-a6c5-8939b366f296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/select</value>
      <webElementGuid>a6592638-918d-4513-89bf-532f362e90f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TradeItem[0].GS1CompanyPrefixId' and @name = 'TradeItem[0].GS1CompanyPrefixId' and (text() = 'Select Company Prefix Length456789101112' or . = 'Select Company Prefix Length456789101112')]</value>
      <webElementGuid>0bda575f-2db1-4c71-8da0-b0013f6782e2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
