<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GS1 Company Prefix Length</name>
   <tag></tag>
   <elementGuidId>845e23ae-7eb5-4b9e-94ec-dd1a7df62b1e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'GS1CompanyPrefixId')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>bab02efc-f433-4845-bef9-2f1febb35f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ml-3 input-ms gcplength</value>
      <webElementGuid>6960675f-63e3-421a-ae6b-c211392fb9b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].GS1CompanyPrefixId</value>
      <webElementGuid>1a4f752e-d6e1-4eba-b84a-926690eedf58</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].GS1CompanyPrefixId</value>
      <webElementGuid>86c6c2de-c403-4382-9fe4-14309ca3e77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3cf0a628-524a-492a-9fb0-fc08cca6a21e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GS1CompanyPrefixId field is required.</value>
      <webElementGuid>f15a2820-941c-43d8-96a3-2129322996ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Company Prefix Length456789101112</value>
      <webElementGuid>4d091dc9-6333-4800-a559-c4054efcc3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].GS1CompanyPrefixId&quot;)</value>
      <webElementGuid>1bd5b313-81a0-4129-9718-acb9bd026f12</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TradeItem[0].GS1CompanyPrefixId']</value>
      <webElementGuid>fdac7c96-51ae-4624-acdd-5099ca453fd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[4]/div[2]/select</value>
      <webElementGuid>f28b6b3a-22de-4f8f-9941-7aa6d5d61296</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix Length'])[1]/following::select[1]</value>
      <webElementGuid>561e47c3-c4da-4cc4-b3e6-d9bd36626b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/following::select[1]</value>
      <webElementGuid>58975cd1-151b-49ce-ac05-ea9285e28510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SKU'])[1]/preceding::select[1]</value>
      <webElementGuid>c358d841-683b-407b-8632-366af7870fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Unit of Use GTIN'])[1]/preceding::select[1]</value>
      <webElementGuid>853669b2-6691-4645-b529-9320a29def11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/select</value>
      <webElementGuid>4370015f-b8a5-4003-8f33-233399d3eba4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TradeItem[0].GS1CompanyPrefixId' and @name = 'TradeItem[0].GS1CompanyPrefixId' and (text() = 'Select Company Prefix Length456789101112' or . = 'Select Company Prefix Length456789101112')]</value>
      <webElementGuid>b0bb8d38-b315-47a7-a076-d33fa958e446</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
