<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Packaging Level</name>
   <tag></tag>
   <elementGuidId>961343c5-d6fa-4c3c-a302-544970758f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TradeItem[0].PackagingLevelId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>cb2240ef-ed20-4857-87f8-850ac42fab79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms packLvl</value>
      <webElementGuid>fce0e895-dece-4ff5-ab87-f82c8d535fd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].PackagingLevelId</value>
      <webElementGuid>2278cfc4-ac94-4544-95f8-698124dcc02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].PackagingLevelId</value>
      <webElementGuid>d3537dbb-e9d7-4775-b0e6-391922873567</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>changePackagelvlTabContent(this)</value>
      <webElementGuid>a5f7d101-be5d-4bbf-91b8-25e738c82ec0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6e11f95-4696-47a4-8875-832890781d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PackagingLevelId field is required.</value>
      <webElementGuid>c277a5b0-09b8-44aa-8398-eb889d9dcd84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Packaging LevelEach</value>
      <webElementGuid>b90619d5-4f1b-422b-bc0d-23cd15f43c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].PackagingLevelId&quot;)</value>
      <webElementGuid>295a75b5-7a35-4178-b613-9ed196cc682c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TradeItem[0].PackagingLevelId']</value>
      <webElementGuid>49fc6ddb-304e-418b-82cf-fa76602d678c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div/div/select</value>
      <webElementGuid>3e75ea1b-32a9-451e-8df8-45f5dcd1228b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packaging Level'])[2]/following::select[1]</value>
      <webElementGuid>e2abc799-c348-42cf-86e0-9e42d40be52b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untitled'])[1]/following::select[1]</value>
      <webElementGuid>47d88a66-1954-4c8a-8c94-8b948f4b06da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/preceding::select[1]</value>
      <webElementGuid>f4e9b222-de81-4aa3-ae25-f52b9b17c450</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/preceding::select[1]</value>
      <webElementGuid>e51bf916-cd82-4c77-b2a7-61d12a11de56</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/select</value>
      <webElementGuid>17c068ec-1648-4bcb-811a-441b0d9c1428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'TradeItem[0].PackagingLevelId' and @id = 'TradeItem[0].PackagingLevelId' and (text() = 'Select Packaging LevelEach' or . = 'Select Packaging LevelEach')]</value>
      <webElementGuid>0e7ae495-d2fb-48e4-8738-2250b7014c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
