<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Packaging String</name>
   <tag></tag>
   <elementGuidId>bbac3d24-276e-4e82-821b-d655a5d47416</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'PackagingString')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>779eadb6-ce79-4536-b163-8be652bdda7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row autodisplayBgcolor input-ms</value>
      <webElementGuid>46c4f88d-7f40-4a87-b51e-a12fe64a2b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].PackagingString</value>
      <webElementGuid>db07777d-5185-4d01-afa6-92ced602437e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5b9e5ae9-d08b-482b-8bb7-4a6677617e50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PackagingString</value>
      <webElementGuid>008511d0-c4a2-462e-9fa7-a9d0c1a98673</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].PackagingString&quot;)</value>
      <webElementGuid>369289ee-3814-4bcf-a3aa-91066ab9e063</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TradeItem[0].PackagingString']</value>
      <webElementGuid>24fb1bdc-1bf5-4ba2-9ba0-d38d3120999a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[7]/div/input</value>
      <webElementGuid>a211783b-51d2-4980-85de-386108e6bab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[7]/div/input</value>
      <webElementGuid>f8a025b8-f693-4e58-b970-b975c977a4a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TradeItem[0].PackagingString' and @type = 'text' and @name = 'PackagingString']</value>
      <webElementGuid>09f339b6-4033-4064-b420-2d2aede0e5e8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
