<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Packaging Level</name>
   <tag></tag>
   <elementGuidId>961343c5-d6fa-4c3c-a302-544970758f6f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'PackagingLevelId')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9a082bed-9ab9-45c7-ba5b-16817e51b816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms packLvl</value>
      <webElementGuid>764fee5e-d633-4169-8cf4-7c1d430a5ef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].PackagingLevelId</value>
      <webElementGuid>a23566b0-821f-4ce9-9e4d-8d5872454fcd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].PackagingLevelId</value>
      <webElementGuid>1987b9c2-528a-4fbd-aa41-2879bbdfafa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>changePackagelvlTabContent(this)</value>
      <webElementGuid>8273176b-c997-4200-b519-d2d600647303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>31bba37d-c9ce-41ea-8795-e36b783e0e7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PackagingLevelId field is required.</value>
      <webElementGuid>ba3c5ae5-3b16-4bec-aabc-d42f47028d8a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Packaging LevelEach</value>
      <webElementGuid>a039a906-d6c0-4d28-8ac0-62be3490a1e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].PackagingLevelId&quot;)</value>
      <webElementGuid>212d124c-aeeb-4211-93f2-9dc9058e76c2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TradeItem[0].PackagingLevelId']</value>
      <webElementGuid>69f78385-3c2d-4dc0-8b0b-4df8b04a306e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div/div/select</value>
      <webElementGuid>7a07ff5f-e02d-4385-9866-66ce68c4b797</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Packaging Level'])[2]/following::select[1]</value>
      <webElementGuid>4428d0ff-b044-4010-ac5f-044bd7e5ce10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Untitled'])[1]/following::select[1]</value>
      <webElementGuid>30300b14-0876-4600-b2b8-729beef65c6e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[3]/preceding::select[1]</value>
      <webElementGuid>c39fbc45-94d4-4e53-9600-d30d77796397</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[2]/preceding::select[1]</value>
      <webElementGuid>2dd16331-edd9-4619-a0ca-a66e8a95394b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div/select</value>
      <webElementGuid>4bc10060-d928-473d-8253-994f9aa072f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@name = 'TradeItem[0].PackagingLevelId' and @id = 'TradeItem[0].PackagingLevelId' and (text() = 'Select Packaging LevelEach' or . = 'Select Packaging LevelEach')]</value>
      <webElementGuid>2aa734dc-3aa0-4e5f-9cf0-d7b62fc73cf1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
