<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Code</name>
   <tag></tag>
   <elementGuidId>13d92872-ca93-4d69-9d61-65766ef01e0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TradeItem[0].ProductCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>045e6503-f4b7-43d4-b372-2eb47543ef1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms pCode</value>
      <webElementGuid>91cf83c5-bc9b-4124-a0df-4ec30a7ae9c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].ProductCode</value>
      <webElementGuid>ac3c5554-1fb9-4143-a347-cfb9487e450d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].ProductCode</value>
      <webElementGuid>78356a02-04c4-496e-87ca-26062e383a26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ValidateGtin(this)</value>
      <webElementGuid>4bf13fe7-630f-42e7-a990-6fed9ae8f151</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product Code</value>
      <webElementGuid>9b488859-85dd-4c18-b1a5-938c17bbe714</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>97e312c7-7447-46b6-a3da-eabcc9afc79b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].ProductCode&quot;)</value>
      <webElementGuid>49c76371-3be7-49f2-a111-eb9ce766dfc9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TradeItem[0].ProductCode']</value>
      <webElementGuid>88c2da6c-89c2-412b-b996-ff539b61d1ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[4]/div/input</value>
      <webElementGuid>a9461daa-0b82-47b3-8ea9-df1886be6100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[4]/div/input</value>
      <webElementGuid>a9fdb314-4d42-45f6-9e92-270b6f903a1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TradeItem[0].ProductCode' and @name = 'TradeItem[0].ProductCode' and @placeholder = 'Enter Product Code' and @type = 'text']</value>
      <webElementGuid>8898b599-e1dd-4329-8269-9a300cba253e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
