<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Code Type</name>
   <tag></tag>
   <elementGuidId>005f7c58-8d59-4af2-b80c-ea9c385fdfae</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TradeItem[0].ProductCodeTypeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2da19640-31c3-4738-ab4a-07ff915877f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>5db6fe08-7b0c-4fd5-9896-887fd19cd5f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].ProductCodeTypeId</value>
      <webElementGuid>f1861bf5-634d-4a2d-a8a3-0e3230a4b29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].ProductCodeTypeId</value>
      <webElementGuid>f6b70f6a-9a84-4bd6-bed4-60022af6139a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ca9ce2c-467c-4604-bb24-b7dfe92d54aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProductCodeTypeId field is required.</value>
      <webElementGuid>67a22621-d5f7-496f-a904-4a74c11e9139</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Product Code TypeGTIN-14GTIN-14</value>
      <webElementGuid>aeef9549-b834-4954-8d4b-5878c3906777</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].ProductCodeTypeId&quot;)</value>
      <webElementGuid>dc04e8e0-a9cf-4b12-8e20-541c4bec06f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TradeItem[0].ProductCodeTypeId']</value>
      <webElementGuid>8a31f0f5-5612-4d5b-bf2d-a4ed2062481a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[3]/div/select</value>
      <webElementGuid>3896e128-c79b-4c24-8fa0-fdbbab92cb2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code Type'])[1]/following::select[1]</value>
      <webElementGuid>2bd3733b-b204-428e-934d-d36a4c737577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason for Status Change is required'])[1]/following::select[1]</value>
      <webElementGuid>bce2625f-039b-4f32-88a5-6ac4f0c8e201</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Filter Value'])[1]/preceding::select[1]</value>
      <webElementGuid>5ceb6d33-9e8e-4c24-a435-b504510056a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/preceding::select[2]</value>
      <webElementGuid>a01520e4-5ada-453e-99f2-4497c3015e26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div/select</value>
      <webElementGuid>ec7ed76b-ec2f-47b9-a417-73b8f11e4790</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TradeItem[0].ProductCodeTypeId' and @name = 'TradeItem[0].ProductCodeTypeId' and (text() = 'Select Product Code TypeGTIN-14GTIN-14' or . = 'Select Product Code TypeGTIN-14GTIN-14')]</value>
      <webElementGuid>77730f3b-3f93-468b-a43c-32d5e28141d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
