<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RFID Filter Value</name>
   <tag></tag>
   <elementGuidId>ed6a818d-b46f-4a5b-b31c-d867a323b801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TradeItem[0].RFIDFilterValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7ce3b94d-f7bb-4fa9-b55e-4ae7efb52fb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ml-3 input-ms</value>
      <webElementGuid>768ad271-63d3-4838-bf7a-72352695e312</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].RFIDFilterValue</value>
      <webElementGuid>6bafb184-cb84-4699-8d0a-43b8adc8451e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].RFIDFilterValue</value>
      <webElementGuid>5736daea-9255-4142-8dfa-d336782b9822</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ea2d5913-b9d4-43df-8144-a887c28c7b32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RFIDFilterValue field is required.</value>
      <webElementGuid>448f5b0b-79ed-42aa-a838-d905575554a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select RFID Filter Value01234567</value>
      <webElementGuid>ee84a517-c1ef-49a4-8331-d294921e23bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].RFIDFilterValue&quot;)</value>
      <webElementGuid>42d53c4f-85e0-4b9e-aa48-a04b3cc8c660</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TradeItem[0].RFIDFilterValue']</value>
      <webElementGuid>e1078031-3446-472c-b937-20f7bdd15191</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[3]/div[2]/select</value>
      <webElementGuid>58797815-2d05-4f82-91e7-933936208710</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Filter Value'])[1]/following::select[1]</value>
      <webElementGuid>7641c007-2929-403f-ba46-5d26af183b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code Type'])[1]/following::select[2]</value>
      <webElementGuid>0d964ed6-f337-4a35-8eb7-d22c7653f7fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/preceding::select[1]</value>
      <webElementGuid>8d98e541-54ea-47dc-a74b-733fc03257c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix Length'])[1]/preceding::select[1]</value>
      <webElementGuid>47c82914-6475-4f38-9133-c96bde6ea488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[2]/select</value>
      <webElementGuid>a0d428b4-379c-4464-bdc9-f0cc5f1fc0b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TradeItem[0].RFIDFilterValue' and @name = 'TradeItem[0].RFIDFilterValue' and (text() = 'Select RFID Filter Value01234567' or . = 'Select RFID Filter Value01234567')]</value>
      <webElementGuid>d4159175-5d22-443d-a05f-cf54df39a742</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
