<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RFID Filter Value</name>
   <tag></tag>
   <elementGuidId>ed6a818d-b46f-4a5b-b31c-d867a323b801</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'RFIDFilterValue')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b28c2ce7-017a-49fd-b884-cf50465de001</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ml-3 input-ms</value>
      <webElementGuid>97d0a9c6-a24f-4f8c-ad72-9b2f11657176</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].RFIDFilterValue</value>
      <webElementGuid>776fae27-dfd0-41ca-aba0-05aacfc45e70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].RFIDFilterValue</value>
      <webElementGuid>3bd74df9-63a5-4da4-9ae3-6ac467721e9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2ef69002-a0de-41bf-ad5f-facb4e601653</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RFIDFilterValue field is required.</value>
      <webElementGuid>73879e79-bfa6-4717-8f48-ae4c7e0ab43c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select RFID Filter Value01234567</value>
      <webElementGuid>fa75065d-3f92-49da-a99a-bdeb094da148</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].RFIDFilterValue&quot;)</value>
      <webElementGuid>675ad771-0994-480b-91ce-7629d7d2228f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TradeItem[0].RFIDFilterValue']</value>
      <webElementGuid>3a47398d-1c0f-4fa7-aa8e-55b2dc07c871</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[3]/div[2]/select</value>
      <webElementGuid>ec607368-fe4b-43ee-8df0-522d759a05ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Filter Value'])[1]/following::select[1]</value>
      <webElementGuid>33b71bb6-ec1f-4761-a882-5ba7437c9bd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code Type'])[1]/following::select[2]</value>
      <webElementGuid>ff6cbc2c-00c1-4e13-99cb-be7e01e825bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/preceding::select[1]</value>
      <webElementGuid>3f252e3c-48d5-45a7-8a20-e70c53a1cbd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix Length'])[1]/preceding::select[1]</value>
      <webElementGuid>c33b248a-edd0-4a19-b4e6-0aa84adacceb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[3]/div[2]/select</value>
      <webElementGuid>ed02996a-da9e-4b6c-8f1b-5e805c530280</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TradeItem[0].RFIDFilterValue' and @name = 'TradeItem[0].RFIDFilterValue' and (text() = 'Select RFID Filter Value01234567' or . = 'Select RFID Filter Value01234567')]</value>
      <webElementGuid>84bd0de9-4c21-46a8-a15c-ecf24284e662</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
