<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unit of Use GTIN</name>
   <tag></tag>
   <elementGuidId>38f391ca-2aeb-4d69-8b8f-81062106292a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'UnitOfUseProductCode')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d8eda027-b7ee-4e02-861f-45713b2e5772</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ml-3 input-ms</value>
      <webElementGuid>455f66fa-028f-4d18-bdf3-d9bb31a29b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].UnitOfUseProductCode</value>
      <webElementGuid>2caf09ec-a789-42ef-b3a4-36014b07dbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].UnitOfUseProductCode</value>
      <webElementGuid>2c3403d5-a582-4d17-bb4f-a776a8098c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Unit of Use GTIN </value>
      <webElementGuid>d656d7aa-82bf-4fb4-b9f2-5d3d4af8e62c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>beb9e9da-6dfc-44a3-9d5a-b368b57c7910</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].UnitOfUseProductCode&quot;)</value>
      <webElementGuid>ae7a3b86-76a8-4524-a694-c3f90b22cae2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TradeItem[0].UnitOfUseProductCode']</value>
      <webElementGuid>089e05cf-0984-4e70-bb30-b11fed0754e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[5]/div[2]/input</value>
      <webElementGuid>5224bc1b-0b28-429f-b290-916076f21378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>60b121b4-504e-4601-9685-378432d23c82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TradeItem[0].UnitOfUseProductCode' and @name = 'TradeItem[0].UnitOfUseProductCode' and @placeholder = 'Enter Unit of Use GTIN ' and @type = 'text']</value>
      <webElementGuid>bff5dcde-0172-44a9-8823-6e57336d9624</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
