<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Unit of Use GTIN</name>
   <tag></tag>
   <elementGuidId>38f391ca-2aeb-4d69-8b8f-81062106292a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TradeItem[0].UnitOfUseProductCode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e9ee76ac-6fe7-466d-8abb-bcf44a2588f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row ml-3 input-ms</value>
      <webElementGuid>a9018468-8ed2-4737-bc6d-2a4e74d5dca1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TradeItem[0].UnitOfUseProductCode</value>
      <webElementGuid>a407c9bd-b033-4ee0-92ec-a2d1873e8f3c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TradeItem[0].UnitOfUseProductCode</value>
      <webElementGuid>1c3d0c06-f0e1-4bba-950f-fe9d41470d93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Unit of Use GTIN </value>
      <webElementGuid>d71936e1-73bf-4850-9cb6-17f04b42847d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd972ded-3edb-4a73-9756-5d233aa70868</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TradeItem[0].UnitOfUseProductCode&quot;)</value>
      <webElementGuid>92012932-900a-4527-a991-66b3540dfca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TradeItem[0].UnitOfUseProductCode']</value>
      <webElementGuid>d28a9168-2f91-4f6c-90aa-67975a8c0c64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_packagingLevelTabContainer']/div/div[5]/div[2]/input</value>
      <webElementGuid>77770278-7e69-46a5-9c72-32a1bfee2139</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/input</value>
      <webElementGuid>96140cb9-c5b3-4823-83a5-4b26243c713b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TradeItem[0].UnitOfUseProductCode' and @name = 'TradeItem[0].UnitOfUseProductCode' and @placeholder = 'Enter Unit of Use GTIN ' and @type = 'text']</value>
      <webElementGuid>79eecaf6-1a97-40ab-bc99-48f8964a0964</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
