<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Party Suite</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>24444809-8245-4bd3-a2e1-ed26a465f413</testSuiteGuid>
   <testCaseLink>
      <guid>8090cae8-07b9-4332-9e80-14771dbbd039</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Add Test Cases/Add party in Draft status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>eda1da0b-9af1-4661-a093-8db23f3aa22a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Add Test Cases/Add Party in Draft with Address values</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d689752d-6be4-40a9-9238-51a289aebb61</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bef3493c-d516-4706-8717-3e917a21a6d4</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4d85bcd0-c0bd-4b3c-b718-cb98dfc5db17</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ffcda96f-8d37-4c69-a7eb-cd453a70f9bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>df87af68-c000-41ee-b622-3b95872cf3b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7f025d12-7c1d-41b4-87ad-d1926c8a9eb0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f72e2ddd-a6cf-42f2-8b2e-59652beb54c8</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>43e6f0e0-7609-4811-9d1c-ecd7eb20e567</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Validations/Address fields validation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>62aaa23b-d378-4cfc-9d46-9ecf313046b3</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Validations/GCP Validation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>251fce79-8f4e-4e98-ab65-02e195155901</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c706f5a-9312-48c6-8ccd-960c6e538911</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fe89efe0-8330-4052-a867-0966c10520cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>b1abcd0d-5be7-4559-937f-cc434da0d8b3</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0ca6546c-c2b7-4970-9e10-1b9af8829cb7</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Validations/GLN Validation</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
   <testCaseLink>
      <guid>67c79aa6-b40f-4298-8aa7-c22b973904b2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Add Test Cases/Add new Affiliate party with Active status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85ef366b-ab9a-40d8-b110-b0d2d65498ce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8db1f946-4ea1-43be-8051-718d7a313ff2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>52960c18-5de1-4654-8676-1d39b6f412d5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Add Test Cases/Add new Partner party with Active status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>111a6cde-b777-48cf-b0a2-84dbe8297e0f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6f83fb05-2514-4972-966d-096f491a4d3d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>69c3fac7-c14e-4b7d-915b-85d805f003b8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Edit Test Cases/Edit Party</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a3f284aa-ff04-404a-9583-851e1f810183</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>39d34631-683a-410f-a934-885aefd3e4a0</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Search Test Cases/Search By Party Name</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6df91dbf-3164-4743-ac63-db87f350656d</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>c3763bd7-849a-4178-a8a9-1454f8c85b7a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Search Test Cases/Search By SGLN</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d743db6e-752d-4d71-9106-afb8fd9e3404</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>582377dc-38a8-4100-8115-f213d073adbc</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>333d9737-329c-4cbe-800f-ed303ca0529f</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Search Test Cases/Search Party By GLN</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a942fcb-e2a4-4cf7-bdf9-1b5d5b442f48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>123d0796-3c9a-4a02-b493-c97b3a8486a2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>1c71ddc0-fe5c-49ea-8dcd-fbca659ab698</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Validations/Validate Party Name in Draft status</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
   </testCaseLink>
</TestSuiteEntity>
