<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Smoke Test</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>11d43a32-13a4-4914-89eb-45d674248c1b</testSuiteGuid>
   <testCaseLink>
      <guid>45566b93-768e-4abc-8875-3f731f1d852d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Product Test Cases/Search Test Cases/Search Product by GTIN-14</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>f8f70abd-c1ad-4cca-be49-ee00e021c45e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6452005d-a6bc-4657-8561-f98d75dc550c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>50b33c71-ff0d-4ed3-ac6e-e84f581613bd</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7c78c81b-7e66-4fa9-acc2-1dd60e732235</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Party Test Cases/Search Test Cases/Search Party By GLN</testCaseId>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a942fcb-e2a4-4cf7-bdf9-1b5d5b442f48</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>123d0796-3c9a-4a02-b493-c97b3a8486a2</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
