<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Party Name</name>
   <tag></tag>
   <elementGuidId>405bac82-0d38-4460-bb40-95246cd9c1de</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='partynameddlId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#partynameddlId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d61d4f97-3460-4f10-88f7-5546a1bb459b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>527603e4-b265-4c83-a35f-6e0423b564ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partynameddlId</value>
      <webElementGuid>efa37265-0d6d-4c51-88e1-2ce6f7650626</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c0c9c378-b38e-4ba5-bc6b-226665de6c69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PartyNameId field is required.</value>
      <webElementGuid>a03b5faa-d8a9-4932-91c8-b34233ecb4a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SystemDetails.PartyNameId</value>
      <webElementGuid>dfab6036-37e8-4720-bd3e-4137653c72c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Party NameRK-Pharmarte_impnorthstarNew RKParty 1_ImportedParty 2_ImportedParty 3_ImportParty 4_ImportMylan Inc.NorthStar Healthcare Unlimited CompanyAppco Pharma LLCPharmaceutics International IncMcKessonnew_cal56Party Test 101Rk_1Rk_1Rk_2Rk_2</value>
      <webElementGuid>3981e20e-67e8-4e0e-b43c-be2d633b75e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partynameddlId&quot;)</value>
      <webElementGuid>d73b8846-b50d-4028-af71-74ae6e5a5df5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='partynameddlId']</value>
      <webElementGuid>8342968b-69f9-4fa0-b642-9f428568fb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div/div/div/div/div/div/select</value>
      <webElementGuid>f259353e-55c2-4f37-8a61-c9130c5df823</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Name'])[1]/following::select[1]</value>
      <webElementGuid>195a069b-4b71-4167-97fc-7a04806d09c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::select[1]</value>
      <webElementGuid>bc303bef-630b-4448-a7be-a4c63ff14788</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>62aac393-a09d-4c58-abd4-87d888d9a272</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::select[1]</value>
      <webElementGuid>516a45e6-e624-48e4-841d-015bcb28ce2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>f7987162-6e4b-44d6-9ab4-813e6d5c2b23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'partynameddlId' and @name = 'SystemDetails.PartyNameId' and (text() = 'Select Party NameRK-Pharmarte_impnorthstarNew RKParty 1_ImportedParty 2_ImportedParty 3_ImportParty 4_ImportMylan Inc.NorthStar Healthcare Unlimited CompanyAppco Pharma LLCPharmaceutics International IncMcKessonnew_cal56Party Test 101Rk_1Rk_1Rk_2Rk_2' or . = 'Select Party NameRK-Pharmarte_impnorthstarNew RKParty 1_ImportedParty 2_ImportedParty 3_ImportParty 4_ImportMylan Inc.NorthStar Healthcare Unlimited CompanyAppco Pharma LLCPharmaceutics International IncMcKessonnew_cal56Party Test 101Rk_1Rk_1Rk_2Rk_2')]</value>
      <webElementGuid>fd403e42-5d58-4170-ab16-cfd802d0acbf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
