<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select Location</name>
   <tag></tag>
   <elementGuidId>f2e546d9-94aa-4eea-bb57-2e05120b27af</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='locationnameddl']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locationnameddl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0c198f54-f73d-4f80-b0ae-0e4923f2fc33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>26a7302f-58ce-4706-b46c-76cdcd0270d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationnameddl</value>
      <webElementGuid>e26a6b95-ad17-4949-8bb3-df79730bd192</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>49fe975c-bcf1-4edf-917e-36123135265d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The LocationNameId field is required.</value>
      <webElementGuid>ab1ad465-5e28-4016-a2b9-5116a9157354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SystemDetails.LocationNameId</value>
      <webElementGuid>b5a6a53f-e5b6-4c65-a7e5-83ad4ccbc78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select LocationRK-Pharma</value>
      <webElementGuid>fb4ae603-688b-4710-b07a-d16f99a0e79d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationnameddl&quot;)</value>
      <webElementGuid>57156578-9c2a-4b4e-b740-2ed6374d3ed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='locationnameddl']</value>
      <webElementGuid>c595fe3b-1412-49cd-9a86-bee04c862dd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div/div/div/div/div[4]/div/select</value>
      <webElementGuid>479e2db5-98aa-4361-8310-b73d6e127516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Name'])[1]/following::select[1]</value>
      <webElementGuid>8c86d586-bec7-4168-a75b-dec3f7828469</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Description'])[1]/following::select[1]</value>
      <webElementGuid>1581fe91-9d75-49dd-b6e2-1a1a0c221c94</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sender ID'])[1]/preceding::select[1]</value>
      <webElementGuid>7a2d8608-394f-4212-8902-561d62ac09d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>0b125982-6033-46f4-97a5-cb5a689345e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'locationnameddl' and @name = 'SystemDetails.LocationNameId' and (text() = 'Select LocationRK-Pharma' or . = 'Select LocationRK-Pharma')]</value>
      <webElementGuid>c7461a1a-d2f4-4462-99cb-97271fef9ca0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
