<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sender ID</name>
   <tag></tag>
   <elementGuidId>3f821ccb-c20d-4ee1-a0ae-922c5f1826ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id=&quot;SenderId&quot;]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c521876-cf91-4588-bed9-4f4ac133a0b8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>col-3 py-2</value>
      <webElementGuid>f66fe4f0-1b2c-4e5c-ace8-2ac085038ab0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>System Identifier [Sender ID] Sender Id is used as system identifier for data exchanges between external partners and internal packaging lines.Sender ID defaulted to Corporate GLN for all external Partners and location GLN for internal packaging lines. </value>
      <webElementGuid>7e37ab2a-5699-469a-a444-e7b56a5e9678</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Div_Detail&quot;)/div[@class=&quot;row position-relative&quot;]/div[@class=&quot;col-10&quot;]/div[@class=&quot;row content-left systemposition&quot;]/div[@class=&quot;col&quot;]/div[@class=&quot;systemDetails mc&quot;]/div[@class=&quot;row me&quot;]/div[@class=&quot;col-3 py-2&quot;]</value>
      <webElementGuid>1e1a4878-6a9d-402d-baf9-c35de51709aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div/div/div/div/div[5]/div</value>
      <webElementGuid>b5574b5d-0e0b-4ea7-b577-988e9249b25c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Name'])[1]/following::div[2]</value>
      <webElementGuid>7acbce76-6697-45c7-bbf8-1096971f5693</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Description'])[1]/following::div[4]</value>
      <webElementGuid>5643f0b5-d062-4ba6-8614-4d9c544bd37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[5]/div</value>
      <webElementGuid>190d4310-3c9e-409b-8809-f8dd205c1784</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'System Identifier [Sender ID] Sender Id is used as system identifier for data exchanges between external partners and internal packaging lines.Sender ID defaulted to Corporate GLN for all external Partners and location GLN for internal packaging lines. ' or . = 'System Identifier [Sender ID] Sender Id is used as system identifier for data exchanges between external partners and internal packaging lines.Sender ID defaulted to Corporate GLN for all external Partners and location GLN for internal packaging lines. ')]</value>
      <webElementGuid>cf04fc03-3fe6-4663-b637-f5687cc79891</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
