<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>System Identifier</name>
   <tag></tag>
   <elementGuidId>0dd1823f-be46-41eb-9688-fe6c049e8457</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SenderddlId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@name,'SenderId')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9c23dcf2-7186-45d5-bd9f-bf59ee1880a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>ac7e8e1b-e809-42ba-812f-544297aa9d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SenderddlId</value>
      <webElementGuid>34a7dbda-4d23-458a-a58d-7108b6da437e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SystemDetails.SenderId</value>
      <webElementGuid>a460c348-e4eb-40c6-bc36-a69521b9a62f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select GLN or SGLN</value>
      <webElementGuid>7e171d84-edfb-48c2-a140-16574f7bfe2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SenderddlId&quot;)</value>
      <webElementGuid>4290cc10-b1e6-41e2-99bd-28e06cbd13b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SenderddlId']</value>
      <webElementGuid>b71010c7-2a88-48ee-adee-fde99d753ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div/div/div/div/div[5]/div/select</value>
      <webElementGuid>aa3a327a-621b-4486-b748-d7b84ccf5c77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sender ID'])[1]/following::select[1]</value>
      <webElementGuid>ef74c9ac-e5bc-43dd-94be-93586e41ce7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System-T3-Code'])[1]/preceding::select[1]</value>
      <webElementGuid>75d28fdd-d7fb-4d52-a60a-98d89231d8c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System generated value'])[1]/preceding::select[1]</value>
      <webElementGuid>8cd8403d-1139-40b7-8f57-650935f53fae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>7ac09fb2-27b0-4104-83df-e29cf235191a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SenderddlId' and @name = 'SystemDetails.SenderId' and (text() = 'Select GLN or SGLN' or . = 'Select GLN or SGLN')]</value>
      <webElementGuid>4330075c-8e27-4d5f-ae63-2fac2485147a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
