<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>System Name</name>
   <tag></tag>
   <elementGuidId>ced2aeb9-ae6d-44ec-a98d-870d186ca125</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SystemName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SystemName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>75dbee4e-ac54-4e00-bbd6-ddb6759954e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SystemName</value>
      <webElementGuid>299b32bc-3b41-4f2d-9f0b-640d5e0d27a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>bb7bb167-6fa2-4b7f-8820-043f8baf79e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter System Name</value>
      <webElementGuid>89eca6cf-eb68-4792-9068-421f43e24de2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3404708d-4687-41cf-941e-e97aa5350561</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>25c0e2cf-f989-42b9-b45a-b314d66067ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>System Name is required</value>
      <webElementGuid>bd5dae02-0e22-4857-a3f1-38a1616573f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SystemDetails.SystemName</value>
      <webElementGuid>78b43c67-5ba8-4ed8-a8d5-3e6777dfb3b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SystemName&quot;)</value>
      <webElementGuid>4b4162ba-0c7b-448e-8c6e-85e29c4349d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SystemName']</value>
      <webElementGuid>577508c1-c8d9-40a5-a979-13fef3eff4cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div/div/div/div/div[2]/div/input</value>
      <webElementGuid>605da45b-753a-491e-9abd-0e2e926d227b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>07d4c635-5ac8-477f-b425-f6250a62a831</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SystemName' and @placeholder = 'Enter System Name' and @type = 'text' and @name = 'SystemDetails.SystemName']</value>
      <webElementGuid>f1705138-d7a0-43be-bb3a-c974be2e522b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
