<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Extension Digit</name>
   <tag></tag>
   <elementGuidId>a6a06b62-5fb9-428a-9cb3-fa4dfb79efc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdExtDigit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ExtensionDigit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>4d689afe-5ed4-426b-93c4-895c4882a80e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ss ml-1</value>
      <webElementGuid>884b4890-050a-4145-b38e-44b06595661c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExtensionDigit</value>
      <webElementGuid>b594efbd-5291-4cae-b2ba-132d9e2b0cf1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PopulateDescription()</value>
      <webElementGuid>7d18fb5b-2a57-4b5f-90b2-abaf34360196</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>38326e23-c6f4-4364-839f-ad382d343559</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ExtensionDigit field is required.</value>
      <webElementGuid>d6549eca-ab12-4de6-a2a7-521ba4f3a649</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.ExtensionDigit</value>
      <webElementGuid>98f155e2-2cc2-4ae2-8326-9948402daa62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select0123456789</value>
      <webElementGuid>150786bf-95db-4ae9-b9be-f57a264d2e4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExtensionDigit&quot;)</value>
      <webElementGuid>a699a2d3-3f4d-42ff-941b-ead1fafac05c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ExtensionDigit']</value>
      <webElementGuid>0ab9b1d4-eab7-4042-8b66-6402780fb8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Ssccserializationprofile']/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>e3262da6-4972-4f21-81ad-db91590e4312</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extension Digit'])[1]/following::select[1]</value>
      <webElementGuid>f6d32e42-112e-4ce8-8be5-aca5556797da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix'])[1]/following::select[2]</value>
      <webElementGuid>184b70c9-e760-492a-93ca-cbe263e86fa1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Filter Value'])[1]/preceding::select[1]</value>
      <webElementGuid>5f6e538f-5a8f-4304-b81c-62e09c972c8e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SSCC Profile'])[4]/preceding::select[2]</value>
      <webElementGuid>54bde56c-e58e-4eac-bd72-4141f803ecc7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>74617e9b-3ed7-4ad7-95e9-6d6a60874a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ExtensionDigit' and @name = 'BasicInfo.ExtensionDigit' and (text() = 'Select0123456789' or . = 'Select0123456789')]</value>
      <webElementGuid>0dc5411a-6512-4fbe-a293-079b5f7a05f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
