<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GS1 Company Prefix</name>
   <tag></tag>
   <elementGuidId>7c952c8b-0129-4aa0-a1ef-09bc54bdc20f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Gs1PrefixId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GS1CompanyPrefixId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9a8d1995-44dd-4889-9631-fa09a0958697</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0</value>
      <webElementGuid>805e5e5d-4776-4483-aff2-1287527cc1de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GS1CompanyPrefixId</value>
      <webElementGuid>bfeaa7f7-d5a9-4e46-b382-07ff76d3141f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PopulateDescription()</value>
      <webElementGuid>7ffa6d8c-8901-4994-a46e-e4c2d6310ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3f402e39-0b65-42f7-883b-69d8fc0e3f97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GS1CompanyPrefixId field is required.</value>
      <webElementGuid>92677090-ad47-4701-81dd-6f5811712e6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.GS1CompanyPrefixId</value>
      <webElementGuid>88b07808-7abe-4ee0-b567-adf6cb31fd37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select GS1 Company Prefix55968</value>
      <webElementGuid>0a405ce9-dd37-4b81-82cc-3c43c451ea0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GS1CompanyPrefixId&quot;)</value>
      <webElementGuid>a1c1c780-9865-4c07-bebd-85e0448b93aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='GS1CompanyPrefixId']</value>
      <webElementGuid>adac302e-a4ca-4e3a-8684-3ec5c798b5ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Ssccserializationprofile']/div/div[2]/div/select</value>
      <webElementGuid>3f2a5672-5366-4846-a87b-6965eee60948</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix'])[1]/following::select[1]</value>
      <webElementGuid>bead1b62-072e-4f54-90ce-f34002bf3fc9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Name'])[1]/following::select[2]</value>
      <webElementGuid>c2c42202-bdf3-4eb8-9a44-bb09a0db88b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extension Digit'])[1]/preceding::select[1]</value>
      <webElementGuid>7c1b6006-dc3c-4aec-9986-7a8269838185</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Filter Value'])[1]/preceding::select[2]</value>
      <webElementGuid>5336c9be-4cfc-4c56-b356-96cc07a6af88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>c51fe527-22f8-44f3-af16-ead858379da8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'GS1CompanyPrefixId' and @name = 'BasicInfo.GS1CompanyPrefixId' and (text() = 'Select GS1 Company Prefix55968' or . = 'Select GS1 Company Prefix55968')]</value>
      <webElementGuid>03059947-4e71-4ba4-af4c-cd7d34ac3422</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
