<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Requesting System</name>
   <tag></tag>
   <elementGuidId>2c694b44-06f2-4989-867d-4918b25789fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdReqSystem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdRequestingSystem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>84e05606-f712-4078-bdde-b89c7289858f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms sgtinrequestingsysinput</value>
      <webElementGuid>49d37ee8-8fad-44f4-ab65-3a85a1b0183f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdRequestingSystem</value>
      <webElementGuid>3b1f9c77-5aef-45c5-b5eb-ee80186a9e80</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2c4d532a-d4d6-47b2-b7d1-39dd1683a1c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RequestingSystem field is required.</value>
      <webElementGuid>b5d0f36a-da06-4e2e-ba2d-c97dca850f14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sgtin.RequestingSystem</value>
      <webElementGuid>b6457ddd-cfc7-4ec0-b04d-46ff0908af05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select SystemSystem Party Automation 883</value>
      <webElementGuid>1354b099-95a1-499f-b4bc-e06832be27e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdRequestingSystem&quot;)</value>
      <webElementGuid>1c407ff6-ff72-47fd-8e3e-d46e4beaaddc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdRequestingSystem']</value>
      <webElementGuid>1fcad938-fc2a-424e-8a00-846f35ea8b87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IdsystemRequest']/select</value>
      <webElementGuid>b39c372f-615f-4f1f-b30e-f58629926cf2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting System'])[1]/following::select[1]</value>
      <webElementGuid>9ee3823f-075e-4c32-bf24-2eb8c5b682ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting Party'])[1]/following::select[2]</value>
      <webElementGuid>9f261f70-5f7c-40ee-81bf-02a71e4fc472</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGLN'])[1]/preceding::select[1]</value>
      <webElementGuid>e85e7d7c-b092-44ba-9917-9ba52573c21d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Mode'])[1]/preceding::select[1]</value>
      <webElementGuid>b5e31996-a064-497e-aef1-9b074b0197d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>b12748e2-9cce-4805-9f7e-06d0e53ff865</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdRequestingSystem' and @name = 'Sgtin.RequestingSystem' and (text() = 'Select SystemSystem Party Automation 883' or . = 'Select SystemSystem Party Automation 883')]</value>
      <webElementGuid>571d43b4-d095-4908-bd5e-bcd5135b31b3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
