<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Requesting Party</name>
   <tag></tag>
   <elementGuidId>6ccf66ca-5aff-4c1b-8b7c-1b0e8d2625da</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdReqPartyssscc']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdReqParty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>67588903-77d4-4124-84e9-b5821e5b2296</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-4</value>
      <webElementGuid>c02e1a00-8707-41f4-a3e4-92d7ac974211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdReqParty</value>
      <webElementGuid>ae991e88-3e9b-4769-8479-7a192573e4a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>RequestingpartySgtin()</value>
      <webElementGuid>230c806b-7cdc-4135-a927-4c0df027bfa4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>337679f8-aefe-452b-a20a-44ab4d095ba8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RequestParty field is required.</value>
      <webElementGuid>1104e3e1-f3ae-477b-9003-fc48433c171d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sgtin.RequestParty</value>
      <webElementGuid>09eeb35f-037f-434f-9ed3-885a9da14647</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Requesting PartyParty Automation 883</value>
      <webElementGuid>857ec55a-ea51-433f-abb8-081e541e103b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdReqParty&quot;)</value>
      <webElementGuid>19315957-a170-474a-86c5-43f3150135ae</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdReqParty']</value>
      <webElementGuid>e4a001bb-2567-4082-b8a3-d75c23e9de47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_sgtin']/div[4]/div/select</value>
      <webElementGuid>3ae647d7-0181-430b-82b8-3828c50a18cb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting Party'])[1]/following::select[1]</value>
      <webElementGuid>68c60bfc-0e8f-43d3-9b53-6e6abf3b7584</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGTIN Profile Version No.'])[1]/following::select[1]</value>
      <webElementGuid>7c6a590c-9d70-4275-a896-2827ffe7c270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting System'])[1]/preceding::select[1]</value>
      <webElementGuid>13db4337-4ee5-44eb-8a45-4dac7b5c9f09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGLN'])[1]/preceding::select[2]</value>
      <webElementGuid>f7ada173-3715-4891-b357-595437c84a8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>d4d8d9b4-69e7-462d-aa2d-0826357c5669</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdReqParty' and @name = 'Sgtin.RequestParty' and (text() = 'Select Requesting PartyParty Automation 883' or . = 'Select Requesting PartyParty Automation 883')]</value>
      <webElementGuid>488d8028-b3a2-40cb-9000-a23806498079</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
