<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Alert Available Range</name>
   <tag></tag>
   <elementGuidId>2b0b29b0-b7ac-457d-a6a1-82c3ed9a3982</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#AlertAvailableRangeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='AlertAvailableRangeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>51edafa8-4b2a-4f14-b8fc-8db137c733fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>AlertAvailableRangeId</value>
      <webElementGuid>f117d52a-65d6-4689-b63c-777c8b6ffa7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>9bee1620-42da-4343-ae62-efa37babd2f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Alert Available Range %</value>
      <webElementGuid>296ef9d4-eaf5-4b6a-b45b-f05b3729bca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>fe865704-2d5e-48a1-815b-7f9ceda9ff4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ca878ac-f7d0-444e-8ee8-32ebf7563a2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range</name>
      <type>Main</type>
      <value>Range cannot be more than 100%</value>
      <webElementGuid>d092377f-276f-40f4-8533-ba0a04380b4c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-max</name>
      <type>Main</type>
      <value>100</value>
      <webElementGuid>00fbaa5f-f9c1-4020-9d6c-1ad154799c27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-range-min</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>fb23e8b3-bf79-462a-8d17-a3d31ac0f659</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The AlertAvailableRange field is required.</value>
      <webElementGuid>1f0cd281-7c54-4cb2-9d77-13854b9b254d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.AlertAvailableRange</value>
      <webElementGuid>028042ac-6f3f-46a9-9eb0-1c64728f2203</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>25</value>
      <webElementGuid>1793d7f7-51fd-476f-a9e5-b3c5624f3c0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;AlertAvailableRangeId&quot;)</value>
      <webElementGuid>8e7e7911-00e8-4613-99bf-be835b25cb71</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='AlertAvailableRangeId']</value>
      <webElementGuid>64dd6e24-df9a-4200-bcfa-190e83ec524b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[11]/div[3]/input</value>
      <webElementGuid>b5a2feba-b0e6-44cc-9239-ee2e6c8887a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[3]/input</value>
      <webElementGuid>eb720aef-5c12-43b5-9f9c-bb9022978e4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'AlertAvailableRangeId' and @placeholder = 'Enter Alert Available Range %' and @type = 'number' and @name = 'TemplateDetails.AlertAvailableRange']</value>
      <webElementGuid>1dba3650-4d47-4159-aa8b-c472208b0b2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
