<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Allow Leading Zero</name>
   <tag></tag>
   <elementGuidId>73a09b86-39c0-44f1-911a-8e0bc747f144</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='AllowLeadingZero']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SNType</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>0ab639ae-1b9b-47f2-9c93-795ee8183b29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SNType</value>
      <webElementGuid>8e61374c-4802-4f25-8eb8-cfb739ad0d3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>6f3a8f45-9f60-42a8-97c0-e7fc9e635b6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>SNTypeChange()</value>
      <webElementGuid>ec0a265e-7489-4074-9ab3-e677aeeefdc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d3087904-adc6-4c36-9c93-b01a21076923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Serial Number Type is required</value>
      <webElementGuid>34375423-963f-4c66-aac2-6c297bd99a40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.SerialNumberTypeId</value>
      <webElementGuid>d8b0a467-372d-4eb8-b960-5b43bb30e4c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Serial Number TypeSequentialRandom</value>
      <webElementGuid>4ab3dde5-c5e5-4acb-a8f9-3bde26b7988d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SNType&quot;)</value>
      <webElementGuid>a7514a1d-23f2-4e77-b4f6-d458cb8f742b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SNType']</value>
      <webElementGuid>ec56e6da-2f70-4ebb-9326-65144fbc2442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[4]/div/div/select</value>
      <webElementGuid>474a9237-ef33-4b9f-97c9-cb1708586447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Type'])[1]/following::select[1]</value>
      <webElementGuid>fed738e5-788a-4725-8051-7352863ddd06</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason for Status Change'])[1]/following::select[1]</value>
      <webElementGuid>1e84d63f-1948-4ada-8c47-c385389fb189</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Length'])[1]/preceding::select[1]</value>
      <webElementGuid>792588ff-dc1c-4cc8-931e-bdd76a514a4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Character Set Type'])[1]/preceding::select[1]</value>
      <webElementGuid>7ec8a90a-98a7-429a-8a56-713ece22c348</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>d1e8a338-8d91-42eb-a86d-eb7855df2bd6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SNType' and @name = 'TemplateDetails.SerialNumberTypeId' and (text() = 'Select Serial Number TypeSequentialRandom' or . = 'Select Serial Number TypeSequentialRandom')]</value>
      <webElementGuid>7fe5f674-9628-4464-8e50-53b2b859ad69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
