<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Coding Schema</name>
   <tag></tag>
   <elementGuidId>b5798983-e3cc-41ad-b9bc-9ee9af7b3be5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IdCodingschemaid</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdCodingschemaid']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a7f92c70-ca3f-4820-be96-998de2c15e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdCodingschemaid</value>
      <webElementGuid>1fe8e4c4-6e05-4b17-b152-98b2ac0de5cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row textboxtemplate ml-2 pl-1</value>
      <webElementGuid>3e76d443-7a5d-4e89-afbc-436f7d9c451e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>CodingSchemaChange()</value>
      <webElementGuid>df98de14-4cbc-4aa7-97a0-36ef9f0394c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5d1c6841-59b3-4783-b67d-1f658508a543</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The CodingSchemaId field is required.</value>
      <webElementGuid>510cb373-a36b-477b-b762-934a7212a1d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.CodingSchemaId</value>
      <webElementGuid>9f2b8ff5-f0d6-46ad-bf1e-02021a32e989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SGTIN-96SGTIN-198</value>
      <webElementGuid>2cf5b94c-ebc0-46da-a0e9-a7227288aed5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdCodingschemaid&quot;)</value>
      <webElementGuid>68a5237f-0eb4-4572-b9c2-3acf1ffea5b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdCodingschemaid']</value>
      <webElementGuid>51fd9b83-cf7b-433c-ac35-f0b53fee593e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[2]/div[2]/select</value>
      <webElementGuid>c9e7b107-6c38-4478-aa0f-5fdcc2a14d57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coding Schema'])[1]/following::select[1]</value>
      <webElementGuid>6fdf8180-b0c5-4cb4-820e-692f01fab86d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EPC Schema'])[1]/following::select[2]</value>
      <webElementGuid>5c410ead-aa81-461b-9fc1-011817d12a33</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>d3fd0f0b-f76d-4fde-ac7a-6b57845cc419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::select[1]</value>
      <webElementGuid>173f899e-4140-4436-bf8c-beae7eb05b44</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>ff4e7ae2-ae45-4f4f-a543-54e458c1a16c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdCodingschemaid' and @name = 'TemplateDetails.CodingSchemaId' and (text() = 'SGTIN-96SGTIN-198' or . = 'SGTIN-96SGTIN-198')]</value>
      <webElementGuid>d509c261-0775-4bb6-b87d-1c84b4b25f44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
