<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>EPC Schema</name>
   <tag></tag>
   <elementGuidId>7cdea6f4-3972-4ee7-b935-785e8b50e981</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#IdEPCSchemaCodeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdEPCSchemaCodeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>aa5991f5-d3ef-4e6a-a873-cff7181478c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdEPCSchemaCodeId</value>
      <webElementGuid>fe24cc13-4271-4e78-8023-63576239e114</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row textboxtemplate pl-1</value>
      <webElementGuid>3c514b90-eef6-447d-bdd1-1ec46b73c5df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>EPCSchemChange()</value>
      <webElementGuid>d6616849-077d-48fb-8913-36f876ab86b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>464305ee-4865-4353-a2da-d5fb0b692580</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>EPC Schema is required</value>
      <webElementGuid>e3dcb043-4e78-4ab1-81b7-eb4ba006359b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.EPCSchemaCodeId</value>
      <webElementGuid>d4334e3a-6e97-4074-83f6-6714c19ab59d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select EPC SchemaSGTINSSCC</value>
      <webElementGuid>904f5356-9c0f-446d-ad1e-6cad192fcb2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdEPCSchemaCodeId&quot;)</value>
      <webElementGuid>dd642573-7b36-4aee-9925-4a5a33e3f5b2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdEPCSchemaCodeId']</value>
      <webElementGuid>052620fd-e81d-4738-be44-62516ebc3349</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[2]/div/select</value>
      <webElementGuid>534334fe-b7a9-4ea4-bf44-80d0d659d8df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EPC Schema'])[1]/following::select[1]</value>
      <webElementGuid>d878e791-fafc-46ae-815a-18dd27991771</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/following::select[1]</value>
      <webElementGuid>9af6029e-6ba8-44a3-8f27-f9ac2961d741</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Coding Schema'])[1]/preceding::select[1]</value>
      <webElementGuid>10b450c6-3f3c-4a54-a186-65d9c07e0848</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[2]</value>
      <webElementGuid>5934c8df-2a74-4684-95e0-7947119fb33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>e845774e-bf32-4a5f-828e-58d81fe2d754</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdEPCSchemaCodeId' and @name = 'TemplateDetails.EPCSchemaCodeId' and (text() = 'Select EPC SchemaSGTINSSCC' or . = 'Select EPC SchemaSGTINSSCC')]</value>
      <webElementGuid>15ea407e-5cd5-47dc-81eb-809aa42570ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
