<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AN_Upper Case</name>
   <tag></tag>
   <elementGuidId>60017fd7-7ff3-458d-a0b8-dacff35b3670</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioNumerUC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioNumerUC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>940747cd-4adc-49ac-a227-089d127ee2b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioNumerUC</value>
      <webElementGuid>97af46c8-21ba-472c-bc77-e3379d9cce97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radiogroup</value>
      <webElementGuid>c7f21b54-efcb-48ec-bc94-fa19d8084c8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>7db78e5d-3572-41fc-b5cf-77a376e22beb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>92df80f9-399f-46b9-9f47-9be4c5b489d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>c3af72d8-669f-4012-9d15-f005f7d81d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>NumericRadioClick(2)</value>
      <webElementGuid>b3acacc8-9051-4111-9042-8d7c88e6156f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioNumerUC&quot;)</value>
      <webElementGuid>093c1764-4eb7-4bb9-9177-a066a92fe7ad</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioNumerUC']</value>
      <webElementGuid>fae83809-d579-451f-aed7-61318226b565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IdradioNumerUC']/input</value>
      <webElementGuid>2635cb04-d967-450d-b2e2-9b2462fc21d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[2]/input</value>
      <webElementGuid>391fb8b0-22f0-411a-b893-64385a50d42a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioNumerUC' and @name = 'radiogroup' and @type = 'radio']</value>
      <webElementGuid>bad1c39b-3457-4e5f-af8a-387ce4ff1a9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
