<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_AN_Lower Case</name>
   <tag></tag>
   <elementGuidId>ea005706-c786-424d-9d2d-65f4f6c24a2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#radioNumerLC</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='radioNumerLC']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2949cd86-0474-41f1-961e-391db2a2aeae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>radioNumerLC</value>
      <webElementGuid>adfc1c50-2081-4283-966d-98b8f2375407</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>radiogroup</value>
      <webElementGuid>fd0fe0ae-f68b-4eb7-a3c4-5b578bf5b06c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>28de35f3-ad22-4ed9-8888-52a89ee1e2dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>dc7d9df6-9781-4820-8b63-3de420a2c402</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>02c1af74-5c69-49c3-91dd-deb2c7bc1a0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>NumericRadioClick(3)</value>
      <webElementGuid>9a0edcd4-58a5-4fc8-ab6b-53b6650b80e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;radioNumerLC&quot;)</value>
      <webElementGuid>f048a6d7-e196-4b25-8549-5fe24fb86a51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='radioNumerLC']</value>
      <webElementGuid>543ce71a-1a3d-4123-88a2-64a34df083ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IdradioNumerLC']/input</value>
      <webElementGuid>3d27efb4-3af0-4f1d-abee-5c808baf1c63</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/div/div/div[3]/input</value>
      <webElementGuid>a38faee4-e623-49d1-917c-29ce2938e7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'radioNumerLC' and @name = 'radiogroup' and @type = 'radio']</value>
      <webElementGuid>cfea4231-9a1f-4db6-b4b4-c10d227d7782</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
