<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Max Serial Numbers</name>
   <tag></tag>
   <elementGuidId>2bb0272b-68fc-438d-b4fd-3ddd942dca24</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MaxSno</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='MaxSno']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2399ef5b-1d67-48e4-a164-a2243eda5030</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MaxSno</value>
      <webElementGuid>5eaf5fad-3359-4309-9eb2-59fdd5736805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms autodisplayBgcolor</value>
      <webElementGuid>6275f4ee-ef1c-4b2e-b009-3956c012532c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>system generated</value>
      <webElementGuid>e2ebd276-9b50-46f7-a8d0-600016ba296b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d80d5c7e-73a6-4193-98ec-a7978df7a943</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.MaxSerialNumbers</value>
      <webElementGuid>670d75c6-05a3-43c7-9e61-cd366c47c7a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MaxSno&quot;)</value>
      <webElementGuid>6845cf3f-db7b-485d-97cd-6d62491a5a74</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='MaxSno']</value>
      <webElementGuid>997c8815-811f-4624-a77d-1394f93faf64</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rangesdiv']/div[3]/input</value>
      <webElementGuid>beb363d1-f4df-409b-8b8f-729c2b55c7b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[3]/input</value>
      <webElementGuid>05d65deb-a5c3-4451-b52c-b26fed03e39b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'MaxSno' and @placeholder = 'system generated' and @type = 'text' and @name = 'TemplateDetails.MaxSerialNumbers']</value>
      <webElementGuid>98ddf186-55cd-4f72-9b63-a0dae7cf6ff2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
