<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Range Start</name>
   <tag></tag>
   <elementGuidId>c9054ddc-f8a5-4746-9c8f-713bc91c77c3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RangeStart</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RangeStart']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6ef8fcdb-ce96-4fe2-914d-72542342f57c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RangeStart</value>
      <webElementGuid>66ecaf57-175b-4bae-87d9-184220bf6954</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row textboxtemplate autodisplayBgcolor pl-1</value>
      <webElementGuid>b92a234b-75a9-4392-891a-9986b245ce2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>system generated</value>
      <webElementGuid>2e9df1d9-c6ea-4b69-8caa-0c95ec69a4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>519dd9cf-295d-4eec-8376-eb061e17c2fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.SerialNumberFrom</value>
      <webElementGuid>0c68f076-c5a0-497d-b3b9-30c344470fae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RangeStart&quot;)</value>
      <webElementGuid>029792de-9033-4ce4-87f6-0f1e7e6482d6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RangeStart']</value>
      <webElementGuid>1be88520-71ec-4acc-8347-693e466a925b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rangesdiv']/div/input</value>
      <webElementGuid>3057ad42-cd03-47f6-9262-28f6f6212bf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/input</value>
      <webElementGuid>4b805855-d361-4660-a431-b7cec315e473</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'RangeStart' and @placeholder = 'system generated' and @type = 'text' and @name = 'TemplateDetails.SerialNumberFrom']</value>
      <webElementGuid>94cf8fc1-3b1b-4f83-b059-f48fd0779289</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
