<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Serial Number Type</name>
   <tag></tag>
   <elementGuidId>71956d42-7280-45e7-a690-1c6e4d3ea682</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SNType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SNType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>92e86c54-dd07-4410-9d91-9aaa0d156d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SNType</value>
      <webElementGuid>80aaf6a5-d3db-4fc5-b0ad-c79c09a69a2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>a456646c-7f85-427b-8818-f23a4cf211b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>SNTypeChange()</value>
      <webElementGuid>2a6c4a11-6c9e-4ef4-973a-43f42cfa7e5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ffc3fd15-2a69-4a3f-b8bd-241cc9b55a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Serial Number Type is required</value>
      <webElementGuid>75e981c9-456c-4b5a-b638-d0e93c497afc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.SerialNumberTypeId</value>
      <webElementGuid>6405c980-1b49-41af-be75-714a9a23beda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Serial Number TypeSequentialRandom</value>
      <webElementGuid>63488db5-9d65-46b6-bd1f-2f3f4a8e56bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SNType&quot;)</value>
      <webElementGuid>03482d51-a28c-4021-bc1a-a61215731219</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SNType']</value>
      <webElementGuid>f74e0c77-2e2b-488f-bd4d-653f1922f58d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[4]/div/div/select</value>
      <webElementGuid>50adffbf-bca8-4549-b377-352a863d6a10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Type'])[1]/following::select[1]</value>
      <webElementGuid>b814cb6e-523e-4e1c-b1d1-998f17718840</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason for Status Change'])[1]/following::select[1]</value>
      <webElementGuid>6eec8ccb-b705-4798-b559-a5bfdb4f3b8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Length'])[1]/preceding::select[1]</value>
      <webElementGuid>6a8737ea-ad06-4a59-8819-a98b81510ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Character Set Type'])[1]/preceding::select[1]</value>
      <webElementGuid>81842995-610d-436d-abba-d4fd70f3189e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/select</value>
      <webElementGuid>342a8eec-1294-4330-b2d0-ae795ece2054</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SNType' and @name = 'TemplateDetails.SerialNumberTypeId' and (text() = 'Select Serial Number TypeSequentialRandom' or . = 'Select Serial Number TypeSequentialRandom')]</value>
      <webElementGuid>c1d7761c-3d2a-4ee0-b0c4-f7b914af4a04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
