<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Serial Number Length</name>
   <tag></tag>
   <elementGuidId>ee1c8c5f-93fb-4ffd-aa4d-d9a1328b8ac2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SNLength</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SNLength']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>63774e10-50d2-499a-ae44-df5e40f0d3f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SNLength</value>
      <webElementGuid>65d1f48a-6fba-4139-8bfa-79cf8774e946</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nameSNLength</value>
      <webElementGuid>771a8a5a-fdab-4b7c-a0af-745c51468cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>25305cda-a8ba-45e4-a36f-a6da8e2e1d15</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Serial Number Length</value>
      <webElementGuid>a1743029-a0d1-40cb-9199-6f4d916ec6f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>SNLengthChangeEvent()</value>
      <webElementGuid>9d830ac4-4823-4298-9334-6d330a8ab8fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>SNLengthChangeEvent()</value>
      <webElementGuid>70ad2bc0-9a02-4466-86cf-bda8507f653a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>a83d654f-20f2-43bf-b27a-303c96f64ad8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>601d57ff-d9e9-4baf-92c6-b6593e4193f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SerialNumberLength field is required.</value>
      <webElementGuid>2940240f-19f0-4a74-ad94-773e67c029ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>def4fe6e-9e6d-4a27-be2d-96a1def77dd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SNLength&quot;)</value>
      <webElementGuid>7f40f714-d854-4dd6-9c03-5be13ffffe14</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SNLength']</value>
      <webElementGuid>32b8c3e8-ac0c-4f61-90ee-750449029b50</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Snlength']/input</value>
      <webElementGuid>4a5121e7-ba9d-472b-8c6b-d9aee158f0e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>ee19a99c-a7f7-4ae9-ac5f-e7f17410de16</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SNLength' and @name = 'nameSNLength' and @placeholder = 'Enter Serial Number Length' and @type = 'number']</value>
      <webElementGuid>9e5a8f26-1f03-4a48-9472-7862b5b1ebf7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
