<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sparseness Factor</name>
   <tag></tag>
   <elementGuidId>a16a2a4c-23c8-44fd-a80c-f7802fed7e6a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#SparsenessFactorId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SparsenessFactorId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a8538301-1ca5-4dce-b0c9-d6a5d0d4cbf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SparsenessFactorId</value>
      <webElementGuid>66658d1c-e175-42b2-a96b-ddec74292d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>22ee3a69-00e5-4da9-9c31-172d29fb3e4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>SNLengthChangeEvent()</value>
      <webElementGuid>977e7d1e-c775-47cc-964c-397136cfb65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f54a6658-7a30-49a7-8d47-84e975b10231</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SparsenessFactor field is required.</value>
      <webElementGuid>9e7ab48f-11f9-438b-a798-6a0d4878c451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.SparsenessFactor</value>
      <webElementGuid>7ec8486d-aff5-43ea-9506-f4e046d4b803</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>110100100010000</value>
      <webElementGuid>5044d826-0096-460b-b8df-41c227caca5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SparsenessFactorId&quot;)</value>
      <webElementGuid>2df3534d-e5de-48cc-b85f-e933382ee431</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SparsenessFactorId']</value>
      <webElementGuid>4cb5c94b-22de-4a82-92bf-f0053f5445cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IdSparsFactor']/select</value>
      <webElementGuid>f4a849eb-8e63-4809-ab02-5727b70893c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sparseness Factor'])[1]/following::select[1]</value>
      <webElementGuid>a49c68d2-9c15-4dcf-8a4c-31c379472211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='z'])[1]/following::select[1]</value>
      <webElementGuid>dc17fe74-4cb0-49f4-a958-51a3e415fa3a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uniqueness'])[1]/preceding::select[1]</value>
      <webElementGuid>b50cf7ac-9045-49c2-babb-00374895f080</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Template Name'])[2]/preceding::select[2]</value>
      <webElementGuid>e9021e52-ddbb-41d9-9992-11ea6f73c09f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/select</value>
      <webElementGuid>b25bc9bd-524e-4ff7-bc02-5fb8b7e0d9b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SparsenessFactorId' and @name = 'TemplateDetails.SparsenessFactor' and (text() = '110100100010000' or . = '110100100010000')]</value>
      <webElementGuid>b5869b25-1565-421b-9d92-62d50d6b7576</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
