<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_Active</name>
   <tag></tag>
   <elementGuidId>ac950d1a-1a3e-4e77-aa44-be1a79a63ee5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idStatusActive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idStatusActive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ac097841-76cd-4ced-825e-b142e01c0d34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idStatusActive</value>
      <webElementGuid>f25f51e6-2b4a-4cc1-8cda-ba7ea8564d38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>ccc8c545-f5a2-4180-9af6-55abdc1e7836</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>a7adf307-7101-4989-b942-a7348c35bf11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>932cc553-65b4-4079-a66a-24a11c77ed31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleReasonStatusChange(2)</value>
      <webElementGuid>e97d1fe0-7b99-4ee0-a250-01d1aa91b033</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.SNStatusId</value>
      <webElementGuid>dff5b69a-57a2-452f-b642-34dbd3f483aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idStatusActive&quot;)</value>
      <webElementGuid>a971455c-c652-4a18-a971-cc31ebd1c647</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idStatusActive']</value>
      <webElementGuid>a6d56e98-ae46-4ee7-9ec5-6c7ed6ffbacd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[2]/div[3]/div/div[2]/input</value>
      <webElementGuid>1b73c62f-b125-4358-a4a8-ada67523d68a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>892bec3e-b02d-4e0d-8af8-d9eff97a66b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idStatusActive' and @type = 'radio' and @name = 'TemplateDetails.SNStatusId']</value>
      <webElementGuid>77a115db-6dd4-4661-9f0e-519680894f67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
