<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_Draft</name>
   <tag></tag>
   <elementGuidId>fee14944-939a-4cb2-9652-854b727d717d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#idStatusDraft</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='idStatusDraft']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21338ecb-6d1d-4e29-91d5-6696e7444569</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>idStatusDraft</value>
      <webElementGuid>a125d107-2248-4d51-8be4-630f563d6158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>2995cb13-709e-46f0-9b0c-fe495d754633</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleReasonStatusChange(1)</value>
      <webElementGuid>b73a0cb0-9bda-44d5-82f0-0ccffa1c1b31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2bc2442a-2bce-40f3-9207-0fd62e98fef7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>64e3b0a3-0769-48ad-b79f-b06e5c54d6e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63e43054-6f7d-4166-855a-9091bb721ab8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>SNStatus is required</value>
      <webElementGuid>49922795-56d5-48d7-b3d9-5d42bdab8b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.SNStatusId</value>
      <webElementGuid>94a6bdfc-5a23-43c6-b109-20af25a0fa10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;idStatusDraft&quot;)</value>
      <webElementGuid>511de88f-17c4-4868-902c-d805e5d685a5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='idStatusDraft']</value>
      <webElementGuid>b960aa98-3c13-4732-a71e-b8e2f0d63aa7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[2]/div[3]/div/div/input</value>
      <webElementGuid>7654ce41-7578-45db-8055-78f9b934f745</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/input</value>
      <webElementGuid>a87d4cba-2cf4-4304-95f9-2ce24e60a516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'idStatusDraft' and @type = 'radio' and @name = 'TemplateDetails.SNStatusId']</value>
      <webElementGuid>29151622-7472-45bb-8c42-d6a77ed38f29</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
