<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Extension Digit</name>
   <tag></tag>
   <elementGuidId>6adbc774-c590-4bf5-927f-8172d277d636</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ExtensionDigit']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ExtensionDigit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>af45a828-e136-4d2e-9afb-41e977c161ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ss ml-1</value>
      <webElementGuid>b469960b-db94-4e85-abd7-d5afeea9de0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ExtensionDigit</value>
      <webElementGuid>90884580-1d8e-49ed-bc8d-cee57935f75c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PopulateDescription()</value>
      <webElementGuid>fa1a74a9-91ed-4d45-a73c-5eacd67e09e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>301f23fa-c4aa-4462-b59c-ab780e133582</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ExtensionDigit field is required.</value>
      <webElementGuid>c9ece0f2-404c-4dc3-bc6c-087ee4945788</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.ExtensionDigit</value>
      <webElementGuid>ff223ff4-230f-42d0-b651-060b8a1e39fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select0123456789</value>
      <webElementGuid>40a19e86-15ea-48d4-8962-c76cee22a608</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ExtensionDigit&quot;)</value>
      <webElementGuid>de3be927-4696-4942-a647-ebf919034986</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ExtensionDigit']</value>
      <webElementGuid>7020ecfc-81ee-46f8-95f5-88d7f9faaf92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Ssccserializationprofile']/div/div[2]/div[2]/div/div/select</value>
      <webElementGuid>d9c41d16-9664-4e51-9c98-0fe41e824578</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extension Digit'])[1]/following::select[1]</value>
      <webElementGuid>3bd71c95-ec8e-4827-8eb2-6f90d8833a0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix'])[1]/following::select[2]</value>
      <webElementGuid>69ca5e30-e2c5-4230-a29b-3685a3d23d90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Filter Value'])[1]/preceding::select[1]</value>
      <webElementGuid>2e23d828-7c62-4440-b689-62ca30b40863</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SSCC Profile'])[4]/preceding::select[2]</value>
      <webElementGuid>10a5a44b-bcfb-4023-a5da-5177744d67fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/select</value>
      <webElementGuid>62d2d472-7136-491a-9c6c-9a38850d4f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ExtensionDigit' and @name = 'BasicInfo.ExtensionDigit' and (text() = 'Select0123456789' or . = 'Select0123456789')]</value>
      <webElementGuid>305bd113-c9b7-40b1-abe2-2f659b97f991</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
