<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GS1 Company Prefix</name>
   <tag></tag>
   <elementGuidId>7c001152-b989-40c5-a21e-bfe7a9522726</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='GS1CompanyPrefixId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#GS1CompanyPrefixId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5edf1792-5ed0-48f6-a3f0-c677995760d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0</value>
      <webElementGuid>37983920-1afa-436c-b0fb-f0c6b0545019</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>GS1CompanyPrefixId</value>
      <webElementGuid>cb2ea5cf-f199-4186-b59a-b2ef1673ccc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PopulateDescription()</value>
      <webElementGuid>dbd14a2e-a6f1-4403-81b1-c7b51728741f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a3b90fa-f877-46ea-82e2-8672bcdf75ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GS1CompanyPrefixId field is required.</value>
      <webElementGuid>9e996238-f22b-4243-bd3f-5d3b74b90ae0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.GS1CompanyPrefixId</value>
      <webElementGuid>88e9d2a9-6d7e-4bbc-acba-4487c892f616</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select GS1 Company Prefix55968</value>
      <webElementGuid>7a7eeed0-9d61-4074-8a5f-b8edf84b08c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;GS1CompanyPrefixId&quot;)</value>
      <webElementGuid>a553c24e-c134-4e38-a443-0a06897781a6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='GS1CompanyPrefixId']</value>
      <webElementGuid>637448c0-030e-4f9c-a12e-a64644e4a53a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Ssccserializationprofile']/div/div[2]/div/select</value>
      <webElementGuid>1e6b671e-1a68-40bc-9e1c-70ffa27a5ac8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix'])[1]/following::select[1]</value>
      <webElementGuid>148cdca5-ce86-44fb-8ab2-79f3bfa5378a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Name'])[1]/following::select[2]</value>
      <webElementGuid>b5a55bfc-3d6b-43d9-9bc6-86ab7dceb8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extension Digit'])[1]/preceding::select[1]</value>
      <webElementGuid>4c15ad59-d2e1-49c8-8c9b-418807bacb5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Filter Value'])[1]/preceding::select[2]</value>
      <webElementGuid>e1e31c8e-7092-423b-8840-fa7209b2da20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>d32b12f4-9c9c-4137-b911-940eb0c1df2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'GS1CompanyPrefixId' and @name = 'BasicInfo.GS1CompanyPrefixId' and (text() = 'Select GS1 Company Prefix55968' or . = 'Select GS1 Company Prefix55968')]</value>
      <webElementGuid>d71c9f9e-2209-4691-be18-0c42e12104c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
