<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Party Name</name>
   <tag></tag>
   <elementGuidId>d1d00311-087f-4ef6-9fad-99b1f34f3f85</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PartyNameId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PartyNameId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1ae31a08-6836-43d2-9757-d78a944f05b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0</value>
      <webElementGuid>0456d2f4-9902-4a9d-a96a-0f913eb5f163</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PartyNameId</value>
      <webElementGuid>33fd183e-5737-43f1-84cb-6b3d83818618</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PartyChange(this)</value>
      <webElementGuid>767779e7-15bc-457c-bbe4-ec5a4cf5ead4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3d0d1d9a-a2cd-4b16-abcf-0301edd966a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PartyNameId field is required.</value>
      <webElementGuid>5a8bcbc5-e4e4-4f08-9ec1-3a9d3202ccc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.PartyNameId</value>
      <webElementGuid>67fe6ef1-dd28-4f88-86d1-c2f7b9653800</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827</value>
      <webElementGuid>1cee5792-8fa7-4d5a-af6a-abbe26b157f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PartyNameId&quot;)</value>
      <webElementGuid>3ecd5c0a-9114-48d9-af53-3437d28e4780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PartyNameId']</value>
      <webElementGuid>b8391c95-946e-4014-9241-774012e04e23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Ssccserializationprofile']/div/div/div/select</value>
      <webElementGuid>6494dde8-da00-4fa7-87d4-3e39077bf749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Name'])[1]/following::select[1]</value>
      <webElementGuid>74ee5d8f-3a02-4f39-a9a4-4df396a449b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::select[1]</value>
      <webElementGuid>3d325236-c382-49b4-a21f-420ba11a736b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix'])[1]/preceding::select[1]</value>
      <webElementGuid>5da86b0e-d815-4db1-ac9e-9fca04bad1c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extension Digit'])[1]/preceding::select[2]</value>
      <webElementGuid>d5f8e222-4172-46f1-9207-16b81e5154e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>9d5d6c5b-3d78-4fbd-91af-c0ee0d1a8789</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PartyNameId' and @name = 'BasicInfo.PartyNameId' and (text() = 'Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827' or . = 'Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827')]</value>
      <webElementGuid>d7772ed4-f63c-4b7e-a054-c32818cbe021</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
