<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Serial Number Source</name>
   <tag></tag>
   <elementGuidId>2805bbc0-8e01-410b-ae29-1ebd626b75f6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id, 'SerialNumberSourceId')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3651f103-fae4-49da-8332-a9751673968b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SgtinVersion[0].SerialNumberSourceId</value>
      <webElementGuid>bc3578ce-fd78-43b9-8fd0-3950d89a1929</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0</value>
      <webElementGuid>e3e4e014-d3f7-402c-8503-920893a91e40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>SNSourceChange(this)</value>
      <webElementGuid>d7826ce5-3a00-41c3-a29a-13dec883cedc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c19663b1-96f0-429a-984e-7f2f251b5cfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SerialNumberSourceId field is required.</value>
      <webElementGuid>8ff93da0-5a57-4353-b5a4-86b6d7700bc8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SgtinVersion[0].SerialNumberSourceId</value>
      <webElementGuid>4f6ee908-cf58-4f1a-a672-910d037549a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Serial Number SourceInternally generatedEnterprise SNM SystemPartner SNM SystemImportedProvisioned by Packager</value>
      <webElementGuid>2cdf2ca5-87c2-42e4-b5c5-4b6537b5d7e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SgtinVersion[0].SerialNumberSourceId&quot;)</value>
      <webElementGuid>6f714f00-9aeb-4448-b6f7-f71a6049e1ea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SgtinVersion[0].SerialNumberSourceId']</value>
      <webElementGuid>fbdaf55a-919a-457d-84e7-61fc91299148</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Addsgtin']/div/div[4]/div/select</value>
      <webElementGuid>e88cebda-838b-47cd-93b4-a7a922d41dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Source'])[1]/following::select[1]</value>
      <webElementGuid>9de05a51-b737-4d49-a40a-ff48f3d9e18d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason for Status Change'])[1]/following::select[1]</value>
      <webElementGuid>1c745032-c772-4266-a089-02ec90fa97fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provider System Name'])[1]/preceding::select[1]</value>
      <webElementGuid>299a3d52-981f-4d9a-ada0-94bae4fa8b72</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Template'])[2]/preceding::select[2]</value>
      <webElementGuid>3733944d-d017-4f17-9d4b-459c695788f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>2f969ec5-a90c-4d18-b6cb-5b3a094d4f1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SgtinVersion[0].SerialNumberSourceId' and @name = 'SgtinVersion[0].SerialNumberSourceId' and (text() = 'Select Serial Number SourceInternally generatedEnterprise SNM SystemPartner SNM SystemImportedProvisioned by Packager' or . = 'Select Serial Number SourceInternally generatedEnterprise SNM SystemPartner SNM SystemImportedProvisioned by Packager')]</value>
      <webElementGuid>9dc22828-1f75-46ae-bde5-50f6e43555af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
