<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Serial Number Template</name>
   <tag></tag>
   <elementGuidId>20275a5b-66ca-4d43-9dfc-008e1c4c0da0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id, 'SerializationTemplateId')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>891cc1a1-bc4f-4cae-8242-8059ef6bcfa2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SgtinVersion[0].SerializationTemplateId</value>
      <webElementGuid>74712c89-f916-4e26-819b-b789e7e7410c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0</value>
      <webElementGuid>10d56bfb-2c3b-4b1a-bd7a-1306254774cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3a4f3f63-b52a-475a-9c96-6d4da9e20b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SerializationTemplateId field is required.</value>
      <webElementGuid>27964e73-74bc-4639-b9bf-013e9670f337</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SgtinVersion[0].SerializationTemplateId</value>
      <webElementGuid>675d9e4a-869a-442a-a556-21c4c30db172</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Serial Number TemplateRandom _ Numeric_435</value>
      <webElementGuid>fd0a0fa5-ae59-420a-b10d-c6ff9d3bb1b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SgtinVersion[0].SerializationTemplateId&quot;)</value>
      <webElementGuid>a67b7e91-3db3-436e-82c7-49cb6821a919</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SgtinVersion[0].SerializationTemplateId']</value>
      <webElementGuid>b6feab9e-7f97-414d-a369-5245abefdefb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Addsgtin']/div/div[5]/div/select</value>
      <webElementGuid>780fc119-8b21-498a-98e5-30b6c0f742ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='All active SSCC templates will appear in this dropdown'])[1]/following::select[1]</value>
      <webElementGuid>248edf09-52ba-41a6-9664-1c06b350f206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Template'])[2]/following::select[1]</value>
      <webElementGuid>2fdc4272-c7d1-46b5-881b-a39523dd9ffc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Owner Name'])[1]/preceding::select[1]</value>
      <webElementGuid>3cc07109-d572-469a-8d98-329e26e23cf1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Systems'])[1]/preceding::select[1]</value>
      <webElementGuid>c539882d-a1a7-4fab-8954-9666368f7554</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/select</value>
      <webElementGuid>5edf78e3-cabb-4ac7-a2ab-b37eba57967f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SgtinVersion[0].SerializationTemplateId' and @name = 'SgtinVersion[0].SerializationTemplateId' and (text() = 'Select Serial Number TemplateRandom _ Numeric_435' or . = 'Select Serial Number TemplateRandom _ Numeric_435')]</value>
      <webElementGuid>678fcd89-beab-47db-a02c-d8f9f6fad2e9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
