<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SSCC Profile Description</name>
   <tag></tag>
   <elementGuidId>6b380545-57bf-4098-8f39-cb645fa5d3a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id, 'DescriptionSSCC')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>df9a831a-24d5-45c0-8173-c1351a806b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0</value>
      <webElementGuid>0079e83c-c130-478a-991c-ec9c2698606d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SgtinVersion[0].DescriptionSSCC</value>
      <webElementGuid>1b75c7a1-49f2-403a-9529-dcdf5d31f685</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter SSCC Profile Description</value>
      <webElementGuid>5ec43142-d1d8-457a-b53d-6c1f1889ecb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>78116a25-d715-4a21-a5cc-ca0d66346488</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SgtinVersion[0].DescriptionSSCC</value>
      <webElementGuid>e49aebbe-8287-4bc4-8482-793c8aa73128</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>55968-2-2</value>
      <webElementGuid>2f4524bc-570b-4beb-bc8e-a60c599b9a98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SgtinVersion[0].DescriptionSSCC&quot;)</value>
      <webElementGuid>5541aa9d-4daa-4cd9-adad-041cc7b6a765</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SgtinVersion[0].DescriptionSSCC']</value>
      <webElementGuid>ced3ff9e-55a1-4786-8f9c-2a1b1d07abbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Addsgtin']/div/div[2]/div/input</value>
      <webElementGuid>51c48001-55ea-42f6-aeb0-06dd364ccb68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>2b849057-77ce-42b0-bb17-cf7dc0e6fd78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SgtinVersion[0].DescriptionSSCC' and @placeholder = 'Enter SSCC Profile Description' and @type = 'text' and @name = 'SgtinVersion[0].DescriptionSSCC']</value>
      <webElementGuid>d3e59b0a-0243-4501-9577-d1cdb932ffb8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
