<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manufacturer Name_Code</name>
   <tag></tag>
   <elementGuidId>f6994b82-4616-4b9a-918e-d09ebdc5109f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c319a419-c922-4049-be26-d022ee5d5889</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-input mt-1</value>
      <webElementGuid>37c65ac7-c2e0-4004-8564-aee608e75696</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>4bd1c57b-3b10-4234-ab15-e20c1100757a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>aad56bd7-2933-4741-83af-06b5db50c47a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductCodeList&quot;)/div[3]/div[@class=&quot;divTableBody&quot;]/div[@class=&quot;rowBorder divTableRow&quot;]/div[@class=&quot;divTableCell col-1 pr-0&quot;]/input[@class=&quot;radio-input mt-1&quot;]</value>
      <webElementGuid>9cdcc197-4858-4373-82a2-2bc433d175ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Code']</value>
      <webElementGuid>7664c5dd-8c2a-4451-b6af-d60da48a335e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProductCodeList']/div[3]/div/div/div/input</value>
      <webElementGuid>ddf57044-7ba7-474e-b30f-186a5b09d80d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/input</value>
      <webElementGuid>e3e7a6a9-5df1-4f05-a414-561a949c2146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Code']</value>
      <webElementGuid>4773565f-546a-492e-98ee-95b152206023</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
