<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Code Search</name>
   <tag></tag>
   <elementGuidId>94a7540b-4bd5-4f5f-8494-55a6dc9cce9a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='btn_SearchProducts']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_SearchProducts</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3c6ed881-487b-4004-959e-7126e74cc757</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_SearchProducts</value>
      <webElementGuid>b13b8995-d6a9-41a1-9a8d-e62b37b350e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/svg/quick_reference.svg</value>
      <webElementGuid>1275f598-8a6a-4211-a6da-5a0e56bc79b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>QuickSearch</value>
      <webElementGuid>788303fb-5807-4d5e-a1bb-2aa21774878f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>108c9630-253d-471b-a78d-90681746819c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#staticBackdrop</value>
      <webElementGuid>40d168ef-2eb2-4f6c-a4e9-e2455bb40672</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_SearchProducts&quot;)</value>
      <webElementGuid>e550be4d-3a07-4c2f-b053-2bd6929f4eca</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='btn_SearchProducts']</value>
      <webElementGuid>1ee610da-076a-4c2f-84b2-9d5a4225b3a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Sgtin-div']/div/div[2]/div/img</value>
      <webElementGuid>f21516ed-5dc0-4c09-b122-3e99d531c946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='QuickSearch']</value>
      <webElementGuid>05c69eab-96f2-48d8-a9e1-0ce83b5976c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/img</value>
      <webElementGuid>65288eac-798f-4c20-9d70-ac3887c1f951</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'btn_SearchProducts' and @src = '/images/svg/quick_reference.svg' and @alt = 'QuickSearch']</value>
      <webElementGuid>1daa30d1-ac5d-4675-b7c7-a2db48138511</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
