<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Code</name>
   <tag></tag>
   <elementGuidId>99f8e556-d823-420c-b4ed-a4f88adeff19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='productcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>085e8f0c-bada-4b5d-838b-be7e9a201464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productcode</value>
      <webElementGuid>11840761-26ac-438b-8cea-b62078e9424c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ms-em ml-0</value>
      <webElementGuid>7d70eaca-07a5-4fc4-b96f-ac3149148d0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type in Product Code</value>
      <webElementGuid>f58e9ab6-dfb6-4869-bd29-3b60abcc1fff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>showSuggestion()</value>
      <webElementGuid>caffe4ff-2930-4b5e-9a9f-406d4f6173fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideSuggesstion()</value>
      <webElementGuid>2fff4319-bce2-4b1f-9425-b192f17c832e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>df849a2c-8b52-43d3-86e8-97e37d045ecc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sgtin.ProductCode</value>
      <webElementGuid>1f60389a-9e62-4839-a2eb-bf6515eae0ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productcode&quot;)</value>
      <webElementGuid>8d0ba761-5e0b-4f71-a9c0-76a6b48b5b46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='productcode']</value>
      <webElementGuid>a6a7250d-7cf9-4396-8a06-9454cbfbc666</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Sgtin-div']/div/div[2]/div/input</value>
      <webElementGuid>73c8e244-e489-4b37-85d2-c2a0262b953e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/div[2]/div/input</value>
      <webElementGuid>95455efd-005d-4f90-95ef-3d7654d5acb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'productcode' and @placeholder = 'Type in Product Code' and @type = 'text' and @name = 'Sgtin.ProductCode']</value>
      <webElementGuid>de27e630-71ee-4b3a-a0b2-43831d7a8005</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
