<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Requesting Party</name>
   <tag></tag>
   <elementGuidId>1ad970c6-8250-4116-bed0-7530f2905a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'IdReqParty']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdReqParty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a28e4bce-0788-4340-b7fe-33f1c9a0129b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-4</value>
      <webElementGuid>487b32ae-f67b-413a-9c2d-d39760cc140b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdReqParty</value>
      <webElementGuid>d85bd2cf-9927-40f7-a9d2-4fb3131ed59c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>RequestingpartySgtin()</value>
      <webElementGuid>fdbeef09-4f5d-4bb1-94ee-e30abe740667</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>bc451a3b-b844-46f2-8e86-9078ec8e51e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RequestParty field is required.</value>
      <webElementGuid>eae5b026-d868-4121-b841-e36f25d01fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sgtin.RequestParty</value>
      <webElementGuid>c83e9362-f54c-453c-83b9-569e9a34c49a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Requesting PartyParty Automation 883</value>
      <webElementGuid>a9ec30c2-763a-4c4d-9a46-a907dcb2053e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdReqParty&quot;)</value>
      <webElementGuid>d0b886fb-5fdb-4764-ac44-7b0ed3cf3e61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdReqParty']</value>
      <webElementGuid>55975bd2-95d4-4dcb-b90a-8261f3fe3cea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_sgtin']/div[4]/div/select</value>
      <webElementGuid>1b988766-572d-4d01-b128-c4cb886fc9ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting Party'])[1]/following::select[1]</value>
      <webElementGuid>094a76f0-3c8b-4400-bcfe-326600cdf4e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGTIN Profile Version No.'])[1]/following::select[1]</value>
      <webElementGuid>89ce767e-9651-4e4f-aafb-96e7df20e882</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting System'])[1]/preceding::select[1]</value>
      <webElementGuid>afd76566-4954-4596-9b96-d694718af623</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGLN'])[1]/preceding::select[2]</value>
      <webElementGuid>e581b598-8779-4fcc-9359-7ec4ba3c531b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>d1453f73-b4d6-4f06-a76b-82b1fc0c7ba5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdReqParty' and @name = 'Sgtin.RequestParty' and (text() = 'Select Requesting PartyParty Automation 883' or . = 'Select Requesting PartyParty Automation 883')]</value>
      <webElementGuid>7251e052-8cc9-4747-97d9-53ab1c6ea03d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
