<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Requesting System</name>
   <tag></tag>
   <elementGuidId>ba73dd9e-9eca-4b15-a8d2-fa141b1df6ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id = 'IdRequestingSystem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdRequestingSystem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1284f6ad-e035-466d-8bcd-620bd36435dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms sgtinrequestingsysinput</value>
      <webElementGuid>4de7f7fe-4535-40fb-91ec-e1f4d2f62ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdRequestingSystem</value>
      <webElementGuid>354b91d6-6b6c-430b-8ba3-4028ca471e2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5bcd13b9-a07f-4109-af06-477c74952a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RequestingSystem field is required.</value>
      <webElementGuid>981228d6-0ff1-4ef3-882c-672ac9ee6b01</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sgtin.RequestingSystem</value>
      <webElementGuid>a151af59-5172-4d20-ae6a-ebd9ebfd280c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select SystemSystem Party Automation 883</value>
      <webElementGuid>cefe4d6e-03ec-4182-8a2c-f405d2affde4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdRequestingSystem&quot;)</value>
      <webElementGuid>07f2118b-8b10-4b18-98ec-66f5268fd53f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdRequestingSystem']</value>
      <webElementGuid>d19a68d8-0ecc-4313-8992-4b88b9e5c5c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IdsystemRequest']/select</value>
      <webElementGuid>3df34458-93a5-4f93-8bcd-d1ee264f4ce9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting System'])[1]/following::select[1]</value>
      <webElementGuid>8f658af7-fbcf-4e38-8a98-b57e053f1c5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting Party'])[1]/following::select[2]</value>
      <webElementGuid>0c8d4b85-1cdb-4b42-8e0e-7ad5f849c7c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGLN'])[1]/preceding::select[1]</value>
      <webElementGuid>109bc045-2f18-4d00-94a9-5354212eb32a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Mode'])[1]/preceding::select[1]</value>
      <webElementGuid>6f86a5a4-6765-4526-ab69-a4dec1ac1995</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>f62ee570-b00b-4dfd-bd3e-875c5c24b982</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdRequestingSystem' and @name = 'Sgtin.RequestingSystem' and (text() = 'Select SystemSystem Party Automation 883' or . = 'Select SystemSystem Party Automation 883')]</value>
      <webElementGuid>3667159a-0587-4994-af4f-81ddde8f8664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
