<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Manufacturer Name_divTableCell col-1 pr-0</name>
   <tag></tag>
   <elementGuidId>ca359e14-cc6f-4341-98bd-6ae4faee533c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='ProductCodeList']/div[3]/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.divTableCell.col-1.pr-0</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>eee8dd16-5e2a-422c-9dec-a7af92563752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>divTableCell col-1 pr-0</value>
      <webElementGuid>c2b2cdfe-89bd-4994-8bf9-a87a4cec9025</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductCodeList&quot;)/div[3]/div[@class=&quot;divTableBody&quot;]/div[@class=&quot;rowBorder divTableRow&quot;]/div[@class=&quot;divTableCell col-1 pr-0&quot;]</value>
      <webElementGuid>81655b73-93f8-43ed-9b46-7eb1f09a792b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProductCodeList']/div[3]/div/div/div</value>
      <webElementGuid>78c052aa-9cb3-4a65-99af-931f8b39396c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturer Name'])[1]/following::div[5]</value>
      <webElementGuid>fddb00f9-3ccb-4484-9261-7e58246afc9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Name'])[1]/following::div[7]</value>
      <webElementGuid>ce960545-cb59-4ff0-ae1a-5bb1f5279cd8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations 3'])[1]/preceding::div[2]</value>
      <webElementGuid>b4cfd031-e8af-4f67-b890-665789dd3ab1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buspirone Hcl'])[1]/preceding::div[3]</value>
      <webElementGuid>b61928a4-eb10-4691-81b9-2bf189b8914a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/div/div[3]/div/div/div</value>
      <webElementGuid>3de08ee0-1d45-4a62-965c-1de4a2a39683</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
