<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Manufacturer Name_Code</name>
   <tag></tag>
   <elementGuidId>956cb9af-24e2-46db-a0ee-4cc412aa8f01</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='Code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;Code&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>974e2cd0-1f07-4504-a54b-c948f4ea9108</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>radio-input mt-1</value>
      <webElementGuid>f9d0a62a-d9dc-4b72-84f7-6ccbd2eaeb48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>b8ca84fe-fe60-4a5a-8922-2c0714114a0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>1801c450-a70f-4fde-ba17-73cbd07d1fec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductCodeList&quot;)/div[3]/div[@class=&quot;divTableBody&quot;]/div[@class=&quot;rowBorder divTableRow&quot;]/div[@class=&quot;divTableCell col-1 pr-0&quot;]/input[@class=&quot;radio-input mt-1&quot;]</value>
      <webElementGuid>7085373b-5a59-4d31-8914-1578c2d7f98f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='Code']</value>
      <webElementGuid>99c63028-7511-40bc-bce6-efb9b1cc786f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProductCodeList']/div[3]/div/div/div/input</value>
      <webElementGuid>f5158472-2e5a-4504-a3f7-24e5c79e123e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/div/input</value>
      <webElementGuid>f296db5e-82da-4ba3-ad73-80bb0690de85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'Code']</value>
      <webElementGuid>dbb2024b-057e-46e0-aee6-d444c5d5bbca</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
