<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GCP GS1CompanyPrefix</name>
   <tag></tag>
   <elementGuidId>83574186-3c2b-483a-95ed-b36ba74e5212</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gs1-gcp</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gs1-gcp']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42d81f5b-e753-401d-9962-f1e22438d33a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-lg ml-2 input-validation-error input-validation-error</value>
      <webElementGuid>00d6e85a-270a-46ce-ad25-0f530aed5fa1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gs1-gcp</value>
      <webElementGuid>7ff467cf-a5be-4dad-9deb-7b71458e6157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>12</value>
      <webElementGuid>bdbd6994-6e4d-442d-a302-7c7737d69229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter GCP</value>
      <webElementGuid>22b7f228-33c4-4bfd-b33e-03c9105265aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^0-9]/g,&quot;&quot;)</value>
      <webElementGuid>ad0c31d7-144b-4295-9fe2-acdbba96a0d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearespanmsgs()</value>
      <webElementGuid>63ee602b-06ab-41d1-b6ac-1d7db8595c9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f0be0529-fd64-445b-8230-25196dc11e98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>GS1CompanyPrefix</value>
      <webElementGuid>63316e01-1027-4b72-ac28-b7e0a8acbcdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gs1-gcp&quot;)</value>
      <webElementGuid>922f4fdd-6806-4bb1-975b-0c606160319f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gs1-gcp']</value>
      <webElementGuid>ecfceb8e-f17b-482c-aa75-e02049293a1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GCP-model']/div/div/input</value>
      <webElementGuid>20df6b35-6142-4efe-a4ba-f12bcf22d4bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/input</value>
      <webElementGuid>679b8237-163c-4364-8073-a713d07090ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gs1-gcp' and @placeholder = 'Enter GCP' and @type = 'text' and @name = 'GS1CompanyPrefix']</value>
      <webElementGuid>607c767b-0695-47f4-a869-43a5d2ad0a12</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
