<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GCP Description</name>
   <tag></tag>
   <elementGuidId>a3a9883a-19df-41f3-8c38-ca5a3df38a80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gcp-Description</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gcp-Description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1d4366ca-49b1-454f-b00e-768845ddad38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-lg ml-2</value>
      <webElementGuid>da540fb1-1775-4476-87c2-c030c116faab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gcp-Description</value>
      <webElementGuid>36286a9a-d5c1-4b31-a02f-42dfa2a0596b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Description</value>
      <webElementGuid>50deb2ac-e990-4a66-806c-74bd87e35210</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b61be336-0043-4526-b26e-ce474951b506</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Description</value>
      <webElementGuid>d33cec56-7361-49bd-b6d6-30885f2b05be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gcp-Description&quot;)</value>
      <webElementGuid>2381f39b-bb69-4b3f-8c0a-a2da599ad0c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gcp-Description']</value>
      <webElementGuid>177c2cde-0078-4cb5-ba6f-b294f847d557</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GCP-model']/div/div[4]/div/input</value>
      <webElementGuid>a265007d-7c34-40fe-a818-36645959483d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div[4]/div/input</value>
      <webElementGuid>ccceb8da-c9b3-4fb1-af31-451f594fe1af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gcp-Description' and @placeholder = 'Enter Description' and @type = 'text' and @name = 'Description']</value>
      <webElementGuid>84a6132a-c763-4484-80c6-6ed194f61db9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
