<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusInactive</name>
   <tag></tag>
   <elementGuidId>747cfea7-a347-4f77-85df-4c024bed5b28</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#statusInActive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='statusInActive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>37d862fd-dc9d-4200-9024-c3dc1801453e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>0f69ab15-cf0f-4e68-91ce-68692e58df5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statusInActive</value>
      <webElementGuid>35704528-6df2-466c-9f07-37d79e4eb04f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>3a1857c1-d694-40a9-be06-83b92182971a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>3</value>
      <webElementGuid>a30e7c09-00c1-4687-b13b-66d3b037cb2e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StatusOption</value>
      <webElementGuid>1d442c0e-0ba0-475f-bbea-52fa5733e94f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gcptoggleReasonStatusChange(2)</value>
      <webElementGuid>075ac215-c513-458f-8c27-20dc26941547</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statusInActive&quot;)</value>
      <webElementGuid>0f179f13-78ab-4f32-b59f-167f3cd830f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='statusInActive']</value>
      <webElementGuid>cd184804-ff5a-4810-bbb2-2b1c165ffb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GCP-model']/div/div[2]/div[2]/input</value>
      <webElementGuid>db45a4eb-38fa-4213-83e7-83171e7c44e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]/div[2]/input</value>
      <webElementGuid>29c21142-66b8-4569-8ba2-dfdac1c81d1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'statusInActive' and @type = 'radio' and @name = 'StatusOption']</value>
      <webElementGuid>c836fcac-8034-4cee-bd05-72316d73b2cf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
