<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusActive</name>
   <tag></tag>
   <elementGuidId>6feb852d-4fbe-4785-bb78-61e1901157b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#statusActive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='statusActive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cab99fe2-cf97-4937-b752-4654bc2ff103</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>1c08f489-0182-4d3b-855a-0add86fe66d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>statusActive</value>
      <webElementGuid>fb032b2b-bdbc-4993-bf5b-ecc2a646e805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>1663fb71-1b7f-461c-95e4-69a66d3b3326</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>1b3c1e57-5c18-413f-9c22-6ad44f579444</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>StatusOption</value>
      <webElementGuid>be2bbbbc-f741-4ad7-aa48-a501af1b19cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>gcptoggleReasonStatusChange(1)</value>
      <webElementGuid>e30be4b1-705e-4e26-b165-38f05d01aeff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c4fe4812-65f0-48ea-9bef-a3d5fde1eba5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The StatusId field is required.</value>
      <webElementGuid>e9551b8d-9ccf-4865-bb38-52c397bd9faa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;statusActive&quot;)</value>
      <webElementGuid>3761158d-ea18-4bf6-b5e5-fc712bc8a6f0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='statusActive']</value>
      <webElementGuid>91e82a2f-a949-4771-87b0-188a7258f6fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='GCP-model']/div/div[2]/div/input</value>
      <webElementGuid>da8e1ce1-ac1d-45c7-aa6d-ecd75ae1b9f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/div/div[2]/div/input</value>
      <webElementGuid>e351ea91-6755-44ba-b7f1-cbf7e1d7d77c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'statusActive' and @type = 'radio' and @name = 'StatusOption']</value>
      <webElementGuid>553f3319-8b31-4792-b981-9db3c82a09a0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
