<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Code Search icon</name>
   <tag></tag>
   <elementGuidId>99aa834d-127f-481e-821b-65e38e67791d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[@id='btn_SearchProducts']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_SearchProducts</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>3f14a981-d090-4143-990a-c27e2d0bdf7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_SearchProducts</value>
      <webElementGuid>f68abd34-9a25-480d-8a25-ac93856a1414</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/svg/quick_reference.svg</value>
      <webElementGuid>2f59b397-c628-4697-a0cd-f3a9a58cff12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>QuickSearch</value>
      <webElementGuid>9d338e30-d196-41e4-9e3c-48f97644ddc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>26100272-1de0-4d9f-932f-952c18dd5699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#staticBackdrop</value>
      <webElementGuid>8afa108f-f79b-4364-a1aa-a5cc6f1601ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_SearchProducts&quot;)</value>
      <webElementGuid>d374c867-7abe-497e-af4f-25ce3e12e1e7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@id='btn_SearchProducts']</value>
      <webElementGuid>105343df-9d21-4029-99c3-f07ebc56c2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form_Profile']/div/div/div[2]/div/img</value>
      <webElementGuid>39d32947-71ff-4f4d-9cd8-80b1d93124b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='QuickSearch']</value>
      <webElementGuid>e4e151ad-908f-4d77-96ac-38b47bfb287e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div[2]/div/img</value>
      <webElementGuid>c593c8a4-8c22-4034-bbba-ace967612b4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@id = 'btn_SearchProducts' and @src = '/images/svg/quick_reference.svg' and @alt = 'QuickSearch']</value>
      <webElementGuid>081bad58-35f3-4716-aff6-ce84fc069d9d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
