<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Code Type</name>
   <tag></tag>
   <elementGuidId>467b11a4-28f6-4274-b78f-f4df045c57c1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='productcodetype']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productcodetype</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>9c80601f-01fb-4b22-b113-9e552b28cea4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms-em ml-0</value>
      <webElementGuid>88a8b85e-3f4b-4fa5-a19c-7211e6be67b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productcodetype</value>
      <webElementGuid>67cbc514-3c7b-4a7f-85f7-76e88cdce89d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f56f257-4231-4e51-9676-acf761333307</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProductCodeTypeId field is required.</value>
      <webElementGuid>2a52f4d4-0baf-4613-a54d-433ede40bd36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.ProductCodeTypeId</value>
      <webElementGuid>9e9b0808-caa9-4e2a-ba88-0c681a9489b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>GTIN-14GTIN-14</value>
      <webElementGuid>ee218978-4c7e-49ef-b537-ba89cbeb182a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productcodetype&quot;)</value>
      <webElementGuid>0f13dc4f-b4d6-403f-bfc9-cd5da918150c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='productcodetype']</value>
      <webElementGuid>d7499ade-112f-4867-a234-49470d323b5f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form_Profile']/div/div/div/select</value>
      <webElementGuid>4e43b131-3948-46db-8a93-11eac72ebc40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code Type'])[1]/following::select[1]</value>
      <webElementGuid>f32f0aaa-31ef-469f-a35b-0ca0d08a4a84</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[1]/following::select[1]</value>
      <webElementGuid>9b0378c0-66d8-4fa1-bf85-ab40c9fa22c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/preceding::select[1]</value>
      <webElementGuid>47bd9617-2cd9-4bb5-9828-1842c23cf07e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Description'])[1]/preceding::select[1]</value>
      <webElementGuid>797d91b7-e0a8-4c77-a1a6-226719655b02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>7ea59368-5f8d-4f1f-9430-312d7f6e5aa4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'productcodetype' and @name = 'BasicInfo.ProductCodeTypeId' and (text() = 'GTIN-14GTIN-14' or . = 'GTIN-14GTIN-14')]</value>
      <webElementGuid>90e36bb1-d115-411f-8838-67818475da9f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
