<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Serial Number Template</name>
   <tag></tag>
   <elementGuidId>fbca2e93-b443-4480-9f6c-9afa98aafa17</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'SerializationTemplateId')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>f5e66774-9539-47b6-a21b-8f150f1ff1b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SgtinVersion[0].SerializationTemplateId</value>
      <webElementGuid>1dfbbb44-b8ab-43a7-bd31-3bec982e4be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0 sgtininput-source</value>
      <webElementGuid>18f90339-0966-4451-9982-4e531a30661d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4a476370-2e76-4f7e-a914-28b22d34b3c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SerializationTemplateId field is required.</value>
      <webElementGuid>e8b0803d-9642-48cd-a538-f897e4debf23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.SerializationTemplateId</value>
      <webElementGuid>9e4e6165-7c25-4f56-868d-a6ac1e621ae3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>12_Random_Numeric_Packaging Level10_Random_Numeric_Packaging Level_847010_Random_Numeric_Packaging Level_8455</value>
      <webElementGuid>73a651fa-ec50-42ba-a860-323e6d23e13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SgtinVersion[0].SerializationTemplateId&quot;)</value>
      <webElementGuid>5a4d94e6-7e89-4f36-9f39-d66a65a57531</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SgtinVersion[0].SerializationTemplateId']</value>
      <webElementGuid>a84e1168-18a9-4730-8744-4e87c8250113</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Addsgtin']/div/div[3]/div/select</value>
      <webElementGuid>13d979a7-4683-4379-8cf6-0730ba70c490</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Template'])[2]/following::select[1]</value>
      <webElementGuid>3f7ae4b6-4267-45b9-bc97-fafd958b1351</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Owner Name'])[1]/preceding::select[1]</value>
      <webElementGuid>ada0b79f-4e05-49b4-8495-ddb5007ca672</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Systems'])[1]/preceding::select[1]</value>
      <webElementGuid>0bdf6d77-81b6-434c-8be2-25c9caf912fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>4d72f921-6611-46de-a3c4-d0a8176fa5b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SgtinVersion[0].SerializationTemplateId' and @name = 'item.SerializationTemplateId' and (text() = '12_Random_Numeric_Packaging Level10_Random_Numeric_Packaging Level_847010_Random_Numeric_Packaging Level_8455' or . = '12_Random_Numeric_Packaging Level10_Random_Numeric_Packaging Level_847010_Random_Numeric_Packaging Level_8455')]</value>
      <webElementGuid>31f4b014-ed0a-4fea-854a-c1757a5347e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
