<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Serial Number Source</name>
   <tag></tag>
   <elementGuidId>3157c855-eb43-48b6-9e8d-8a2a9eabbf27</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id, 'SerialNumberSourceId')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>eab10c45-e065-47ff-87e3-9f7d2f2553ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SgtinVersion[0].SerialNumberSourceId</value>
      <webElementGuid>6cbeca32-9533-4b71-a818-4db0642f950e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0 sgtininput-source</value>
      <webElementGuid>bf1b1bae-13ce-4b79-8cb4-a5f74f4a81dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>SNSourceChange(this)</value>
      <webElementGuid>3db172d8-e1db-4abc-bb5b-d1a060255a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>daa83032-287c-45bc-8335-84a588b87bcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SerialNumberSourceId field is required.</value>
      <webElementGuid>ffbc5c18-30c2-4669-8e92-d3e3ddf0bf50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.SerialNumberSourceId</value>
      <webElementGuid>ce2bd996-81d9-4d13-8409-38aa0db465bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Internally generatedEnterprise SNM SystemPartner SNM SystemImportedProvisioned by Packager</value>
      <webElementGuid>e0ef89ab-6d01-4020-aff8-fff6e7c67c02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SgtinVersion[0].SerialNumberSourceId&quot;)</value>
      <webElementGuid>dcb0c787-1c53-42b2-9906-fa0ed131b5db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SgtinVersion[0].SerialNumberSourceId']</value>
      <webElementGuid>4793c9c3-8a64-47af-bbbb-cc1f4c5d6181</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Addsgtin']/div/div[2]/div/select</value>
      <webElementGuid>c98ebc49-0426-4f08-b916-3d6bc14bea3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Source'])[1]/following::select[1]</value>
      <webElementGuid>c0821ffe-0186-4ac4-873f-2a957a374c9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/following::select[1]</value>
      <webElementGuid>bb59c6e8-ffce-433d-aa01-608f6785cbc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provider System Name'])[1]/preceding::select[1]</value>
      <webElementGuid>bf2b4e23-f58d-4007-b6fd-98bd0244fae2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Template'])[2]/preceding::select[2]</value>
      <webElementGuid>5d34f085-f314-472c-9931-ba65d8bffb54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>aec69024-5a85-45d4-9a5b-bbb76425ce6f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SgtinVersion[0].SerialNumberSourceId' and @name = 'item.SerialNumberSourceId' and (text() = 'Internally generatedEnterprise SNM SystemPartner SNM SystemImportedProvisioned by Packager' or . = 'Internally generatedEnterprise SNM SystemPartner SNM SystemImportedProvisioned by Packager')]</value>
      <webElementGuid>77c8ea3a-2d90-42a7-9437-ee7c5cb5cf67</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
