<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_Draft</name>
   <tag></tag>
   <elementGuidId>608d1f6c-ed67-47dd-a7c7-4e3b39f32ade</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//label[(text() = 'Draft' or . = 'Draft')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>label.form-check-label.input-label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>a165501b-36fb-4cc2-8669-8df0c37c1607</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>SgtinVersion[0].SnStatusId.Draft</value>
      <webElementGuid>5c71ab2a-f44c-477f-aa9c-454bf90fc3fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-label input-label</value>
      <webElementGuid>8a3a1089-339b-41c6-890c-0ff784c655e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Draft</value>
      <webElementGuid>10db83eb-23a6-49f1-af4b-7e2dc35509ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Div_Addsgtin&quot;)/div[@class=&quot;additionalsgtin&quot;]/div[@class=&quot;row mt-2 pt-2 pl-3&quot;]/div[@class=&quot;col-4&quot;]/div[@class=&quot;form-check form-check-inline&quot;]/label[@class=&quot;form-check-label input-label&quot;]</value>
      <webElementGuid>dc88a202-3394-4e4e-b76f-bc60e933ceeb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Addsgtin']/div/div/div/div/label</value>
      <webElementGuid>73d71d75-e5b7-43cc-afbb-e54d40536667</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::label[1]</value>
      <webElementGuid>a909fea1-7bee-4d53-9a5f-cfb06c36b6f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Version 1'])[1]/following::label[2]</value>
      <webElementGuid>1aa31460-c4fe-4906-b293-a63772e5fad0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[1]/preceding::label[1]</value>
      <webElementGuid>be7836cd-ffb3-4be3-8074-5c5cb8509f79</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/preceding::label[2]</value>
      <webElementGuid>404c5eb5-b445-48f3-b132-1f0f5e717055</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Draft']/parent::*</value>
      <webElementGuid>7416e1a0-da6f-4d3f-ab28-13e494357f82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]/div/div/div/div/label</value>
      <webElementGuid>95fa9fbb-cd98-4f56-9697-4db8126cf224</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = 'Draft' or . = 'Draft')]</value>
      <webElementGuid>2fad0681-6acc-4113-ad71-2e7f4bbc979d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
