<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Owner row_DO</name>
   <tag></tag>
   <elementGuidId>374c9bbf-8816-4bda-b013-21e82f3114fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//td[contains(text(), '${ProductOwner}')]&#xd;
</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.temprodown</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>td</value>
      <webElementGuid>a3f5390e-51f9-46e1-b329-0926db2bea24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>temprodown</value>
      <webElementGuid>2236e6de-fc8d-4629-8b5f-d4c80dc43e8b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>northstar</value>
      <webElementGuid>bf481b12-a00e-421e-afb5-835e229e2b93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ownerTable&quot;)/tbody[1]/tr[2]/td[@class=&quot;temprodown&quot;]</value>
      <webElementGuid>b9596ff3-6d52-4525-b292-0c13e7956c90</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ownerTable']/tbody/tr[2]/td[2]</value>
      <webElementGuid>033e4c71-40c2-42fd-af35-ab8e201db367</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Test 101'])[3]/following::td[6]</value>
      <webElementGuid>fb904cd8-a88b-481f-9ca0-0f3f76a5a3cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Action'])[1]/following::td[8]</value>
      <webElementGuid>7bb0dd66-930c-48b4-9b79-69ac776a2034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Default Override Confirmation'])[1]/preceding::td[6]</value>
      <webElementGuid>42d2a618-abfc-451f-aaaa-369b3a6df18a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to override the existing template?'])[1]/preceding::td[6]</value>
      <webElementGuid>c1b3dc9a-4339-4c56-9626-557c3489086c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[2]</value>
      <webElementGuid>90c7f9c2-e33f-49d0-9455-00e9b59645bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//td[(text() = 'northstar' or . = 'northstar')]</value>
      <webElementGuid>c3ed671e-0c8f-4a2b-84b0-ff48bc4e8292</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
