<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Template</name>
   <tag></tag>
   <elementGuidId>e6900ad3-6afa-4ff1-98f1-496a93ec7126</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>button[name=&quot;addtemplate&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@name='addtemplate']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e3b2cf21-de0b-47c7-bc46-aca386b7f0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>3df3bb16-ac82-499a-be95-693f24ad9bd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary mr-3 listtemplatebutton</value>
      <webElementGuid>aba26dde-5723-440a-92e5-ff6836e66bfc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>addtemplate</value>
      <webElementGuid>edd43882-52ab-48bc-b7f4-2076830dfbc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addtemplate()</value>
      <webElementGuid>a927203d-48c5-40ff-a743-cb0608f619de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Template</value>
      <webElementGuid>09c5a63c-2578-42dd-a738-e478f99c92a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;content-borders&quot;]/div[1]/div[@class=&quot;bg-white&quot;]/div[@class=&quot;row partylist-buttons&quot;]/div[@class=&quot;col-6 text-right font-size-twenty-px&quot;]/button[@class=&quot;btn btn-primary mr-3 listtemplatebutton&quot;]</value>
      <webElementGuid>f2c84a22-17d4-4349-b5a4-267b06d764ce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@name='addtemplate']</value>
      <webElementGuid>7b34a82d-7557-4410-8eec-b6d4ddfd01ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Export'])[1]/following::button[1]</value>
      <webElementGuid>4ea0bf67-c42b-4387-8b9a-73566741b6e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[1]/following::button[2]</value>
      <webElementGuid>3e981508-a3b2-4372-a79d-98eeccdbf44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Displaying 1 of 1 records'])[1]/preceding::button[1]</value>
      <webElementGuid>a3a1dbf3-8e60-435f-a9bc-709db4e1f6a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='First'])[1]/preceding::button[1]</value>
      <webElementGuid>7c3e8a09-11b8-4222-90f0-9432f63b4a2a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Template']/parent::*</value>
      <webElementGuid>4a66493b-9d0f-4995-9e67-786350d1f340</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>8753e8c3-0d50-4121-a8ef-459b84f41552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'addtemplate' and (text() = 'Add Template' or . = 'Add Template')]</value>
      <webElementGuid>603eeb85-6a5d-410f-baec-38a9d19636fe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
