<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveConfirmPop-up</name>
   <tag></tag>
   <elementGuidId>36b73a11-b763-470e-8d1b-b38a1a3e617a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-GetConfirmation > div.modal-dialog.modal-sl.modal-messageBox > div.modal-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[contains(@class,'GetVersionConfirmation')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>20a41c6a-5680-4526-bb36-aff47f12e648</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-content</value>
      <webElementGuid>198ce240-fb0c-4b05-b998-09acd8058512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> The Serial number source and Serial Number Template cannot be modified, after saving the serialization Profile.Do you want to continue?Cancel Confirm</value>
      <webElementGuid>b267cb54-dae0-4a59-889e-476804299449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-GetConfirmation&quot;)/div[@class=&quot;modal-dialog modal-sl modal-messageBox&quot;]/div[@class=&quot;modal-content&quot;]</value>
      <webElementGuid>77899529-0f90-444b-8342-a472a9cf73f4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-GetConfirmation']/div/div</value>
      <webElementGuid>9f4ea953-e158-499f-b7f0-0c71b6e69ddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[3]/following::div[3]</value>
      <webElementGuid>71abbacc-5275-458c-ad54-60397380de4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/following::div[11]</value>
      <webElementGuid>b30ee01d-a405-4b5c-b819-cc4553533b1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div</value>
      <webElementGuid>4ff48e1e-f420-40e1-85b9-b619cdaacb39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' The Serial number source and Serial Number Template cannot be modified, after saving the serialization Profile.Do you want to continue?Cancel Confirm' or . = ' The Serial number source and Serial Number Template cannot be modified, after saving the serialization Profile.Do you want to continue?Cancel Confirm')]</value>
      <webElementGuid>a7514423-a834-4de3-a0a2-014b9c92217d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
