<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PartyNameLink</name>
   <tag></tag>
   <elementGuidId>c7777c1d-31cc-49f8-bb5f-033e83703034</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner'])[5]/following::a[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = '${PartyName}' or . = '${PartyName}')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>11f69291-d357-4f73-8f45-ce78c80d03fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/Admin/Party/Edit?partylocationid=5&amp;editviewflg=true</value>
      <webElementGuid>564eeb7b-f2b0-411b-b7a9-e265090de0e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${PartyName}</value>
      <webElementGuid>b96c5a38-5646-4db3-9fbc-de62afc129c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;body-wrapper&quot;]/div[@class=&quot;w-100&quot;]/div[@class=&quot;content-borders&quot;]/div[1]/div[@class=&quot;bg-white&quot;]/div[@class=&quot;party-list-table&quot;]/div[@class=&quot;divTable&quot;]/div[@class=&quot;divTableBody&quot;]/div[@class=&quot;rowBorder  divTableRow&quot;]/div[@class=&quot;divTableCell col-4&quot;]/a[1]</value>
      <webElementGuid>04edde21-b5c9-4b60-9dc1-6feabcbd13af</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Partner'])[5]/following::a[1]</value>
      <webElementGuid>7b35c40b-a770-4c20-9212-d272a26a1175</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit'])[16]/following::a[1]</value>
      <webElementGuid>9f6952d1-0cdf-4364-bb8c-2c0d2aafd3e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/Admin/Party/Edit?partylocationid=5&amp;editviewflg=true')]</value>
      <webElementGuid>b791db7c-87f0-498c-9a30-edb3e56ac67f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[19]/div[4]/a</value>
      <webElementGuid>0e1b44e3-f3d2-41b0-9e4a-927dfabe4875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/Admin/Party/Edit?partylocationid=5&amp;editviewflg=true' and (text() = ' Party 1_Imported' or . = ' Party 1_Imported')]</value>
      <webElementGuid>24bf96e1-8105-4a9a-96a0-33435c942f62</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
