<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Range End</name>
   <tag></tag>
   <elementGuidId>10a28ed1-7986-4c6d-ab86-d3018cee100d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#RangeEnd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='RangeEnd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>58dbdc0f-4b8f-4ae4-ba26-e74aeb143e6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RangeEnd</value>
      <webElementGuid>72dc6c49-5a22-4473-954d-998892862d54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row textboxtemplate ml-3 pl-1 autodisplayBgcolor</value>
      <webElementGuid>a3ba71b3-7321-4379-8a2c-0529d38a8356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>system generated</value>
      <webElementGuid>aeac20f8-e08d-4a1f-9b6e-e04efd9facc4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d3728ac8-6cff-46e8-81e3-f57cde4fd9d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.SerialNumberTo</value>
      <webElementGuid>367edc18-737f-43f1-a689-ce2baf950776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RangeEnd&quot;)</value>
      <webElementGuid>63b260a9-a4a8-4446-b6d9-807ab88195a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='RangeEnd']</value>
      <webElementGuid>147b57d2-7244-4cc5-a03e-50c32b9f70ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rangesdiv']/div[2]/input</value>
      <webElementGuid>d5a0e6a7-30df-49ff-aea8-23fa72e8d58a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div[2]/input</value>
      <webElementGuid>e0df964d-db5c-4b34-8aab-6fca40cc59aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'RangeEnd' and @placeholder = 'system generated' and @type = 'text' and @name = 'TemplateDetails.SerialNumberTo']</value>
      <webElementGuid>ad086963-b448-4554-a172-bd2054a3278a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
