<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Reorder Quantity</name>
   <tag></tag>
   <elementGuidId>8da5aec8-77cf-44d4-a92d-0d9a94a3caee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReOrderQtyId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReOrderQtyId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bf695acb-760e-4570-8ed5-2332f69179c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReOrderQtyId</value>
      <webElementGuid>de3399a6-641a-4261-a6e5-1ffc6421421d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row textboxtemplate ml-2 pl-1</value>
      <webElementGuid>f099de4e-6e49-4775-a3af-5276bed28a45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Reorder Quantity</value>
      <webElementGuid>c094d54c-3e5d-4328-aed4-d56836e05254</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>b1d5c530-a6a0-43a4-b92c-ae5e3d8c8233</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ee1b766-b1cf-4e3c-9099-a43736fbadf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Reorder Quantity is required</value>
      <webElementGuid>fda3a574-1e4b-4f35-929c-a3a7d22ec71a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.ReOrderQty</value>
      <webElementGuid>82801f20-5fa6-4b1e-be0f-7150758b6133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>98f7a532-2a09-4fbd-a5ab-f92649b3850e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReOrderQtyId&quot;)</value>
      <webElementGuid>e90ec242-1180-41ab-8e65-d05af0b33383</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReOrderQtyId']</value>
      <webElementGuid>3ae8ca4b-3b34-46ca-9fc2-11174bf8fb2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[11]/div[2]/input</value>
      <webElementGuid>a617a866-7837-4670-92e2-e9ce94af23b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div[2]/input</value>
      <webElementGuid>173337c6-84a8-4738-92e1-e4f3d2a389d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReOrderQtyId' and @placeholder = 'Enter Reorder Quantity' and @type = 'number' and @name = 'TemplateDetails.ReOrderQty']</value>
      <webElementGuid>3a29bb1e-df52-4620-97e3-57c55cf6a016</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
