<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Replenish Threshold</name>
   <tag></tag>
   <elementGuidId>06160bcf-50ea-4c4e-8925-3f911d768a97</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ReplenishThresholdId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ReplenishThresholdId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8347124f-d2d8-4d82-bcc3-e255ed369c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ReplenishThresholdId</value>
      <webElementGuid>1a8af318-488f-4641-b067-cfd041eec945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row textboxtemplate pl-1</value>
      <webElementGuid>29746790-dbfc-4b71-8441-d23a6464baff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Replenish Threshold</value>
      <webElementGuid>31760f7b-e5c4-4ff6-bdd8-960908c0d0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>c056f592-22fc-430a-8e05-898453344386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1c21ac09-64d7-443e-b24b-56e8cc88459a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Replenish Threshold is required</value>
      <webElementGuid>cceb55e5-2d5e-4219-bdaf-a085fb71d0a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.ReplenishThreshold</value>
      <webElementGuid>585d20b1-17ac-4947-83cd-e3ac1cc74c2a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>669e93c3-a320-427c-b6ff-ebe212c5da79</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ReplenishThresholdId&quot;)</value>
      <webElementGuid>a9810a16-b6b0-4d55-a32b-b0146a9d0a73</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ReplenishThresholdId']</value>
      <webElementGuid>1fd44b33-999e-4bed-8b2d-9966c7c80cbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div[11]/div/input</value>
      <webElementGuid>ac414c52-21ba-4394-8ba7-65ea4317e036</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[11]/div/input</value>
      <webElementGuid>457be4b9-a635-4813-bc97-87063639af7d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ReplenishThresholdId' and @placeholder = 'Enter Replenish Threshold' and @type = 'number' and @name = 'TemplateDetails.ReplenishThreshold']</value>
      <webElementGuid>78f7d69b-8d3f-4f9e-bb5b-72f990fffe9b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
