<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Serial Number Template Name</name>
   <tag></tag>
   <elementGuidId>92b7bc07-4da9-4229-b252-e67b1353cf93</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#TempName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='TempName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7af89638-fe29-4322-9c5e-9263830ccc5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TempName</value>
      <webElementGuid>48bf3ff5-15af-422f-b74d-3eccadb19e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nametemplete</value>
      <webElementGuid>ba6d32e6-da0d-47f5-8745-6d6a3a152e93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ls</value>
      <webElementGuid>0235f5c8-bc48-4786-8da0-de41e4d4537d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Serial Number Template Name</value>
      <webElementGuid>a2644adb-fa8a-43f7-b2cf-253e74b6f1a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>templateNameRestriction()</value>
      <webElementGuid>48625a4b-e58a-48ed-87ce-065037f02f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>bb1dfe1d-d8e9-426d-bb26-f4ca3ad7584f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1da24889-2fbc-4f3c-ab58-9dd06681c53f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Serial Number Template Name is required</value>
      <webElementGuid>246a0226-9637-4099-ade6-0e1bf82091dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TempName&quot;)</value>
      <webElementGuid>840af6df-5615-494a-b7a1-041b2293ee3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='TempName']</value>
      <webElementGuid>0f3b93c4-a823-43be-b9b1-6c0a76df12c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Templatename']/div/input</value>
      <webElementGuid>5ef180f4-1fa7-4dd6-b168-44c9b8c86cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/input</value>
      <webElementGuid>a3e01640-76ba-4740-bce0-46cd8b2e60fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'TempName' and @name = 'nametemplete' and @placeholder = 'Enter Serial Number Template Name' and @type = 'text']</value>
      <webElementGuid>fb10afa2-241e-49a9-941a-c0afbfc79305</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
