<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Uniqueness</name>
   <tag></tag>
   <elementGuidId>69713cf9-5a14-47eb-ae2f-00130470bde9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Uniqueness</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Uniqueness']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fdf90fb5-6909-42e1-adc8-dc4cb27cbc23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Uniqueness</value>
      <webElementGuid>959345e2-6d92-4307-af7c-833f20d903da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>0c7d0b79-fb52-4b06-953b-e0dc6efd8651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>templateNameSystemgenerated()</value>
      <webElementGuid>96232429-047a-456f-8004-6d6a399b4412</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2a0b5e11-3f7e-4ead-9efe-eada6dc68480</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The UniquenessTypeId field is required.</value>
      <webElementGuid>842ab07b-14df-41ba-a890-046293bac0a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>TemplateDetails.UniquenessTypeId</value>
      <webElementGuid>6c41e272-4a5a-41bd-9231-c46c803241ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SelectTarget CountryEnterprisePackaging LevelProduct</value>
      <webElementGuid>a9582ddd-2259-4c23-9bd3-bb626d10da2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Uniqueness&quot;)</value>
      <webElementGuid>2562aa06-7c02-432c-b1f5-3b887705c8f9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Uniqueness']</value>
      <webElementGuid>6a1b09bd-dab2-42b7-8610-13ce6d57f3f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='divUniqueness']/select</value>
      <webElementGuid>5ad0ac33-ee56-42df-8214-6acffa8e9636</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Uniqueness'])[1]/following::select[1]</value>
      <webElementGuid>09925d88-aed4-4c9f-a46a-50abe00481df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sparseness Factor'])[1]/following::select[2]</value>
      <webElementGuid>a2c34b08-393f-47fa-b8ca-cf22230b2d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Template Name'])[2]/preceding::select[1]</value>
      <webElementGuid>0f4827e8-faf2-45a6-9f14-d62e0c068ed0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Range Start'])[1]/preceding::select[1]</value>
      <webElementGuid>b3ff32d1-f5fd-475a-93cf-93d280185407</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div[2]/select</value>
      <webElementGuid>afeab867-4a4b-4e36-ad88-4f3af6cd957c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Uniqueness' and @name = 'TemplateDetails.UniquenessTypeId' and (text() = 'SelectTarget CountryEnterprisePackaging LevelProduct' or . = 'SelectTarget CountryEnterprisePackaging LevelProduct')]</value>
      <webElementGuid>83fa601e-8930-4a68-a662-668ce9bc4550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
