<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GCP</name>
   <tag></tag>
   <elementGuidId>1bd27bfd-ed7b-4c12-87ed-67d7363a73e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='gcp']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gcp</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e38dd7a0-6afa-4238-9665-04d5d82e292c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gcp</value>
      <webElementGuid>c9ba223a-7ec1-4feb-ba9c-c80c7fd4d17b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchby-fields</value>
      <webElementGuid>82d75f30-2143-473d-ba03-1e441530f0c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter GCP</value>
      <webElementGuid>8489b0ac-1a56-49e3-9ebc-55f3cc2d13d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gcp&quot;)</value>
      <webElementGuid>50955eee-9368-4b86-aca7-3ab6f5c41228</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='gcp']</value>
      <webElementGuid>271a168d-8460-4a67-9b46-0fc983014c2b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbyfilter']/div/div[3]/input</value>
      <webElementGuid>3472bc39-2b6d-47bd-ac6d-2fec538442b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div[3]/input</value>
      <webElementGuid>5a51ee4a-49b5-428e-9c01-94013a52c5be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'gcp' and @placeholder = 'Enter GCP']</value>
      <webElementGuid>a513f862-f0e7-4f96-acc8-cb8c3b956be5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
