<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Identifier Value</name>
   <tag></tag>
   <elementGuidId>a9e94127-4f5d-4f3f-8f45-7b45160009a0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='identifier-value']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#identifier-value</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f62f3d02-0c48-4caf-9f43-76814ec37753</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>identifier-value</value>
      <webElementGuid>80a3a397-6df9-443d-867e-8b6842ec2f75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchby-fields identifier-value-field</value>
      <webElementGuid>9234c6bd-9d46-4ac1-8789-b3fbef97a11e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Identifier Value</value>
      <webElementGuid>2f9ce4c1-681a-4e96-9698-b03e6f8a5379</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;identifier-value&quot;)</value>
      <webElementGuid>2270b2a2-6499-4c81-97c6-d9440de017fb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='identifier-value']</value>
      <webElementGuid>b530382d-b483-4b1c-bf70-ee39336b9a51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbyfilter']/div[2]/div[4]/input</value>
      <webElementGuid>8e67109d-8c50-4dc8-aa0a-19231e9dd301</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>94b487cb-76f3-42cc-a9c8-4d394d8b4aa6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'identifier-value' and @placeholder = 'Enter Identifier Value']</value>
      <webElementGuid>91999142-8405-4481-89af-be74555fcc81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
