<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Packaging Levels</name>
   <tag></tag>
   <elementGuidId>1377c6ff-c2e9-4f87-913d-f69213f1fd80</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_packagingLevel</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_packagingLevel']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>bec8f7e0-9118-4a13-95e8-37472b687cc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_packagingLevel</value>
      <webElementGuid>94f03b9a-4d3c-4ddf-b3e8-163f15e80b98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab tab-inactive</value>
      <webElementGuid>1f689b36-b5fd-49ee-af99-9b7f1e6f33d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Packaging Levels  </value>
      <webElementGuid>595624d1-eb0f-4aae-a95b-4c55c08a14ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_packagingLevel&quot;)</value>
      <webElementGuid>bc300acb-9c9c-4f49-a430-fc7f6d306282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_packagingLevel']</value>
      <webElementGuid>e623cc9e-22f2-4954-9f65-0bb0570d0b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Details'])[1]/following::button[1]</value>
      <webElementGuid>6f7a29fd-115c-4817-a84b-2e2d0f4af9f7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[2]/following::button[2]</value>
      <webElementGuid>2669ff31-5a6f-4d8d-809c-be87a7e77cbc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Audit Trail'])[1]/preceding::button[1]</value>
      <webElementGuid>b96b479d-392c-46eb-90da-a7a99155f2ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Import'])[1]/preceding::button[2]</value>
      <webElementGuid>a8b9d14c-90ce-445b-8ec0-87e5010c59f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Packaging Levels']/parent::*</value>
      <webElementGuid>d84053e5-9feb-4b02-8b5e-5edb62fff940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button[2]</value>
      <webElementGuid>32713d34-c71d-403b-b8e7-01088c276447</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_packagingLevel' and (text() = ' Packaging Levels  ' or . = ' Packaging Levels  ')]</value>
      <webElementGuid>c0301cbb-c46f-4837-92ca-5a8332611c1c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
