<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add Identifier</name>
   <tag></tag>
   <elementGuidId>72348e8d-cf1a-4725-a44d-f3743497d974</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_AddIdentifier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_AddIdentifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>79c5fcc4-3867-4d71-8b2b-32578d4ae89f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_AddIdentifier</value>
      <webElementGuid>27276ba7-c2dc-4bbb-af88-8a96fe56d1f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f326a035-e2a2-43cc-a315-f1b1b7ed2c45</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-trading prd-addIdentifier</value>
      <webElementGuid>92fc14ac-c54d-421f-9539-af40cb63067e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>9956db98-bfd1-48fb-9f0f-36963c1da8b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#staticBackdrop</value>
      <webElementGuid>53f53059-8957-47d2-9794-d3ffdb481275</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Add Identifier </value>
      <webElementGuid>79da008e-efb1-444f-aa49-265bd1fa6ebc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_AddIdentifier&quot;)</value>
      <webElementGuid>a59e1ec1-aab6-4cee-96a7-e9e6374d8802</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_AddIdentifier']</value>
      <webElementGuid>892d4387-2517-4a5b-892c-f19998ae259d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductDetail']/div/div/div/div[6]/div/div/button</value>
      <webElementGuid>db54af3c-c75a-4265-abaa-8d3e5637b12e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Identifiers'])[1]/following::button[1]</value>
      <webElementGuid>40baa9e1-27f2-4fa9-8b2a-b241543bc40c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Commercial Status'])[1]/following::button[1]</value>
      <webElementGuid>9edf3194-8623-4943-89d1-c983cf37792a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product ID Type'])[1]/preceding::button[1]</value>
      <webElementGuid>351b1b10-9019-45f2-99ed-20c92d9d0c20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Identifier'])[1]/preceding::button[1]</value>
      <webElementGuid>7b446477-5085-4645-a4e6-b325b3d13c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Identifier']/parent::*</value>
      <webElementGuid>823173e2-02e8-46d3-95a8-856f5fa1525e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/div/button</value>
      <webElementGuid>ea924905-b4c7-4991-a360-89db50afb7b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_AddIdentifier' and @type = 'button' and (text() = ' Add Identifier ' or . = ' Add Identifier ')]</value>
      <webElementGuid>0842e9a4-e2ec-44d8-9b11-85d6e06617d3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
