<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Add</name>
   <tag></tag>
   <elementGuidId>02178262-4224-42d5-83b0-d33e691488c9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_Submit_AddIdentifier</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_Submit_AddIdentifier']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c80cd75d-c80d-4e6d-8b22-b44800d9996e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Submit_AddIdentifier</value>
      <webElementGuid>8ebc7320-9247-44d7-a760-654eb3d78705</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>720d255c-58b2-4431-a550-f8851130329d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save mt-3</value>
      <webElementGuid>48dae5f6-badb-4de3-8c57-56d0d40d265b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add</value>
      <webElementGuid>627c38e2-b91a-45f6-b55d-35c428787278</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Submit_AddIdentifier&quot;)</value>
      <webElementGuid>2d6377cc-d786-4a25-93d1-eac44ba31313</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_Submit_AddIdentifier']</value>
      <webElementGuid>40d7d9ae-959d-4193-b59a-896a416d5a58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-AddIdentifier']/div/div/div[3]/button[2]</value>
      <webElementGuid>507bde99-df50-4c66-aab7-c5ef52b10d18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[6]/following::button[1]</value>
      <webElementGuid>4de3a1f2-608a-4fea-ae66-9a0594b43092</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[2]/following::button[2]</value>
      <webElementGuid>3dc3c23c-a075-4235-8946-422f19cb43bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel Confirmation'])[2]/preceding::button[1]</value>
      <webElementGuid>112689a3-8539-421d-829a-5699bde6402c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Are you sure you want to discard changes?'])[2]/preceding::button[2]</value>
      <webElementGuid>60d15bf1-7d8c-4b1b-961f-c4c67d8ca663</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[3]/div/div/div/div[3]/button[2]</value>
      <webElementGuid>1fd9c96c-7f7f-4eff-924f-3ba2218f2dac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_Submit_AddIdentifier' and @type = 'button' and (text() = 'Add' or . = 'Add')]</value>
      <webElementGuid>667c2318-ef59-459e-a03c-61b3bde23ad3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
