<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Commercial Status</name>
   <tag></tag>
   <elementGuidId>b8b84981-a044-438c-80f6-4331df8306e8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductCommercialStatusId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ProductCommercialStatusId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>32249d73-a1c0-4eca-be29-558ecd690a0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ss input-Commercial</value>
      <webElementGuid>9c9a3b1d-ce77-4c65-8757-e09df81a83b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ef107214-3e76-4992-b02d-87d8beccf2fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProductCommercialStatusId field is required.</value>
      <webElementGuid>ec846113-05eb-48b4-acef-40e0b4fdbc82</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductCommercialStatusId</value>
      <webElementGuid>674fd412-dc26-490d-9933-24b221262b20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductCommercialStatusId</value>
      <webElementGuid>28bc9bfe-84b6-4944-b074-f6d39b446237</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Commercial StatusAlternate items availableIn MarketItems no longer stockedPhase outWithdrawn</value>
      <webElementGuid>f0aae13f-b074-4489-89a9-d8515097d886</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductCommercialStatusId&quot;)</value>
      <webElementGuid>fc2c0905-7ef3-4d46-9f99-a14cae6020c7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ProductCommercialStatusId']</value>
      <webElementGuid>e9618eee-54d6-4d71-9613-8e5a11ae4ebd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductDetail']/div/div/div/div[5]/div[2]/div/div[2]/select</value>
      <webElementGuid>ee8fb94c-ba93-4d5b-b8fd-56b7822859c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Commercial Status'])[1]/following::select[1]</value>
      <webElementGuid>7d88bb9c-f5af-4bfe-a805-08c97515aa96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ZW - Zimbabwe'])[2]/following::select[1]</value>
      <webElementGuid>1741dae9-c35c-4899-9e57-591522a2260c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Identifiers'])[1]/preceding::select[1]</value>
      <webElementGuid>ef62c1c3-59bc-4eb7-a14f-b841bc2489bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Identifier'])[1]/preceding::select[1]</value>
      <webElementGuid>e14bdd8f-4337-484d-9c2d-23bb8cb8d234</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>b8025fcb-5140-419f-b497-cc8da591bcc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ProductCommercialStatusId' and @name = 'ProductCommercialStatusId' and (text() = 'Select Commercial StatusAlternate items availableIn MarketItems no longer stockedPhase outWithdrawn' or . = 'Select Commercial StatusAlternate items availableIn MarketItems no longer stockedPhase outWithdrawn')]</value>
      <webElementGuid>a3a1ab63-e4a1-4f08-9ab7-40713340f326</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
