<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Companys Role</name>
   <tag></tag>
   <elementGuidId>f6044a01-595e-427c-a5bc-21f70f0da4a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#OwnerPartyRoleId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OwnerPartyRoleId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>309bc185-4df6-45f8-b600-6de4853b059a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>ccff299d-ab70-4c19-ab86-3da03f35a6ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>roleChange(this)</value>
      <webElementGuid>52cd0361-195c-4c3a-bfc2-3c67508e946a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>52d59fc6-991d-4c8f-b1fa-9db552d332ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The OwnerPartyRoleId field is required.</value>
      <webElementGuid>2397eb47-1a8a-436a-b3a3-f8e960177a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OwnerPartyRoleId</value>
      <webElementGuid>4dd51596-9e29-4f90-a93f-773357868da8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OwnerPartyRoleId</value>
      <webElementGuid>50a3284e-dcfb-4391-95cc-ca93062c55ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Company's Role3PLCMOContract PackagerDispenserExclusive DistributorImporterManufacurerParallel DistributorRepackagerVirtual CMOWholesaler</value>
      <webElementGuid>fa85fe6b-b7b7-42db-99b0-334f8cf0203f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OwnerPartyRoleId&quot;)</value>
      <webElementGuid>87d3dea7-d3c0-488e-87b0-81df9fbb3773</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OwnerPartyRoleId']</value>
      <webElementGuid>ec9fd2f0-55a1-4f6b-9eaa-965825f2db25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductDetail']/div/div/div/div[2]/div/select</value>
      <webElementGuid>3e0c48b9-9006-4c63-a30c-bd88a9a36488</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Company’s Supply Chain Role'])[1]/following::select[1]</value>
      <webElementGuid>663157cd-ab8e-4aa4-b96b-1fd456fd1cb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ProductId'])[1]/following::select[1]</value>
      <webElementGuid>1ec73a93-b8f0-4a39-ba71-c8b3a84168c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>958758d5-f176-4ec7-8f46-c7e7ef1364cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft'])[1]/preceding::select[1]</value>
      <webElementGuid>f5f6b3b3-3226-41b4-a2d2-ccb493e11513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select</value>
      <webElementGuid>54be82aa-e99c-4460-806b-b46b27e35a26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OwnerPartyRoleId' and @name = 'OwnerPartyRoleId' and (text() = concat(&quot;Select Company&quot; , &quot;'&quot; , &quot;s Role3PLCMOContract PackagerDispenserExclusive DistributorImporterManufacurerParallel DistributorRepackagerVirtual CMOWholesaler&quot;) or . = concat(&quot;Select Company&quot; , &quot;'&quot; , &quot;s Role3PLCMOContract PackagerDispenserExclusive DistributorImporterManufacurerParallel DistributorRepackagerVirtual CMOWholesaler&quot;))]</value>
      <webElementGuid>cb16c533-f94f-4185-8ce2-855df256aa0f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
