<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Country</name>
   <tag></tag>
   <elementGuidId>3258c48b-05e2-491f-8367-dab338c532c5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#CountryId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='CountryId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e407aede-8237-4962-9b40-67779035bf26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-lg</value>
      <webElementGuid>b7892631-8f69-45bf-93f1-fc01e2775b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>CountryId</value>
      <webElementGuid>7da0389f-a70d-49ae-820b-fa1c33e8162c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>efb2bacf-991f-4bca-aa2b-8c6713014701</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The CountryId field is required.</value>
      <webElementGuid>c1430bc1-2ef8-457e-a1d0-a77eb7c69a4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>CountryId</value>
      <webElementGuid>daeb2458-b5aa-4f3f-b628-8e4370cbf514</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select CountryAD - AndorraAE - United Arab EmiratesAF - AfghanistanAG - Antigua and BarbudaAI - AnguillaAL - AlbaniaAM - ArmeniaAO - AngolaAQ - AntarcticaAR - ArgentinaAS - American SamoaAT - AustriaAU - AustraliaAW - ArubaAX - Åland IslandsAZ - AzerbaijanBA - Bosnia and HerzegovinaBB - BarbadosBD - BangladeshBE - BelgiumBF - Burkina FasoBG - BulgariaBH - BahrainBI - BurundiBJ - BeninBL - Saint BarthélemyBM - BermudaBN - Brunei DarussalamBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBR - BrazilBS - BahamasBT - BhutanBV - Bouvet IslandBW - BotswanaBY - BelarusBZ - BelizeCA - CanadaCC - Cocos (Keeling) IslandsCD - Congo (Democratic Republic of the)CF - Central African RepublicCG - CongoCH - SwitzerlandCI - Côte d'IvoireCK - Cook IslandsCL - ChileCM - CameroonCN - ChinaCO - ColombiaCR - Costa RicaCU - CubaCV - Cabo VerdeCW - CuraçaoCX - Christmas IslandCY - CyprusCZ - CzechiaDE - GermanyDJ - DjiboutiDK - DenmarkDM - DominicaDO - Dominican RepublicDZ - AlgeriaEC - EcuadorEE - EstoniaEG - EgyptEH - Western SaharaER - EritreaES - SpainET - EthiopiaFI - FinlandFJ - FijiFK - Falkland Islands (Malvinas)FM - Micronesia (Federated States of)FO - Faroe IslandsFR - FranceGA - GabonGB - United Kingdom of Great Britain and Northern IrelandGD - GrenadaGE - GeorgiaGF - French GuianaGG - GuernseyGH - GhanaGI - GibraltarGL - GreenlandGM - GambiaGN - GuineaGP - GuadeloupeGQ - Equatorial GuineaGR - GreeceGS - South Georgia and the South Sandwich IslandsGT - GuatemalaGU - GuamGW - Guinea-BissauGY - GuyanaHK - Hong KongHM - Heard Island and McDonald IslandsHN - HondurasHR - CroatiaHT - HaitiHU - HungaryID - IndonesiaIE - IrelandIL - IsraelIM - Isle of ManIN - IndiaIO - British Indian Ocean TerritoryIQ - IraqIR - Iran (Islamic Republic of)IS - IcelandIT - ItalyJE - JerseyJM - JamaicaJO - JordanJP - JapanKE - KenyaKG - KyrgyzstanKH - CambodiaKI - KiribatiKM - ComorosKN - Saint Kitts and NevisKP - Korea (Democratic People's Republic of)KR - Korea (Republic of)KW - KuwaitKY - Cayman IslandsKZ - KazakhstanLA - Lao People's Democratic RepublicLB - LebanonLC - Saint LuciaLI - LiechtensteinLK - Sri LankaLR - LiberiaLS - LesothoLT - LithuaniaLU - LuxembourgLV - LatviaLY - LibyaMA - MoroccoMC - MonacoMD - Moldova (Republic of)ME - MontenegroMF - Saint Martin (French part)MG - MadagascarMH - Marshall IslandsMK - North MacedoniaML - MaliMM - MyanmarMN - MongoliaMO - MacaoMP - Northern Mariana IslandsMQ - MartiniqueMR - MauritaniaMS - MontserratMT - MaltaMU - MauritiusMV - MaldivesMW - MalawiMX - MexicoMY - MalaysiaMZ - MozambiqueNA - NamibiaNC - New CaledoniaNE - NigerNF - Norfolk IslandNG - NigeriaNI - NicaraguaNL - NetherlandsNO - NorwayNP - NepalNR - NauruNU - NiueNZ - New ZealandOM - OmanPA - PanamaPE - PeruPF - French PolynesiaPG - Papua New GuineaPH - PhilippinesPK - PakistanPL - PolandPM - Saint Pierre and MiquelonPN - PitcairnPR - Puerto RicoPS - Palestine, State ofPT - PortugalPW - PalauPY - ParaguayQA - QatarRE - RéunionRO - RomaniaRS - SerbiaRU - Russian FederationRW - RwandaSA - Saudi ArabiaSB - Solomon IslandsSC - SeychellesSD - SudanSE - SwedenSG - SingaporeSH - Saint Helena, Ascension and Tristan da CunhaSI - SloveniaSJ - Svalbard and Jan MayenSK - SlovakiaSL - Sierra LeoneSN - SenegalSO - SomaliaSP - San MarinoSR - SurinameSS - South SudanST - Sao Tome and PrincipeSV - El SalvadorSX - Sint Maarten (Dutch part)SY - Syrian Arab RepublicSZ - EswatiniTC - Turks and Caicos IslandsTD - ChadTF - French Southern TerritoriesTG - TogoTH - ThailandTJ - TajikistanTK - TokelauTL - Timor-LesteTM - TurkmenistanTN - TunisiaTO - TongaTR - TurkeyTT - Trinidad and TobagoTV - TuvaluTW - Taiwan, Province of ChinaTZ - Tanzania, United Republic ofUA - UkraineUG - UgandaUM - United States Minor Outlying IslandsUS - United States of AmericaUY - UruguayUZ - UzbekistanVA - Holy SeeVC - Saint Vincent and the GrenadinesVE - Venezuela (Bolivarian Republic of)VG - Virgin Islands (British)VI - Virgin Islands (U.S.)VN - VietnamVU - VanuatuWF - Wallis and FutunaWS - SamoaYE - YemenYT - MayotteZA - South AfricaZM - ZambiaZW - Zimbabwe</value>
      <webElementGuid>61deb9af-0889-426b-9bd4-d2f975bd4688</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;CountryId&quot;)</value>
      <webElementGuid>ad2fef91-a608-4c5e-a688-754f94d9375c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='CountryId']</value>
      <webElementGuid>d4cd0db4-f963-43c2-a7d3-cdbff562f25e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddIdentifier']/div/div[3]/div/select</value>
      <webElementGuid>f9aabac7-98cd-4243-93a0-43cb61b4e70d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[2]/following::select[1]</value>
      <webElementGuid>5cae585a-7b9c-4b44-ab4c-c9e2486091e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Identifier'])[3]/following::select[1]</value>
      <webElementGuid>3b5868ba-2afa-44fc-a613-204fe53ad518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[6]/preceding::select[1]</value>
      <webElementGuid>2fc6d12d-9698-4e2a-8a69-0a86aa64a9cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add'])[2]/preceding::select[1]</value>
      <webElementGuid>40c42b49-1090-4aca-9b59-f87a7af75021</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/select</value>
      <webElementGuid>e390a87d-8178-4587-93bc-f923fc89ec61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'CountryId' and @name = 'CountryId' and (text() = concat(&quot;Select CountryAD - AndorraAE - United Arab EmiratesAF - AfghanistanAG - Antigua and BarbudaAI - AnguillaAL - AlbaniaAM - ArmeniaAO - AngolaAQ - AntarcticaAR - ArgentinaAS - American SamoaAT - AustriaAU - AustraliaAW - ArubaAX - Åland IslandsAZ - AzerbaijanBA - Bosnia and HerzegovinaBB - BarbadosBD - BangladeshBE - BelgiumBF - Burkina FasoBG - BulgariaBH - BahrainBI - BurundiBJ - BeninBL - Saint BarthélemyBM - BermudaBN - Brunei DarussalamBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBR - BrazilBS - BahamasBT - BhutanBV - Bouvet IslandBW - BotswanaBY - BelarusBZ - BelizeCA - CanadaCC - Cocos (Keeling) IslandsCD - Congo (Democratic Republic of the)CF - Central African RepublicCG - CongoCH - SwitzerlandCI - Côte d&quot; , &quot;'&quot; , &quot;IvoireCK - Cook IslandsCL - ChileCM - CameroonCN - ChinaCO - ColombiaCR - Costa RicaCU - CubaCV - Cabo VerdeCW - CuraçaoCX - Christmas IslandCY - CyprusCZ - CzechiaDE - GermanyDJ - DjiboutiDK - DenmarkDM - DominicaDO - Dominican RepublicDZ - AlgeriaEC - EcuadorEE - EstoniaEG - EgyptEH - Western SaharaER - EritreaES - SpainET - EthiopiaFI - FinlandFJ - FijiFK - Falkland Islands (Malvinas)FM - Micronesia (Federated States of)FO - Faroe IslandsFR - FranceGA - GabonGB - United Kingdom of Great Britain and Northern IrelandGD - GrenadaGE - GeorgiaGF - French GuianaGG - GuernseyGH - GhanaGI - GibraltarGL - GreenlandGM - GambiaGN - GuineaGP - GuadeloupeGQ - Equatorial GuineaGR - GreeceGS - South Georgia and the South Sandwich IslandsGT - GuatemalaGU - GuamGW - Guinea-BissauGY - GuyanaHK - Hong KongHM - Heard Island and McDonald IslandsHN - HondurasHR - CroatiaHT - HaitiHU - HungaryID - IndonesiaIE - IrelandIL - IsraelIM - Isle of ManIN - IndiaIO - British Indian Ocean TerritoryIQ - IraqIR - Iran (Islamic Republic of)IS - IcelandIT - ItalyJE - JerseyJM - JamaicaJO - JordanJP - JapanKE - KenyaKG - KyrgyzstanKH - CambodiaKI - KiribatiKM - ComorosKN - Saint Kitts and NevisKP - Korea (Democratic People&quot; , &quot;'&quot; , &quot;s Republic of)KR - Korea (Republic of)KW - KuwaitKY - Cayman IslandsKZ - KazakhstanLA - Lao People&quot; , &quot;'&quot; , &quot;s Democratic RepublicLB - LebanonLC - Saint LuciaLI - LiechtensteinLK - Sri LankaLR - LiberiaLS - LesothoLT - LithuaniaLU - LuxembourgLV - LatviaLY - LibyaMA - MoroccoMC - MonacoMD - Moldova (Republic of)ME - MontenegroMF - Saint Martin (French part)MG - MadagascarMH - Marshall IslandsMK - North MacedoniaML - MaliMM - MyanmarMN - MongoliaMO - MacaoMP - Northern Mariana IslandsMQ - MartiniqueMR - MauritaniaMS - MontserratMT - MaltaMU - MauritiusMV - MaldivesMW - MalawiMX - MexicoMY - MalaysiaMZ - MozambiqueNA - NamibiaNC - New CaledoniaNE - NigerNF - Norfolk IslandNG - NigeriaNI - NicaraguaNL - NetherlandsNO - NorwayNP - NepalNR - NauruNU - NiueNZ - New ZealandOM - OmanPA - PanamaPE - PeruPF - French PolynesiaPG - Papua New GuineaPH - PhilippinesPK - PakistanPL - PolandPM - Saint Pierre and MiquelonPN - PitcairnPR - Puerto RicoPS - Palestine, State ofPT - PortugalPW - PalauPY - ParaguayQA - QatarRE - RéunionRO - RomaniaRS - SerbiaRU - Russian FederationRW - RwandaSA - Saudi ArabiaSB - Solomon IslandsSC - SeychellesSD - SudanSE - SwedenSG - SingaporeSH - Saint Helena, Ascension and Tristan da CunhaSI - SloveniaSJ - Svalbard and Jan MayenSK - SlovakiaSL - Sierra LeoneSN - SenegalSO - SomaliaSP - San MarinoSR - SurinameSS - South SudanST - Sao Tome and PrincipeSV - El SalvadorSX - Sint Maarten (Dutch part)SY - Syrian Arab RepublicSZ - EswatiniTC - Turks and Caicos IslandsTD - ChadTF - French Southern TerritoriesTG - TogoTH - ThailandTJ - TajikistanTK - TokelauTL - Timor-LesteTM - TurkmenistanTN - TunisiaTO - TongaTR - TurkeyTT - Trinidad and TobagoTV - TuvaluTW - Taiwan, Province of ChinaTZ - Tanzania, United Republic ofUA - UkraineUG - UgandaUM - United States Minor Outlying IslandsUS - United States of AmericaUY - UruguayUZ - UzbekistanVA - Holy SeeVC - Saint Vincent and the GrenadinesVE - Venezuela (Bolivarian Republic of)VG - Virgin Islands (British)VI - Virgin Islands (U.S.)VN - VietnamVU - VanuatuWF - Wallis and FutunaWS - SamoaYE - YemenYT - MayotteZA - South AfricaZM - ZambiaZW - Zimbabwe&quot;) or . = concat(&quot;Select CountryAD - AndorraAE - United Arab EmiratesAF - AfghanistanAG - Antigua and BarbudaAI - AnguillaAL - AlbaniaAM - ArmeniaAO - AngolaAQ - AntarcticaAR - ArgentinaAS - American SamoaAT - AustriaAU - AustraliaAW - ArubaAX - Åland IslandsAZ - AzerbaijanBA - Bosnia and HerzegovinaBB - BarbadosBD - BangladeshBE - BelgiumBF - Burkina FasoBG - BulgariaBH - BahrainBI - BurundiBJ - BeninBL - Saint BarthélemyBM - BermudaBN - Brunei DarussalamBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBR - BrazilBS - BahamasBT - BhutanBV - Bouvet IslandBW - BotswanaBY - BelarusBZ - BelizeCA - CanadaCC - Cocos (Keeling) IslandsCD - Congo (Democratic Republic of the)CF - Central African RepublicCG - CongoCH - SwitzerlandCI - Côte d&quot; , &quot;'&quot; , &quot;IvoireCK - Cook IslandsCL - ChileCM - CameroonCN - ChinaCO - ColombiaCR - Costa RicaCU - CubaCV - Cabo VerdeCW - CuraçaoCX - Christmas IslandCY - CyprusCZ - CzechiaDE - GermanyDJ - DjiboutiDK - DenmarkDM - DominicaDO - Dominican RepublicDZ - AlgeriaEC - EcuadorEE - EstoniaEG - EgyptEH - Western SaharaER - EritreaES - SpainET - EthiopiaFI - FinlandFJ - FijiFK - Falkland Islands (Malvinas)FM - Micronesia (Federated States of)FO - Faroe IslandsFR - FranceGA - GabonGB - United Kingdom of Great Britain and Northern IrelandGD - GrenadaGE - GeorgiaGF - French GuianaGG - GuernseyGH - GhanaGI - GibraltarGL - GreenlandGM - GambiaGN - GuineaGP - GuadeloupeGQ - Equatorial GuineaGR - GreeceGS - South Georgia and the South Sandwich IslandsGT - GuatemalaGU - GuamGW - Guinea-BissauGY - GuyanaHK - Hong KongHM - Heard Island and McDonald IslandsHN - HondurasHR - CroatiaHT - HaitiHU - HungaryID - IndonesiaIE - IrelandIL - IsraelIM - Isle of ManIN - IndiaIO - British Indian Ocean TerritoryIQ - IraqIR - Iran (Islamic Republic of)IS - IcelandIT - ItalyJE - JerseyJM - JamaicaJO - JordanJP - JapanKE - KenyaKG - KyrgyzstanKH - CambodiaKI - KiribatiKM - ComorosKN - Saint Kitts and NevisKP - Korea (Democratic People&quot; , &quot;'&quot; , &quot;s Republic of)KR - Korea (Republic of)KW - KuwaitKY - Cayman IslandsKZ - KazakhstanLA - Lao People&quot; , &quot;'&quot; , &quot;s Democratic RepublicLB - LebanonLC - Saint LuciaLI - LiechtensteinLK - Sri LankaLR - LiberiaLS - LesothoLT - LithuaniaLU - LuxembourgLV - LatviaLY - LibyaMA - MoroccoMC - MonacoMD - Moldova (Republic of)ME - MontenegroMF - Saint Martin (French part)MG - MadagascarMH - Marshall IslandsMK - North MacedoniaML - MaliMM - MyanmarMN - MongoliaMO - MacaoMP - Northern Mariana IslandsMQ - MartiniqueMR - MauritaniaMS - MontserratMT - MaltaMU - MauritiusMV - MaldivesMW - MalawiMX - MexicoMY - MalaysiaMZ - MozambiqueNA - NamibiaNC - New CaledoniaNE - NigerNF - Norfolk IslandNG - NigeriaNI - NicaraguaNL - NetherlandsNO - NorwayNP - NepalNR - NauruNU - NiueNZ - New ZealandOM - OmanPA - PanamaPE - PeruPF - French PolynesiaPG - Papua New GuineaPH - PhilippinesPK - PakistanPL - PolandPM - Saint Pierre and MiquelonPN - PitcairnPR - Puerto RicoPS - Palestine, State ofPT - PortugalPW - PalauPY - ParaguayQA - QatarRE - RéunionRO - RomaniaRS - SerbiaRU - Russian FederationRW - RwandaSA - Saudi ArabiaSB - Solomon IslandsSC - SeychellesSD - SudanSE - SwedenSG - SingaporeSH - Saint Helena, Ascension and Tristan da CunhaSI - SloveniaSJ - Svalbard and Jan MayenSK - SlovakiaSL - Sierra LeoneSN - SenegalSO - SomaliaSP - San MarinoSR - SurinameSS - South SudanST - Sao Tome and PrincipeSV - El SalvadorSX - Sint Maarten (Dutch part)SY - Syrian Arab RepublicSZ - EswatiniTC - Turks and Caicos IslandsTD - ChadTF - French Southern TerritoriesTG - TogoTH - ThailandTJ - TajikistanTK - TokelauTL - Timor-LesteTM - TurkmenistanTN - TunisiaTO - TongaTR - TurkeyTT - Trinidad and TobagoTV - TuvaluTW - Taiwan, Province of ChinaTZ - Tanzania, United Republic ofUA - UkraineUG - UgandaUM - United States Minor Outlying IslandsUS - United States of AmericaUY - UruguayUZ - UzbekistanVA - Holy SeeVC - Saint Vincent and the GrenadinesVE - Venezuela (Bolivarian Republic of)VG - Virgin Islands (British)VI - Virgin Islands (U.S.)VN - VietnamVU - VanuatuWF - Wallis and FutunaWS - SamoaYE - YemenYT - MayotteZA - South AfricaZM - ZambiaZW - Zimbabwe&quot;))]</value>
      <webElementGuid>56437a57-a25d-4d80-be4e-2eefbe8dad81</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
