<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manufacturer Product Owner</name>
   <tag></tag>
   <elementGuidId>f9149245-59ef-4332-a419-379d7cf291aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductOwner</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductOwner']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dc4c0075-a04c-4d8d-a60c-393d535aaef4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductOwner</value>
      <webElementGuid>6244cf4b-6140-4c57-afcc-a5433a3caff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>f40da08a-eb19-457b-aefa-789579ebaa88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ms-em ml-0</value>
      <webElementGuid>e9db5a45-73f4-4096-85d8-535b1b0de13c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type in Manufacturer</value>
      <webElementGuid>019841d4-013c-47f6-b8a3-6600e6523ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e96d0e70-9f97-4f8a-b277-ed33ba3fcf6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Product Owner is required</value>
      <webElementGuid>7803e777-b1df-4271-8440-2acf945391e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductOwner</value>
      <webElementGuid>fb39a759-b3e5-418f-b754-6174e02a3c41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductOwner&quot;)</value>
      <webElementGuid>a9e42434-2e29-49c4-9000-32de36ce53f2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductOwner']</value>
      <webElementGuid>dfb10d9a-98c6-476d-86c3-4397cae7a484</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductDetail']/div/div/div/div[4]/div/input</value>
      <webElementGuid>4b335c9a-6a33-44ae-b91e-74ba859415c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>aea2e3e5-befc-431a-b323-c53f0b77053b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductOwner' and @type = 'text' and @placeholder = 'Type in Manufacturer' and @name = 'ProductOwner']</value>
      <webElementGuid>1fc89167-7b29-45e3-a930-75fac6f96a4b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
