<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Manufacturer GLN</name>
   <tag></tag>
   <elementGuidId>105be0f3-9ff5-421c-a95b-6d28d3c1d008</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PartyGln</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PartyGln']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9d2fde2d-931b-457a-87b4-8d91d38d5869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ss ml-0 autodisplayBgcolor</value>
      <webElementGuid>c9cb3298-c295-4dac-8440-789683cf998b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PartyGln</value>
      <webElementGuid>1311573c-03e8-4b42-97d7-2c2321230b47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>8e94b91a-9abe-45d2-a770-726ab7c86b4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OwnerGLN</value>
      <webElementGuid>5fc56172-32be-4da3-8e92-1093be5279d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PartyGln&quot;)</value>
      <webElementGuid>c809644e-1cd0-497d-a7b7-66c18c7c0df1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PartyGln']</value>
      <webElementGuid>3e6a5f7a-0b10-4b9d-9ded-9609ee99ad5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductDetail']/div/div/div/div[4]/div[2]/div/div/input</value>
      <webElementGuid>f70a9336-4502-4164-994c-70c9c5fa181b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/input</value>
      <webElementGuid>197ab087-2e45-4fdb-91c5-019c5cf3f0df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PartyGln' and @type = 'text' and @name = 'OwnerGLN']</value>
      <webElementGuid>6dc5790e-39cc-4eff-950a-95ad020edbe1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
