<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Pack Type</name>
   <tag></tag>
   <elementGuidId>3800009e-5eaa-43cd-a67c-97c88748b660</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ProductDetailList[0].PackTypeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>405c66df-cb14-4eb7-9544-1e4d0d53ed64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-3 ProductPackType</value>
      <webElementGuid>5c25febf-a478-4e40-8beb-457db6bbc995</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductDetailList[0].PackTypeId</value>
      <webElementGuid>cf4d3650-0891-4d8f-a7db-9f860b6ff409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ProductDescChange(this)</value>
      <webElementGuid>9b012d82-94be-4710-be3a-e92d8a04fff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>c62e92ef-ba22-4026-94e1-6af06ee810db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PackTypeId field is required.</value>
      <webElementGuid>5a721661-8472-4684-96ec-ce26c73a3f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductDetailList[0].PackTypeId</value>
      <webElementGuid>0774d536-44c4-408d-9181-4b7428e0054f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Pack TypeAMPULEAPPLICATORBAGBLISTER PACKBOTTLEBOTTLE, DISPENSINGBOTTLE, DROPPERBOTTLE, GLASSBOTTLE, PLASTICBOTTLE, PUMPBOTTLE, SPRAYBOTTLE, UNIT-DOSEBOTTLE, WITH APPLICATORBOXBOX, UNIT-DOSECANCANISTERCAPSULECARTONCARTRIDGECASECELLO PACKCONTAINERCONTAINER, FLEXIBLE INTERMEDIATE BULKCUPCUP, UNIT-DOSECYLINDERDEWARDIALPACKDOSE PACKDRUMINHALERINHALER, REFILLJARJUGKITNOT APPLICABLEPACKAGEPACKAGE, COMBINATIONPACKETPAILPATCHPOUCHSUPERSACKSYRINGESYRINGE, GLASSSYRINGE, PLASTICTABMINDERTANKTRAYTUBETUBE, WITH APPLICATORVIALVIAL, DISPENSINGVIAL, GLASSVIAL, MULTI-DOSEVIAL, PATENT DELIVERY SYSTEMVIAL, PHARMACY BULK PACKAGEVIAL, PIGGYBACKVIAL, PLASTICVIAL, SINGLE-DOSEVIAL, SINGLE-USE</value>
      <webElementGuid>6845220e-bcf1-4816-a6ab-8f4d71731247</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductDetailList[0].PackTypeId&quot;)</value>
      <webElementGuid>b6c3b0f0-260a-4f47-9075-acee234da1dc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ProductDetailList[0].PackTypeId']</value>
      <webElementGuid>26425351-a9c2-4191-ac69-4f49068d6a8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductInformation']/div/div[6]/div[2]/select</value>
      <webElementGuid>5751320b-ebf0-4a9c-90e8-13dbfa27f9c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Type'])[1]/following::select[1]</value>
      <webElementGuid>55ba7019-5aed-442b-a8cc-aba26aed032e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pack Size/Pack Description'])[1]/following::select[1]</value>
      <webElementGuid>169902c3-1934-4f12-bd7d-235767e2ecbf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Description'])[1]/preceding::select[1]</value>
      <webElementGuid>900f0351-a6cf-4f53-b8e5-c2123479f159</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/select</value>
      <webElementGuid>79f5d803-0fb0-4f12-82c5-f517c1bc4648</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ProductDetailList[0].PackTypeId' and @name = 'ProductDetailList[0].PackTypeId' and (text() = 'Select Pack TypeAMPULEAPPLICATORBAGBLISTER PACKBOTTLEBOTTLE, DISPENSINGBOTTLE, DROPPERBOTTLE, GLASSBOTTLE, PLASTICBOTTLE, PUMPBOTTLE, SPRAYBOTTLE, UNIT-DOSEBOTTLE, WITH APPLICATORBOXBOX, UNIT-DOSECANCANISTERCAPSULECARTONCARTRIDGECASECELLO PACKCONTAINERCONTAINER, FLEXIBLE INTERMEDIATE BULKCUPCUP, UNIT-DOSECYLINDERDEWARDIALPACKDOSE PACKDRUMINHALERINHALER, REFILLJARJUGKITNOT APPLICABLEPACKAGEPACKAGE, COMBINATIONPACKETPAILPATCHPOUCHSUPERSACKSYRINGESYRINGE, GLASSSYRINGE, PLASTICTABMINDERTANKTRAYTUBETUBE, WITH APPLICATORVIALVIAL, DISPENSINGVIAL, GLASSVIAL, MULTI-DOSEVIAL, PATENT DELIVERY SYSTEMVIAL, PHARMACY BULK PACKAGEVIAL, PIGGYBACKVIAL, PLASTICVIAL, SINGLE-DOSEVIAL, SINGLE-USE' or . = 'Select Pack TypeAMPULEAPPLICATORBAGBLISTER PACKBOTTLEBOTTLE, DISPENSINGBOTTLE, DROPPERBOTTLE, GLASSBOTTLE, PLASTICBOTTLE, PUMPBOTTLE, SPRAYBOTTLE, UNIT-DOSEBOTTLE, WITH APPLICATORBOXBOX, UNIT-DOSECANCANISTERCAPSULECARTONCARTRIDGECASECELLO PACKCONTAINERCONTAINER, FLEXIBLE INTERMEDIATE BULKCUPCUP, UNIT-DOSECYLINDERDEWARDIALPACKDOSE PACKDRUMINHALERINHALER, REFILLJARJUGKITNOT APPLICABLEPACKAGEPACKAGE, COMBINATIONPACKETPAILPATCHPOUCHSUPERSACKSYRINGESYRINGE, GLASSSYRINGE, PLASTICTABMINDERTANKTRAYTUBETUBE, WITH APPLICATORVIALVIAL, DISPENSINGVIAL, GLASSVIAL, MULTI-DOSEVIAL, PATENT DELIVERY SYSTEMVIAL, PHARMACY BULK PACKAGEVIAL, PIGGYBACKVIAL, PLASTICVIAL, SINGLE-DOSEVIAL, SINGLE-USE')]</value>
      <webElementGuid>ee7df6e7-2042-4b5b-990d-d5fee523bde6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
