<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Name</name>
   <tag></tag>
   <elementGuidId>43766e4e-4a81-4eee-ad7a-85b2d703d068</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductDetailList[0].ProductName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>79457ec4-fa37-4943-8526-78ffa3452ff4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ProductName productdetailinput</value>
      <webElementGuid>af002528-4d11-47b9-bcdd-168a8e4c3d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductDetailList[0].ProductName</value>
      <webElementGuid>e41d7b68-5a3d-4491-ac83-dca443052408</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product Name</value>
      <webElementGuid>b6311f86-cdc2-4300-a97e-e3403282f9b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ProductDescChange(this)</value>
      <webElementGuid>52f625a6-569b-47a9-804e-f96fb52cef1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>166ac3b8-cf34-47cd-9312-584a40d65283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>24a70c82-b71c-4241-8b26-32fe3d83bc07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Product Name is required</value>
      <webElementGuid>d9c60b99-c133-455b-a877-72309d942821</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductDetailList[0].ProductName</value>
      <webElementGuid>09d5b580-fd66-4442-9748-d2bf8869e0ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductDetailList[0].ProductName&quot;)</value>
      <webElementGuid>c09cf82b-88e5-4c8a-adfa-5220b3a684a0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductDetailList[0].ProductName']</value>
      <webElementGuid>aa85a2a4-cce0-4265-a060-8481e8983aa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductInformation']/div/div[3]/div/input</value>
      <webElementGuid>9eba8089-2eac-4a52-ac81-d2b221f4bac7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[3]/div/input</value>
      <webElementGuid>536c5145-b026-4374-a758-4ce019cd9023</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductDetailList[0].ProductName' and @placeholder = 'Enter Product Name' and @type = 'text' and @name = 'ProductDetailList[0].ProductName']</value>
      <webElementGuid>3b66112c-5837-4b06-a300-533b6a341fe4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
