<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Identifier Value</name>
   <tag></tag>
   <elementGuidId>c8f1da3a-7206-4115-9584-21e093c794ca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductIdentifierValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductIdentifierValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>49d0d5dd-df3f-4b74-8afd-8e34e4d55f00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-lg</value>
      <webElementGuid>d17fd4f2-b517-4980-addd-4e228097bbc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product Identifier</value>
      <webElementGuid>793526e8-1cd2-466b-83d7-cf7178583267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductIdentifierValue</value>
      <webElementGuid>03e0bb5b-b6c8-43d2-9994-2f32786dee19</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>identifierKeyPress(this)</value>
      <webElementGuid>09edc405-29ee-41aa-971b-6056da5b7ac2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5559975e-b942-4ce5-a56a-c5e18c5ee88f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>dcfff63b-acae-4aa4-b8f7-fcb68014cc74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Product Identifier is required</value>
      <webElementGuid>37734cf5-035b-44be-9a3d-c22bd9fc71a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductIdentifierValue</value>
      <webElementGuid>b890ed25-d560-4d40-a5b2-f3e7b59c7e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductIdentifierValue&quot;)</value>
      <webElementGuid>214b61e8-6a87-4f5d-a993-30e0a7fae395</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductIdentifierValue']</value>
      <webElementGuid>2546150e-4052-4a16-a8c8-a01518e8d3a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddIdentifier']/div/div[2]/div[2]/input</value>
      <webElementGuid>950e11e9-0ffa-4b9b-bcb7-7a0ece7efcf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>81e7fca6-c403-4a1b-9893-ea71d0728f85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Product Identifier' and @id = 'ProductIdentifierValue' and @type = 'text' and @name = 'ProductIdentifierValue']</value>
      <webElementGuid>f24f8112-1ddc-4605-a705-c6dfa0c697f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
