<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Identifier Type</name>
   <tag></tag>
   <elementGuidId>8839ec44-f273-4a77-87f3-79b476d97fc2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductIdentifierType</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductIdentifierType']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>7cbd56e8-a317-4a08-ad3f-7255404912e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-lg</value>
      <webElementGuid>cda9f8eb-1db9-404e-b279-4c3d72011a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type in Product Identifier Type</value>
      <webElementGuid>c23c8363-dc2a-446d-8c15-73ffe3586435</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductIdentifierType</value>
      <webElementGuid>747e0ef8-a94f-4ccb-a152-afbef619d847</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>dd6f6398-98f6-4d90-a8fa-9a09a297688f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8d62982f-df8d-48f1-b000-ef066bd96200</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Product Identifier Type is required</value>
      <webElementGuid>799e117a-861e-43d6-969c-4bc54ee02bb8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductIdentifierType</value>
      <webElementGuid>5c962363-b3d9-4f83-a493-9e65d831041c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductIdentifierType&quot;)</value>
      <webElementGuid>19983376-1d34-4b72-9ffc-30057d9ef22f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductIdentifierType']</value>
      <webElementGuid>55be7e81-27ab-4492-8904-5d13fccd0d09</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddIdentifier']/div/div[2]/div/input</value>
      <webElementGuid>2ec0805d-ae7c-4e16-8d0d-4929ad429b85</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>edf5e262-d1a2-42c5-b5c3-a2f5a669d37b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type in Product Identifier Type' and @id = 'ProductIdentifierType' and @type = 'text' and @name = 'ProductIdentifierType']</value>
      <webElementGuid>c07996f3-977e-4879-993f-b4f10e897e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
