<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Identifier</name>
   <tag></tag>
   <elementGuidId>a7d49983-65da-483f-989a-c60a880441bd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductIdentifierValue</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductIdentifierValue']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>766fc8e9-3cb6-4780-b1eb-81767cf8bc68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-lg</value>
      <webElementGuid>057284af-858c-4404-8f34-dd584f4d69ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type in Product Identifier</value>
      <webElementGuid>bb475222-d3fe-4742-b330-782fe3786a09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductIdentifierValue</value>
      <webElementGuid>5dcba40a-65dd-4b8c-bc97-48328e8b41f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeypress</name>
      <type>Main</type>
      <value>identifierKeyPress(this)</value>
      <webElementGuid>967c1619-308f-4b2a-ad9b-79bbb055a784</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d4adc8a8-e055-4cc5-b6a2-1bfc62d5a65c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b578f526-0085-4cdc-a258-0a1ce6f7d9e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Product Identifier is required</value>
      <webElementGuid>3cf842e9-e2f4-4f23-8f68-05890df165c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductIdentifierValue</value>
      <webElementGuid>4bacb8ab-3c1e-4ad8-9ecc-aec256285aaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductIdentifierValue&quot;)</value>
      <webElementGuid>d3bb5d84-9ec2-4680-820c-97475c58dde9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductIdentifierValue']</value>
      <webElementGuid>11c7ec84-f522-4844-81d1-ef244db4ec1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddIdentifier']/div/div[2]/div[2]/input</value>
      <webElementGuid>e6030903-2b27-4b68-beac-d16daf3506ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>e552853b-09b2-4179-a9c5-735a2445f467</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Type in Product Identifier' and @id = 'ProductIdentifierValue' and @type = 'text' and @name = 'ProductIdentifierValue']</value>
      <webElementGuid>aa8484f2-b8c8-4f88-9ead-a307bc4db701</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
