<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Group</name>
   <tag></tag>
   <elementGuidId>998daa69-5443-491b-b320-b2aebac9d834</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ProductGroup</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductGroup']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>78b52c59-f7d1-4a2d-8290-4425c67502f7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductGroup</value>
      <webElementGuid>602488f6-49fe-4e03-b75c-32f9388ee076</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>25b58e78-01e5-43c1-872c-195e5a795a4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>54be321c-28f6-462e-a1b8-c7353af6d158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type in Group</value>
      <webElementGuid>ec80c599-7170-4be7-b6f0-a1f48ea69820</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>57534767-e6c0-48b0-b027-bc4b054444ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Product Group is required</value>
      <webElementGuid>964b6bcc-7b8f-495b-984d-4a8fde5e9a7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductGroup</value>
      <webElementGuid>a66333d6-cb92-4340-87b1-5848ba5c12a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductGroup&quot;)</value>
      <webElementGuid>a80072a7-8eec-41b1-8820-9c53627cf54d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductGroup']</value>
      <webElementGuid>2a3779e6-1208-49f0-885d-0af39075c8ff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductDetail']/div/div/div/div[5]/div/input</value>
      <webElementGuid>901e33ca-5316-46c0-b7cd-b4f5d2c77d2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/input</value>
      <webElementGuid>c9b1ac6d-e97c-4df4-9b69-f5bdd5094474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductGroup' and @type = 'text' and @placeholder = 'Type in Group' and @name = 'ProductGroup']</value>
      <webElementGuid>512bd2ee-74e7-4b71-9f63-0fdacf171a11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
