<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Proprietary Name</name>
   <tag></tag>
   <elementGuidId>922563a2-5246-435f-96c2-941e00b54ad8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductDetailList[0].ProprietaryName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>76eee4c0-4da7-4cd5-b242-f77d5d6b1a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-3</value>
      <webElementGuid>6a37b728-d64f-4ef9-b151-34885b5d45a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductDetailList[0].ProprietaryName</value>
      <webElementGuid>c1a3196a-4950-4d79-9ea6-7d8945255f66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Proprietary Name</value>
      <webElementGuid>6651eeb0-4812-4cb5-84ce-c79e37d4babd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a0e44432-0c6a-430e-ad8f-7aa5c45a2193</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductDetailList[0].ProprietaryName</value>
      <webElementGuid>ba031be8-3b92-4a25-a8c2-eabc93332541</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductDetailList[0].ProprietaryName&quot;)</value>
      <webElementGuid>bc585d4f-4a15-4c22-8c44-0c4e0a0f8ca7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductDetailList[0].ProprietaryName']</value>
      <webElementGuid>fffcc4e9-d281-41e7-aa6b-071f769bdcb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductInformation']/div/div[3]/div[2]/div/div/input</value>
      <webElementGuid>2208fe44-bb72-45a6-ab60-56961498d662</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div/div/input</value>
      <webElementGuid>f3771f0b-98e2-493d-8927-ac8392a185f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductDetailList[0].ProprietaryName' and @placeholder = 'Enter Proprietary Name' and @type = 'text' and @name = 'ProductDetailList[0].ProprietaryName']</value>
      <webElementGuid>953b7f5d-219a-4103-a241-84c47358bfed</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
