<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Strength</name>
   <tag></tag>
   <elementGuidId>5cd61c77-c11f-481b-a401-9b1adc9fa52e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ProductDetailList[0].Strength']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>333af91f-7b67-422c-82f9-817035e9061c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ProductStrength productdetailinput</value>
      <webElementGuid>6e0dc37f-e595-4de5-8857-3041df6bbbb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ProductDescChange(this)</value>
      <webElementGuid>f7f71983-64fc-4f0a-bef3-f9c4b8e7b7d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ProductDetailList[0].Strength</value>
      <webElementGuid>f866d7c3-a6ac-4ad3-8e4b-9d46e250d764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Strength</value>
      <webElementGuid>a3912fc5-6f4b-468f-ad07-149ea307c12f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>325bce0b-298d-440d-bfb7-24b19d96a59a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7d2fcdba-b6c0-4ba2-9ade-3056289e4ceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>Strength is required</value>
      <webElementGuid>7047b96e-8793-4500-ada2-0589006071c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ProductDetailList[0].Strength</value>
      <webElementGuid>7c6bae0b-72c9-4544-aebe-25b07717a043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductDetailList[0].Strength&quot;)</value>
      <webElementGuid>78c22e77-a65a-4af7-82a5-6a50b74600b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ProductDetailList[0].Strength']</value>
      <webElementGuid>f4d1ec9c-9b37-40dd-a636-d569d2a730d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductInformation']/div/div[5]/div/input</value>
      <webElementGuid>34580655-4ce9-475b-b6ff-44ad0dfae950</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/div/div/div[5]/div/input</value>
      <webElementGuid>91d228cf-a947-4036-b35d-10304d7f571d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ProductDetailList[0].Strength' and @placeholder = 'Enter Strength' and @type = 'text' and @name = 'ProductDetailList[0].Strength']</value>
      <webElementGuid>9ed19885-2f09-454c-9334-e9f78475c76a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
