<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Identifier Type</name>
   <tag></tag>
   <elementGuidId>cf2ac730-f930-4064-b669-ce581ac32ecf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Identifiertype']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Identifiertype</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>56c3799a-26b9-48a8-a054-631879f2bdd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identifiertype</value>
      <webElementGuid>362d690c-e53c-4fdc-bd9c-64f8616b2e0a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchby-fields</value>
      <webElementGuid>b94229f5-5c62-4c3d-834f-86a1c955c4b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d6664f3e-3c74-4ad2-b785-cced0b252211</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProductIdentifiertypeId field is required.</value>
      <webElementGuid>ebd93500-4f2f-41ed-a4d0-6ecf7d749f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchModel.ProductIdentifiertypeId</value>
      <webElementGuid>82332800-7c69-47d5-951a-8678843341a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllUS_ANDAUS_FDA_NDCUS_FDA_NDC442US_FDA_NDC532US_FDA_NDC541US_FDA_NDC542</value>
      <webElementGuid>3874792f-d861-4167-8adb-092df1d3151b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identifiertype&quot;)</value>
      <webElementGuid>4a07667e-10b3-4653-97de-277cb26391d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Identifiertype']</value>
      <webElementGuid>6dfb2c77-3416-4c5d-8003-510cd76d4596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbyfilter']/div/div[3]/select</value>
      <webElementGuid>45913d59-8be1-4b45-8207-6980e6211d25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Identifier Type'])[1]/following::select[1]</value>
      <webElementGuid>94a0e100-1a7a-489f-99d9-ea1e239f0d3b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Code'])[1]/following::select[1]</value>
      <webElementGuid>fef18ba0-3efc-4a2d-b513-864060d9f9a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Identifier'])[1]/preceding::select[1]</value>
      <webElementGuid>1a122025-ae15-4740-bca6-6b40e2604aed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Description'])[1]/preceding::select[1]</value>
      <webElementGuid>3c372e16-0c65-413a-8012-798d529af2e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>5a6d5250-a87b-4bb0-be58-3dbcfa69d5b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Identifiertype' and @name = 'SearchModel.ProductIdentifiertypeId' and (text() = 'AllUS_ANDAUS_FDA_NDCUS_FDA_NDC442US_FDA_NDC532US_FDA_NDC541US_FDA_NDC542' or . = 'AllUS_ANDAUS_FDA_NDCUS_FDA_NDC442US_FDA_NDC532US_FDA_NDC541US_FDA_NDC542')]</value>
      <webElementGuid>c9ba50ea-dde6-437f-a18d-3bfc2965c10e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
