<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Identifier</name>
   <tag></tag>
   <elementGuidId>7d816409-09dc-4e1c-a0e3-ec5c9bf8efa8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Identifier']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Identifier</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b90ce449-b605-4593-8f73-261dc214f168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Identifier</value>
      <webElementGuid>e4768ea1-03da-43ed-84e5-329a0fb0dfb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchby-fields identifier-value-field</value>
      <webElementGuid>1e25fcf0-fd23-414f-8294-e261be502cf2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product Identifier</value>
      <webElementGuid>81b21efc-6ca2-49e6-a2ba-21c3f62a0615</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>49db8144-7b3d-44e9-ada7-425107c748ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchModel.ProductIdentifier</value>
      <webElementGuid>6e0cdaa8-f42c-4540-8b58-30e66db63224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Identifier&quot;)</value>
      <webElementGuid>cd999ef7-a3ae-41d5-8e2d-c93864e64af9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Identifier']</value>
      <webElementGuid>592789cd-7266-4944-9819-e5ecb4f8d7ca</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbyfilter']/div/div[4]/input</value>
      <webElementGuid>6407e331-597d-4ad9-a918-636c9e136ab6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/input</value>
      <webElementGuid>5301e95c-4215-4ec4-a14f-817898fb77ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Identifier' and @placeholder = 'Enter Product Identifier' and @type = 'text' and @name = 'SearchModel.ProductIdentifier']</value>
      <webElementGuid>ede5d88b-7c89-4127-b684-3e062a016985</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
