<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Status</name>
   <tag></tag>
   <elementGuidId>cc40b4da-30d5-4428-aede-ff9ec085d7d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='StatusId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#StatusId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>b9131166-2b85-4422-92b5-9dbbf8a287cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>StatusId</value>
      <webElementGuid>7baf3a94-6036-4724-be3e-527dbec7ff55</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchby-fields</value>
      <webElementGuid>e3cf7e7c-3a2a-450a-a2fa-12fa820baec4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>829b2339-2e1a-41ad-a446-d318c46d6f6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProductStatusId field is required.</value>
      <webElementGuid>0dc0ab40-b2ce-4750-b9be-ac59788df96c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchModel.ProductStatusId</value>
      <webElementGuid>a9019686-8407-4418-98c8-306f2f923a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllActiveInactiveDraft</value>
      <webElementGuid>e314e2c6-5122-48fc-8ede-209c56673364</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;StatusId&quot;)</value>
      <webElementGuid>4efc7c42-791a-42cc-86d6-27f212d7b093</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='StatusId']</value>
      <webElementGuid>76e32b29-e397-429a-bee7-b22e635de815</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbyfilter']/div[2]/div[3]/select</value>
      <webElementGuid>71405e88-24a7-4935-85d9-f31d9432a742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[1]</value>
      <webElementGuid>47774490-9205-48cf-b25b-719fbf6b7da0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target Market'])[1]/following::select[2]</value>
      <webElementGuid>fedb2ce0-dc23-4ec5-bf22-ba5cf3e5d4ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Owner'])[1]/preceding::select[1]</value>
      <webElementGuid>81809455-944b-4b50-ae76-2623fb97bcf7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Group'])[2]/preceding::select[2]</value>
      <webElementGuid>736674c9-203a-4ab3-96b4-f6b2c5fc9562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/select</value>
      <webElementGuid>cc67ced9-9f19-46d8-a6f1-3c607ff43e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'StatusId' and @name = 'SearchModel.ProductStatusId' and (text() = 'AllActiveInactiveDraft' or . = 'AllActiveInactiveDraft')]</value>
      <webElementGuid>76aa4d25-e94e-4c6a-9ea4-50bf64f779d5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
