<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Group</name>
   <tag></tag>
   <elementGuidId>53a3269b-f9d0-4386-a523-23ec7cffc962</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='Group']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Group</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>61034019-7930-46c8-ab3d-3dc1ae143ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Group</value>
      <webElementGuid>8e5dec21-3dae-4d4a-8038-986631dcb2e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchby-fields</value>
      <webElementGuid>48ff1bd2-50b3-4e3c-b391-1ae42f512759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5fed3c31-b27a-4862-949f-56bc773fcf34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProductGroupId field is required.</value>
      <webElementGuid>5c897c60-44c0-4cec-84ab-3eba502f3083</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchModel.ProductGroupId</value>
      <webElementGuid>da90934c-f47b-49e1-80a4-c5d2a9ffeb43</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllAntibioticsProd GRP Code 286Prod GRP Code 327Prod GRP Code 48Prod GRP Code 605Prod GRP Code 773Prod GRP Code 862Prod GRP Code 864ProducGroup_AutomationProduct_Group AutomationProduct_Group AutomationProduct_Group AutomationProduct_Group Automation 136.6713455492896Product_Group Automation 809ProductGroupCode Automation 325ProductGroupCode Automation 37ProductGroupCode Automation 387ProductGroupCode Automation 616ProductGroupCode Automation 699ProductGroupCode Automation 716ProductGroupCode Automation 754ProductGroupCode Automation 792ProductGroupCode Automation 809ProductGroupCode Automation 864ProductGroupCode Automation 952</value>
      <webElementGuid>19838f81-33eb-490a-bd7b-1e5002de1224</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Group&quot;)</value>
      <webElementGuid>73a74e4f-8802-4007-992f-7ea708ea4c17</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='Group']</value>
      <webElementGuid>ffa1836d-a3c4-4163-8b0b-5a54d1d6777f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbyfilter']/div[3]/div[2]/select</value>
      <webElementGuid>292ca67d-6703-4125-8221-fb838ad6e6c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Group'])[2]/following::select[1]</value>
      <webElementGuid>47033653-21a6-46a4-ab21-32297d04b565</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Owner'])[1]/following::select[2]</value>
      <webElementGuid>acd885a0-7087-4fb4-9cee-33355c540d52</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::select[1]</value>
      <webElementGuid>8529916d-1aaa-4dc9-9eea-e444bc5d57f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear'])[1]/preceding::select[1]</value>
      <webElementGuid>14c44d16-5b89-4e69-b691-c57c46a99955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>6fb0e5e9-0286-459f-83a4-f5e5342b1e59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'Group' and @name = 'SearchModel.ProductGroupId' and (text() = 'AllAntibioticsProd GRP Code 286Prod GRP Code 327Prod GRP Code 48Prod GRP Code 605Prod GRP Code 773Prod GRP Code 862Prod GRP Code 864ProducGroup_AutomationProduct_Group AutomationProduct_Group AutomationProduct_Group AutomationProduct_Group Automation 136.6713455492896Product_Group Automation 809ProductGroupCode Automation 325ProductGroupCode Automation 37ProductGroupCode Automation 387ProductGroupCode Automation 616ProductGroupCode Automation 699ProductGroupCode Automation 716ProductGroupCode Automation 754ProductGroupCode Automation 792ProductGroupCode Automation 809ProductGroupCode Automation 864ProductGroupCode Automation 952' or . = 'AllAntibioticsProd GRP Code 286Prod GRP Code 327Prod GRP Code 48Prod GRP Code 605Prod GRP Code 773Prod GRP Code 862Prod GRP Code 864ProducGroup_AutomationProduct_Group AutomationProduct_Group AutomationProduct_Group AutomationProduct_Group Automation 136.6713455492896Product_Group Automation 809ProductGroupCode Automation 325ProductGroupCode Automation 37ProductGroupCode Automation 387ProductGroupCode Automation 616ProductGroupCode Automation 699ProductGroupCode Automation 716ProductGroupCode Automation 754ProductGroupCode Automation 792ProductGroupCode Automation 809ProductGroupCode Automation 864ProductGroupCode Automation 952')]</value>
      <webElementGuid>db5d1fdf-002b-4a36-abb3-c79aa727b391</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
