<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Owner</name>
   <tag></tag>
   <elementGuidId>3991c18c-a6fc-4812-8a36-34e3af597139</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OwnerName']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OwnerName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5d289475-3818-4de0-899c-b07b8f587a60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OwnerName</value>
      <webElementGuid>1193f4e6-8f0d-4689-b6ad-4c100e4dc7d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchby-fields</value>
      <webElementGuid>83d0be26-9d19-42dc-a640-6768da83aaa9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>88f74fec-8caf-4e44-98a7-cd68959bb4c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProductOwnerId field is required.</value>
      <webElementGuid>e79e46a8-27cc-4457-b168-56b1caf69cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchModel.ProductOwnerId</value>
      <webElementGuid>d49979c4-66bb-4b22-a2fe-43e98c76462c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllAppco Pharma LLCAutomation Party 479McKessonMylan Inc.New RKnew_cal56northstarNorthStar Healthcare Unlimited CompanyParty 1_ImportedParty 13740Party 2_ImportedParty 29604Party 3_ImportParty 32888Party 4_ImportParty 63583Party 89900Party Automation 17Party Automation 20313Party Automation 372Party Automation 5268Party Automation 54033Party Automation 61170Party Automation 65603Party Automation 65914Party Automation 78736Party Automation 823Party Automation 859Party Automation 883Party Automation 98589Party Automation 995Party Test 101Pharmaceutics International IncRk_1Rk_1Rk_2Rk_2RK-Pharmarte_imp</value>
      <webElementGuid>ed792ffe-c0a0-4eb5-864d-ab9cc33a8a64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OwnerName&quot;)</value>
      <webElementGuid>b57677db-b84f-4c86-963e-e3985b1aab4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OwnerName']</value>
      <webElementGuid>cd9de367-ed2e-4594-87d5-66c6cc0c859d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbyfilter']/div[3]/div/select</value>
      <webElementGuid>fd4faa12-5d49-4652-83a8-ddf7242a6abe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Owner'])[1]/following::select[1]</value>
      <webElementGuid>9ad2733e-212b-4282-91a4-77db736457a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/following::select[2]</value>
      <webElementGuid>dc6da63d-5964-4154-8f39-e9fb0f3fd5fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Group'])[2]/preceding::select[1]</value>
      <webElementGuid>c30edd9d-0ece-4d0f-ad5e-a8f564c9dcac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[1]/preceding::select[2]</value>
      <webElementGuid>e6b17c0d-8fdf-46d9-9d8a-d7f1e8cac378</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>05d06f9e-c818-49e8-88d7-24787330f46d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OwnerName' and @name = 'SearchModel.ProductOwnerId' and (text() = 'AllAppco Pharma LLCAutomation Party 479McKessonMylan Inc.New RKnew_cal56northstarNorthStar Healthcare Unlimited CompanyParty 1_ImportedParty 13740Party 2_ImportedParty 29604Party 3_ImportParty 32888Party 4_ImportParty 63583Party 89900Party Automation 17Party Automation 20313Party Automation 372Party Automation 5268Party Automation 54033Party Automation 61170Party Automation 65603Party Automation 65914Party Automation 78736Party Automation 823Party Automation 859Party Automation 883Party Automation 98589Party Automation 995Party Test 101Pharmaceutics International IncRk_1Rk_1Rk_2Rk_2RK-Pharmarte_imp' or . = 'AllAppco Pharma LLCAutomation Party 479McKessonMylan Inc.New RKnew_cal56northstarNorthStar Healthcare Unlimited CompanyParty 1_ImportedParty 13740Party 2_ImportedParty 29604Party 3_ImportParty 32888Party 4_ImportParty 63583Party 89900Party Automation 17Party Automation 20313Party Automation 372Party Automation 5268Party Automation 54033Party Automation 61170Party Automation 65603Party Automation 65914Party Automation 78736Party Automation 823Party Automation 859Party Automation 883Party Automation 98589Party Automation 995Party Test 101Pharmaceutics International IncRk_1Rk_1Rk_2Rk_2RK-Pharmarte_imp')]</value>
      <webElementGuid>41a3c976-4dd3-4b09-9a84-ac8a61503f9c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
