<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Target Market</name>
   <tag></tag>
   <elementGuidId>ca935182-65e1-4300-b65c-605515c7c42c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='TargetMarket']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#TargetMarket</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>e9359309-2eac-46a9-a8ce-7f011607d32c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>TargetMarket</value>
      <webElementGuid>f2f42ce1-5d93-48ce-95d0-dd8701e42229</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>searchby-fields</value>
      <webElementGuid>fc9e1160-7cf0-4bf8-b1d3-9f90c298641b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9dfb19e7-9f19-4de6-9098-77afea308a1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The TargetMarketId field is required.</value>
      <webElementGuid>789437b1-8e67-443b-a403-982e5f1ac75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SearchModel.TargetMarketId</value>
      <webElementGuid>816de6f9-a021-40bc-bbd7-5f78b463a99c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>AllABWAFGAGOAIAALAALBANDAREARGARMASMATAATFATGAUSAUTAZEBDIBELBENBESBFABGDBGRBHRBHSBIHBLMBLRBLZBMUBOLBRABRBBRNBTNBVTBWACAFCANCCKCHECHLCHNCIVCMRCODCOGCOKCOLCOMCPVCRICUBCUWCXRCYMCYPCZEDEUDJIDMADNKDOMDZAECUEGYERIESHESPESTETHFINFJIFLKFRAFROFSMGABGBRGEOGGYGHAGIBGINGLPGMBGNBGNQGRCGRDGRLGTMGUFGUMGUYHKGHMDHNDHRVHTIHUNIDNIMNINDIOTIRLIRNIRQISLISRITAJAMJEYJORJPNKAZKENKGZKHMKIRKNAKORKWTLAOLBNLBRLBYLCALIELKALSOLTULUXLVAMACMAFMARMCOMDAMDGMDVMEXMHLMKDMLIMLTMMRMNEMNGMNPMOZMRTMSRMTQMUSMWIMYSMYTNAMNCLNERNFKNGANICNIUNLDNORNPLNRUNZLOMNPAKPANPCNPERPHLPLWPNGPOLPRIPRKPRTPRYPSEPYFQATREUROURUSRWASAUSDNSENSGPSGSSHNSJMSLBSLESLVSMRSOMSPMSRBSSDSTPSURSVKSVNSWESWZSXMSYCSYRTCATCDTGOTHATJKTKLTKMTLSTONTTOTUNTURTUVTWNTZAUGAUKRUMIURYUSAUZBVATVCTVENVGBVIRVNMVUTWLFWSMYEMZAFZMBZWE</value>
      <webElementGuid>56a0489a-12f1-4382-8f5e-f3dc70fe6cbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;TargetMarket&quot;)</value>
      <webElementGuid>0abb84d5-b606-4733-852d-d0985bbad2bb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='TargetMarket']</value>
      <webElementGuid>de892490-7406-4d88-aa38-836579177cce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='searchbyfilter']/div[2]/div[2]/select</value>
      <webElementGuid>c3a6b0dc-ae66-4b96-ad9c-a352b39539b9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Target Market'])[1]/following::select[1]</value>
      <webElementGuid>3c2160a4-1b94-4e07-94e4-f81c7afc4543</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Description'])[1]/following::select[1]</value>
      <webElementGuid>f744e787-2d6a-4177-9334-5d40a2469a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[1]/preceding::select[1]</value>
      <webElementGuid>32617d7d-4aa6-47e2-a4bc-f9dbaa24c8c7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Owner'])[1]/preceding::select[2]</value>
      <webElementGuid>bc09be0d-6f7c-443e-827e-6e38f39a38b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>3e091bc3-1d20-40ba-9e05-9f0578f80730</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'TargetMarket' and @name = 'SearchModel.TargetMarketId' and (text() = 'AllABWAFGAGOAIAALAALBANDAREARGARMASMATAATFATGAUSAUTAZEBDIBELBENBESBFABGDBGRBHRBHSBIHBLMBLRBLZBMUBOLBRABRBBRNBTNBVTBWACAFCANCCKCHECHLCHNCIVCMRCODCOGCOKCOLCOMCPVCRICUBCUWCXRCYMCYPCZEDEUDJIDMADNKDOMDZAECUEGYERIESHESPESTETHFINFJIFLKFRAFROFSMGABGBRGEOGGYGHAGIBGINGLPGMBGNBGNQGRCGRDGRLGTMGUFGUMGUYHKGHMDHNDHRVHTIHUNIDNIMNINDIOTIRLIRNIRQISLISRITAJAMJEYJORJPNKAZKENKGZKHMKIRKNAKORKWTLAOLBNLBRLBYLCALIELKALSOLTULUXLVAMACMAFMARMCOMDAMDGMDVMEXMHLMKDMLIMLTMMRMNEMNGMNPMOZMRTMSRMTQMUSMWIMYSMYTNAMNCLNERNFKNGANICNIUNLDNORNPLNRUNZLOMNPAKPANPCNPERPHLPLWPNGPOLPRIPRKPRTPRYPSEPYFQATREUROURUSRWASAUSDNSENSGPSGSSHNSJMSLBSLESLVSMRSOMSPMSRBSSDSTPSURSVKSVNSWESWZSXMSYCSYRTCATCDTGOTHATJKTKLTKMTLSTONTTOTUNTURTUVTWNTZAUGAUKRUMIURYUSAUZBVATVCTVENVGBVIRVNMVUTWLFWSMYEMZAFZMBZWE' or . = 'AllABWAFGAGOAIAALAALBANDAREARGARMASMATAATFATGAUSAUTAZEBDIBELBENBESBFABGDBGRBHRBHSBIHBLMBLRBLZBMUBOLBRABRBBRNBTNBVTBWACAFCANCCKCHECHLCHNCIVCMRCODCOGCOKCOLCOMCPVCRICUBCUWCXRCYMCYPCZEDEUDJIDMADNKDOMDZAECUEGYERIESHESPESTETHFINFJIFLKFRAFROFSMGABGBRGEOGGYGHAGIBGINGLPGMBGNBGNQGRCGRDGRLGTMGUFGUMGUYHKGHMDHNDHRVHTIHUNIDNIMNINDIOTIRLIRNIRQISLISRITAJAMJEYJORJPNKAZKENKGZKHMKIRKNAKORKWTLAOLBNLBRLBYLCALIELKALSOLTULUXLVAMACMAFMARMCOMDAMDGMDVMEXMHLMKDMLIMLTMMRMNEMNGMNPMOZMRTMSRMTQMUSMWIMYSMYTNAMNCLNERNFKNGANICNIUNLDNORNPLNRUNZLOMNPAKPANPCNPERPHLPLWPNGPOLPRIPRKPRTPRYPSEPYFQATREUROURUSRWASAUSDNSENSGPSGSSHNSJMSLBSLESLVSMRSOMSPMSRBSSDSTPSURSVKSVNSWESWZSXMSYCSYRTCATCDTGOTHATJKTKLTKMTLSTONTTOTUNTURTUVTWNTZAUGAUKRUMIURYUSAUZBVATVCTVENVGBVIRVNMVUTWLFWSMYEMZAFZMBZWE')]</value>
      <webElementGuid>ffe9dfed-331f-4726-b2d8-b621a6e65614</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
