<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Group Code</name>
   <tag></tag>
   <elementGuidId>aaad7fea-ccc4-4c43-8481-76eee45e4bc1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='group-code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#group-code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>74e70a9a-d9f8-43e5-9db8-f81f9fe03646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-lg input-validation-error input-validation-error</value>
      <webElementGuid>74c880ff-da8d-4366-a8a0-5b289ca597ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>group-code</value>
      <webElementGuid>feb1aedb-39b9-47bf-a293-237ad39bf0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Product Group</value>
      <webElementGuid>71095856-a763-426f-84c1-d27dc46b188a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onfocus</name>
      <type>Main</type>
      <value>clearegroupmsgs()</value>
      <webElementGuid>bcd7c548-37e8-4bb4-9574-8aa073a8df74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2b8619f1-4568-4741-9932-c06d7d88df7f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e0e486f0-9999-4978-9075-c6388eecad0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>ProductGroup is required</value>
      <webElementGuid>ade6c310-633d-4841-9931-2a677a664be2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Code</value>
      <webElementGuid>5418f266-ea54-4380-8fc4-87736f75d73d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;group-code&quot;)</value>
      <webElementGuid>1f722e27-c83b-414d-82e3-4b60f4509a06</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='group-code']</value>
      <webElementGuid>bec531bf-5b01-4f45-9171-0838fc0743e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_ProductGroup']/div/div/input</value>
      <webElementGuid>6e6fd2ec-c0c6-411f-bcbd-9f1e829363e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div[2]/div/div/div/div/div/input</value>
      <webElementGuid>7057d253-c3b7-4ada-9179-cfc56c9864ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'group-code' and @placeholder = 'Enter Product Group' and @type = 'text' and @name = 'Code']</value>
      <webElementGuid>c2f673ce-7e95-41c6-968d-463d95a7b5b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
