<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_SaveSystem</name>
   <tag></tag>
   <elementGuidId>2f94dd4c-d448-4691-9f44-05c4ec4a6d55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_Submit_System']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_Submit_System</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>0f6623b2-b797-435e-b547-9bd5e48f349d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Submit_System</value>
      <webElementGuid>b3a81284-1e58-4026-8bbf-6dbeded1f689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>64190e1d-633e-446a-a874-c599a271d015</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save mt-3 ml-2</value>
      <webElementGuid>98b3e32c-d959-410f-b3fa-dfe78f540b02</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>35b92d55-534f-4edc-af33-c77f3a60d879</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Submit_System&quot;)</value>
      <webElementGuid>a6d4f863-11ba-4038-a3fe-46a63646434d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_Submit_System']</value>
      <webElementGuid>c3979c49-2671-4e9f-9d0b-d9f522c1d52e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-AddSystem']/div/div/div[3]/button[2]</value>
      <webElementGuid>c74820a7-49df-470f-b45c-1ab8bd2bf30e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[5]/following::button[1]</value>
      <webElementGuid>990f570d-16d4-4608-85d3-1cd64e6d667d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Separate Prefix'])[1]/following::button[2]</value>
      <webElementGuid>3c075f47-db4b-40ac-8075-1c6ce2e538db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New Range'])[2]/preceding::button[1]</value>
      <webElementGuid>1641eb21-fcff-42b4-9932-b9ae629af2c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[6]/preceding::button[2]</value>
      <webElementGuid>356490dc-1927-4464-bf01-b2a4c9d9326e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div[3]/button[2]</value>
      <webElementGuid>61b055aa-a8b0-4aaa-a5b6-16396e606325</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_Submit_System' and @type = 'button' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>938ea302-017c-4d82-927e-fbd204e6e6e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
