<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Range</name>
   <tag></tag>
   <elementGuidId>fb6a11d6-9ff0-46a2-9f4e-bf3d976d0311</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='RangeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#RangeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>ab9a162c-e7f8-4c76-b4c0-0f4209983a8c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>RangeId</value>
      <webElementGuid>427bd828-392e-4e5f-a7f2-bd7d34840a9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profile</value>
      <webElementGuid>bdb06bb1-36f8-4c6f-9c74-6cdbdeb55ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>systemRangeChange(this)</value>
      <webElementGuid>2f4161d2-98c8-4e62-98fa-15a97932d3d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>69d51c21-71b7-499e-bd77-a18407ba98c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RangeId field is required.</value>
      <webElementGuid>f06a991e-704e-4ec4-8eff-1ec2666ccae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>RangeId</value>
      <webElementGuid>bd855131-6479-4aba-872f-84daee063c28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Range100000000000-999999999999</value>
      <webElementGuid>e4dd3fef-5844-468c-a97b-d4b3bb7290ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;RangeId&quot;)</value>
      <webElementGuid>459f8457-d053-4b11-b17d-af204e17d086</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='RangeId']</value>
      <webElementGuid>523632dd-388d-40e0-84ea-d2806a24fddc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div[2]/div/select</value>
      <webElementGuid>e312816f-118e-40b7-81a6-335631328497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Range'])[1]/following::select[1]</value>
      <webElementGuid>f317209e-71f1-4997-99e7-c0cacd155f90</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Name'])[1]/following::select[2]</value>
      <webElementGuid>d4725981-c67e-4243-8153-3f0685415583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='From'])[1]/preceding::select[1]</value>
      <webElementGuid>a16d75a1-0ad9-46c0-9053-1179ca4ab336</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='To'])[1]/preceding::select[1]</value>
      <webElementGuid>25d481c7-8c8e-437b-b3bf-a9bf64fb720f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/select</value>
      <webElementGuid>570cf05f-ed27-4c73-87c5-7caef5eac343</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'RangeId' and @name = 'RangeId' and (text() = 'Select Range100000000000-999999999999' or . = 'Select Range100000000000-999999999999')]</value>
      <webElementGuid>2ddfe343-9642-4b34-9146-1b2cc34b5d2e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
