<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GCP Length</name>
   <tag></tag>
   <elementGuidId>1bafeb20-a58a-4a9d-92a6-10b9a75927d1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#gscompanyprefixlengthddl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='gscompanyprefixlengthddl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7a363f6f-65a9-438a-ae16-06448ae36b37</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gscompanyprefixlengthddl</value>
      <webElementGuid>3ac83a97-4845-4f96-8343-8fbe0e51ae5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-5</value>
      <webElementGuid>05ab7086-39bc-4347-a429-603f6cfaa75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gcplengthbasesgln()</value>
      <webElementGuid>5586ad30-8a63-492f-9011-907ef371c823</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1d336545-8325-4f87-92be-840da5129776</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GS1CompanyPrefixLength field is required.</value>
      <webElementGuid>fc41d123-679d-4711-b779-8b593478a157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyGLN.GS1CompanyPrefixLength</value>
      <webElementGuid>8eed2d33-30e0-4c3a-965b-33390673598c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select GCP Length456789101112</value>
      <webElementGuid>1397c54b-3028-4304-a590-429fbaa1dc09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gscompanyprefixlengthddl&quot;)</value>
      <webElementGuid>21cb17d3-d831-4d4f-83c6-14b8a29c8b67</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gscompanyprefixlengthddl']</value>
      <webElementGuid>8c7cd286-0588-467e-9fe7-d70f2ada3743</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='glnModel']/div/div[2]/select</value>
      <webElementGuid>6be7bec2-08a3-4e12-9cdc-38e3e6677ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix Length'])[1]/following::select[1]</value>
      <webElementGuid>95a30ac0-efd9-4921-9e64-070ffa071926</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLN should be 13 digits'])[1]/following::select[1]</value>
      <webElementGuid>5a74cba8-8803-490b-9091-0c32380200da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLN Extension'])[1]/preceding::select[1]</value>
      <webElementGuid>009ffba9-3d78-44dd-8bc2-16be89a1d61c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGLN'])[1]/preceding::select[1]</value>
      <webElementGuid>8b7fb4c1-9d0b-4eee-bcdf-b1fa569dff31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>005ecbdc-ceb7-45d9-b754-e58251d43baf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gscompanyprefixlengthddl' and @name = 'PartyGLN.GS1CompanyPrefixLength' and (text() = 'Select GCP Length456789101112' or . = 'Select GCP Length456789101112')]</value>
      <webElementGuid>c98f14b0-d2df-4d3e-8c0d-87a9f8d086d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
