<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GLN</name>
   <tag></tag>
   <elementGuidId>f10b488b-1ddc-43ed-a587-324af4ccf044</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#partyglntxt</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partyglntxt']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>21c106d7-391f-4a4a-805d-a694935a8ae9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>f9df8969-27da-4675-a821-1478ae1344c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partyglntxt</value>
      <webElementGuid>9586ac87-7ec3-489f-b95b-bfe0d414d546</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter GLN</value>
      <webElementGuid>abeb2645-10f0-4253-a29e-5a3c5469727a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>e5600532-4353-4e88-b9bf-9b756d02d0e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>sglnsystemgenerated()</value>
      <webElementGuid>8659f5d0-a539-41e9-b09e-c977c20b8ba7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>this.value=this.value.replace(/[^0-9]/g,&quot;&quot;)</value>
      <webElementGuid>3c132ba5-68af-4dbe-aa2e-0a4fe9a5c69b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2ecf13f3-e2ec-4844-8d7c-141761433a23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>60844bc2-01ae-4b55-a139-d11852a35f0f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length</name>
      <type>Main</type>
      <value>GLN should be 13 digits</value>
      <webElementGuid>13708264-1a2c-4f98-9cfa-e8dad0caf930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-max</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>e7152017-ade3-4dba-ae14-bdac81379ba3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-length-min</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>922a61a8-6cfb-4179-ac97-428aa9a214e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>GLN is required</value>
      <webElementGuid>2f8c774a-aba2-4fd1-9de0-88f7b18ebc3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyGLN.GLN</value>
      <webElementGuid>ce5d2a33-6055-45bb-9bdb-b0a72b91698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partyglntxt&quot;)</value>
      <webElementGuid>e5bc6308-3457-431c-b0f0-4f1a8f578859</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partyglntxt']</value>
      <webElementGuid>c3f9800e-d869-4657-a00c-1bc8008efe02</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='glnModel']/div/div/input</value>
      <webElementGuid>8429007c-51c0-4f27-a107-ba629d9b76b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[6]/div/div/input</value>
      <webElementGuid>1055c36e-2bc1-4ea7-a1da-3bf3ee78f333</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partyglntxt' and @placeholder = 'Enter GLN' and @type = 'text' and @name = 'PartyGLN.GLN']</value>
      <webElementGuid>5d5800bd-c750-433e-b9dc-d6b4b41a3f0c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
