<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GLNExtension</name>
   <tag></tag>
   <elementGuidId>a818cfed-9d7a-4014-af95-55aee503d30a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#PartyGLN_GLNExtension</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PartyGLN_GLNExtension']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>842a1ce0-f26c-4f2a-b1a8-0490fef56ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PartyGLN_GLNExtension</value>
      <webElementGuid>d059ef08-5d7f-4827-9c9a-e846b7af8cb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>64f83a8f-04e0-4bcf-85e5-bbdc2f55c259</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter GLN Extension</value>
      <webElementGuid>84db0ced-5b8c-4c03-b1ca-57b91badce89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>sglnsystemgenerated()</value>
      <webElementGuid>786c6cf5-6288-42da-a4f4-b561d2d9428f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>76a19db5-2165-41f5-b86f-3aebd3aedb3e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c16085c9-d35b-44fe-a601-c507cd342fc2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>06c23192-130a-47bd-abd4-77c109106cd6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>GLN Extension is required</value>
      <webElementGuid>18fc8533-2970-4b73-81f1-7e143cef24e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyGLN.GLNExtension</value>
      <webElementGuid>de64458e-7f0a-4568-8199-b45c75d8b593</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>cb05e0e6-9cf5-44fa-a98c-7fcbb1b529bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PartyGLN_GLNExtension&quot;)</value>
      <webElementGuid>8dae79c2-b9a2-47f2-ba32-7a3cdd84974a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PartyGLN_GLNExtension']</value>
      <webElementGuid>11792115-abb8-46a9-a05e-fcf8a2058f7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='glnModel']/div[2]/div/input</value>
      <webElementGuid>f51aef07-fa01-4e70-a9ee-c6e7e30be8fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[6]/div[2]/div/input</value>
      <webElementGuid>658c836e-a4a3-4afc-aade-28ea362505a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PartyGLN_GLNExtension' and @placeholder = 'Enter GLN Extension' and @type = 'text' and @name = 'PartyGLN.GLNExtension']</value>
      <webElementGuid>265f3306-551c-4f6e-b1e4-4756349350aa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
