<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Description</name>
   <tag></tag>
   <elementGuidId>5554208f-02be-4d0b-99c0-81848559a11b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='productdescription']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productdescription</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a45d3102-ce3b-4e2d-95ab-3d622180b32b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms-em autodisplayBgcolor ml-0</value>
      <webElementGuid>4b2dc32c-3a63-4169-a2bb-6ef285819577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productdescription</value>
      <webElementGuid>c0d98902-ad4e-4e6b-be4a-e671a12116c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Display Value</value>
      <webElementGuid>872b879d-e9a3-4dcd-9f42-9f99b142d1f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7c0e4cd7-33bf-452d-a22d-2f905c977392</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.ProductDescription</value>
      <webElementGuid>70a19639-e0c4-4fd0-a794-e046f80b9ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productdescription&quot;)</value>
      <webElementGuid>a9a0afe7-ce30-4ce9-82ca-0bf3ea645d99</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='productdescription']</value>
      <webElementGuid>bae712be-e7bd-4a9b-a5f1-63441a8f9a4e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form_Profile']/div/div[2]/div/input</value>
      <webElementGuid>0e1cb1b4-4b1a-4e3b-8d0d-183ef8703b18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>5cd465b5-a9a0-4c0e-a449-070095eea6cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'productdescription' and @placeholder = 'Display Value' and @type = 'text' and @name = 'BasicInfo.ProductDescription']</value>
      <webElementGuid>8893780b-21ec-4582-8691-cc0e3087d4a9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
