<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Product Code</name>
   <tag></tag>
   <elementGuidId>9dafe45e-15bb-4a74-8ff4-0cd440e8b2f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='productcode']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#productcode</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9475b025-cb56-453f-824b-9deee01eb7d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>productcode</value>
      <webElementGuid>0a59d626-ea54-411e-98c7-6b3d4c65d6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-ms-em ml-0</value>
      <webElementGuid>86281032-b386-4382-9bc6-f47db1382ed3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Type in Product Code</value>
      <webElementGuid>3ed9a5eb-56ec-4a15-83d3-4639e553caa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>showSuggestion()</value>
      <webElementGuid>2fa93267-b67a-48bb-a8f1-942536aedbc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>hideSuggesstion()</value>
      <webElementGuid>d06d1402-7bc1-4d3e-a879-d3a1f8c596f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>095e1927-407b-4bfc-bd51-670fc055d13e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.ProductCode</value>
      <webElementGuid>03a76d9d-b29c-4b94-a32a-d5e01539f81f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;productcode&quot;)</value>
      <webElementGuid>6ac67e71-c8e7-4b12-ac60-b4cf6ac1fbdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='productcode']</value>
      <webElementGuid>53fbbb4e-f4cc-425c-9e49-012d506b4354</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='Form_Profile']/div/div/div[2]/div/input</value>
      <webElementGuid>fa49ca9d-2160-478c-9496-20acbe9d06c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div[2]/div/input</value>
      <webElementGuid>c54930da-d578-408a-ae11-a2a61041ba0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'productcode' and @placeholder = 'Type in Product Code' and @type = 'text' and @name = 'BasicInfo.ProductCode']</value>
      <webElementGuid>6ebcd939-3044-407b-82ab-e2064815d7a7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
