<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ProductSearchWindowRow_DO</name>
   <tag></tag>
   <elementGuidId>4bbc8b48-77a9-4309-9c12-17c5fba43f07</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[contains(text(), '${ProductCode}')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.CodeValue.ml-n2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>33b101a5-de40-4af9-9e9e-d69efc7c1d4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>CodeValue ml-n2</value>
      <webElementGuid>584e55fc-9d09-4de4-84a5-6bbae94d23bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>24560124542072</value>
      <webElementGuid>4d5d95db-67c4-4e0c-ae97-4b3bbdf324ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ProductCodeList&quot;)/div[3]/div[@class=&quot;divTableBody&quot;]/div[@class=&quot;rowBorder divTableRow&quot;]/div[@class=&quot;divTableCell col-3 px-0&quot;]/span[@class=&quot;CodeValue ml-n2&quot;]</value>
      <webElementGuid>8637d9c0-a268-40ec-a300-38ccbb9eaa5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='ProductCodeList']/div[3]/div/div/div[2]/span</value>
      <webElementGuid>9ec09de7-30b7-45f6-a3ab-3b8c6ee73b99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Manufacturer Name'])[1]/following::span[1]</value>
      <webElementGuid>07e76b9f-a779-45a1-a717-43c94b7cefdc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Product Name'])[1]/following::span[2]</value>
      <webElementGuid>5b22b2a6-fd48-48b8-8a42-59554046c32b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations 3'])[1]/preceding::span[1]</value>
      <webElementGuid>24ac45df-335d-4fe5-9fb9-56114b7934b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Buspirone Hcl'])[1]/preceding::span[2]</value>
      <webElementGuid>011c6f18-13d9-4023-8ed5-823673dfadab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='24560124542072']/parent::*</value>
      <webElementGuid>81a3119b-6198-4440-8437-a121f38e20d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/div/div[2]/span</value>
      <webElementGuid>1977fcf7-45a6-4d33-97f9-3c7fc0519f70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '24560124542072' or . = '24560124542072')]</value>
      <webElementGuid>d75c5f59-3fab-4e9e-9f12-6509c31c2b45</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
