<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Provider System Name</name>
   <tag></tag>
   <elementGuidId>fbd373a8-a9c9-4444-a987-e7f2e3d132b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[contains(@id,'ProviderSystemId')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9ed59ca-bdd4-447b-89f9-cf2da1a74199</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SgtinVersion[0].ProviderSystemId</value>
      <webElementGuid>770c07a6-c479-43d4-ade0-bd47dffd7dc3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms sgtinprovidersystem</value>
      <webElementGuid>f9142e86-f434-43f6-9e2a-099100ece2eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>ProviderChange(this)</value>
      <webElementGuid>5c142f79-be70-4e75-802b-0ffbaaa72dd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d57a03c9-89db-4a33-b81f-90394c4594ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ProviderSystemId field is required.</value>
      <webElementGuid>c16f0697-c573-4ed2-af04-16e1b396c9c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.ProviderSystemId</value>
      <webElementGuid>460f13b7-cc8c-46b8-9847-fb73a1da97bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select ProviderTestf                          Rk pharma system</value>
      <webElementGuid>853f6d9f-4e3f-494a-900c-1378e80b4d2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SgtinVersion[0].ProviderSystemId&quot;)</value>
      <webElementGuid>aac657d4-a8b2-4a43-896d-4553fc2402d3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='SgtinVersion[0].ProviderSystemId']</value>
      <webElementGuid>68ea9ec2-23b5-4526-983a-7945fe75b919</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Addsgtin']/div/div[2]/div[2]/select</value>
      <webElementGuid>e429d141-2327-4377-a84a-144e1b2e4e80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Provider System Name'])[1]/following::select[1]</value>
      <webElementGuid>2f1a8dee-1108-4487-9f65-3da369513c26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Source'])[1]/following::select[2]</value>
      <webElementGuid>a02f0cc5-5153-4788-85e1-ba73faa03cc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Serial Number Template'])[2]/preceding::select[1]</value>
      <webElementGuid>e88335bb-61da-4bce-acc5-0d91d7d815bb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>78cdb872-fc4b-4aba-ac1e-6322256f8fb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'SgtinVersion[0].ProviderSystemId' and @name = 'item.ProviderSystemId' and (text() = 'Select ProviderTestf                          Rk pharma system' or . = 'Select ProviderTestf                          Rk pharma system')]</value>
      <webElementGuid>1bb97d70-2b0b-43e7-9255-35a556b1063b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
