<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>System Owner Name</name>
   <tag></tag>
   <elementGuidId>43cdc9a4-cc93-495f-a4d8-3452cdae7c1b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'ProviderSystemName')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>be71bf10-8141-419b-a483-a21b00771336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SgtinVersion[0].ProviderSystemName</value>
      <webElementGuid>5eacc75b-6d77-4639-a756-2c03ea91e5d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms sgtinprovidersystem autodisplayBgcolor</value>
      <webElementGuid>b226b054-98fc-4fc7-a902-015cdda68c39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Party Name</value>
      <webElementGuid>bc3d5aa5-c7ce-4247-bf90-7f5425b0e9fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6b98cb8b-5f48-485a-b94a-53e86a623ff0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.ProviderSystemName</value>
      <webElementGuid>1d30ae4a-b48a-4012-9f29-302060b07849</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SgtinVersion[0].ProviderSystemName&quot;)</value>
      <webElementGuid>38afc5b6-d174-44a8-88b5-5125f2f15364</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SgtinVersion[0].ProviderSystemName']</value>
      <webElementGuid>fbf95c5f-c903-40b0-9002-ce9e695cd674</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Addsgtin']/div/div[3]/div[2]/input</value>
      <webElementGuid>4382b564-8515-48fc-8622-6f1a634e6efa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>f2c89e83-79c8-40bc-9f86-1d3641f4dc03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SgtinVersion[0].ProviderSystemName' and @placeholder = 'Party Name' and @type = 'text' and @name = 'item.ProviderSystemName']</value>
      <webElementGuid>6c834b8f-84a2-4333-a70a-77b223f54ebf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
