<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Requesting System</name>
   <tag></tag>
   <elementGuidId>ba73dd9e-9eca-4b15-a8d2-fa141b1df6ad</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdRequestingSystem']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdRequestingSystem</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>5056166a-1fbf-4be3-8150-087520cc0680</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms sgtinrequestingsysinput</value>
      <webElementGuid>08abc7ee-45f5-4800-8927-8c156340f0f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdRequestingSystem</value>
      <webElementGuid>6cb90fa4-71d5-4958-83f8-0258a228efe0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>8e01c01a-eb46-4b3c-97dc-85db5f6afd7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RequestingSystem field is required.</value>
      <webElementGuid>1e443bd3-56a5-427b-a6d8-b0142f518ac5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sgtin.RequestingSystem</value>
      <webElementGuid>294609aa-e189-4f80-8168-c3c75483ff5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select SystemSystem Party Automation 883</value>
      <webElementGuid>074c8566-25ef-49dd-839f-94c8a4ba1b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdRequestingSystem&quot;)</value>
      <webElementGuid>3c7d6358-b5bf-460d-87b8-310e66751143</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdRequestingSystem']</value>
      <webElementGuid>0022308a-9a63-4426-8dec-e5b46ef0f5e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='IdsystemRequest']/select</value>
      <webElementGuid>0e20ee18-8007-43bf-8154-fedebc5dcfe1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting System'])[1]/following::select[1]</value>
      <webElementGuid>a8ab6569-5748-41a0-ba6a-66944a4e9b2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting Party'])[1]/following::select[2]</value>
      <webElementGuid>2e74f7b2-1c25-46f6-8d04-d23b0d376434</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGLN'])[1]/preceding::select[1]</value>
      <webElementGuid>1756383a-2792-480a-89db-39521eae261a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Mode'])[1]/preceding::select[1]</value>
      <webElementGuid>a14f7ad4-88fa-42a2-ab73-8cf61adecf47</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>33cc9c21-148d-4023-b722-58ba445f53d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdRequestingSystem' and @name = 'Sgtin.RequestingSystem' and (text() = 'Select SystemSystem Party Automation 883' or . = 'Select SystemSystem Party Automation 883')]</value>
      <webElementGuid>9b327b8b-df5d-4872-899b-42ba4d143390</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
