<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Requesting Party</name>
   <tag></tag>
   <elementGuidId>1ad970c6-8250-4116-bed0-7530f2905a32</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='IdReqParty']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#IdReqParty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d9b9d2cd-27e4-4ffb-8a15-0839c745b7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-4</value>
      <webElementGuid>d5dc76d4-2c8c-4059-85e6-c1c3822a9d09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>IdReqParty</value>
      <webElementGuid>995fca44-a25f-45ae-a382-e69307ac0a08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>RequestingpartySgtin()</value>
      <webElementGuid>ba1504f5-0a06-4bd6-95c2-ac19e87bc3e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>d07dd3c0-631c-47f2-bba3-c75a314b89a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The RequestParty field is required.</value>
      <webElementGuid>e47d29e7-d501-49c1-8005-d7292ea7d477</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Sgtin.RequestParty</value>
      <webElementGuid>b80a19c8-47bf-4052-87f1-cc35efbf3368</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Requesting PartyParty Automation 883</value>
      <webElementGuid>2dbd231b-841a-49c8-8313-9a21cae0c1e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;IdReqParty&quot;)</value>
      <webElementGuid>26bac25c-415b-47a1-a68d-cf63d4ed7745</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='IdReqParty']</value>
      <webElementGuid>50b23c49-5058-4ba6-a728-becacdc15bd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_sgtin']/div[4]/div/select</value>
      <webElementGuid>90e4aeda-a1e6-48c6-a837-95196ef07c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting Party'])[1]/following::select[1]</value>
      <webElementGuid>2147271e-e790-4675-a53d-31422bb6529f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGTIN Profile Version No.'])[1]/following::select[1]</value>
      <webElementGuid>4a1bb17a-1274-49d5-97ef-b7afcced2c5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Requesting System'])[1]/preceding::select[1]</value>
      <webElementGuid>a77023fc-81cd-4399-8d77-f7b7a4f85ba3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGLN'])[1]/preceding::select[2]</value>
      <webElementGuid>9f7c0ba7-7904-4ee4-8c82-32b9f19581c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>584ac2af-4faf-42c5-b8c3-df3503e60d13</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'IdReqParty' and @name = 'Sgtin.RequestParty' and (text() = 'Select Requesting PartyParty Automation 883' or . = 'Select Requesting PartyParty Automation 883')]</value>
      <webElementGuid>adeb877e-5406-4cc8-8851-457abd2c35bc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
