<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Contact Type</name>
   <tag></tag>
   <elementGuidId>0bec3a66-9830-45be-8a36-26118a26f5c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContactTypeId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ContactTypeId']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>612e4f72-8762-427a-b96e-e57e91558554</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContactTypeId</value>
      <webElementGuid>b097c209-64a5-4136-a209-650ecec67cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row modal-input</value>
      <webElementGuid>29c0f248-649c-49ae-b9d0-6ca522e0e662</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>clearspanmsg()</value>
      <webElementGuid>02431378-e693-4b28-8f49-51295af65adb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4c22829f-1bad-40b0-b527-3c0d3aa1063a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The ContactTypeId field is required.</value>
      <webElementGuid>4371d427-25c8-485d-a5b3-89a8f9eef689</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactTypeId</value>
      <webElementGuid>def41223-2dd8-40b1-a3c9-2df1dc1f7e69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Contact TypeAccounting ContactAccounts Payable ContactAccounts Receivable ContactAdministrative ContactAfter Business Hours ContactAgent ContactClaims ContactConsumer Support ContactCustomer RelationsCustomer Support ContactDangerous Goods ContactDelivery ContactDepartment Or Person Responsible for Processing Purchase OrderDepartment/Employee to Execute Export ProceduresDepartment/Employee to Execute Import ProceduresEmergency Dangerous Goods ContactFinancial ContactGDS ContactGoods Receiving ContactInformation ContactInsurance ContactLicensee Registrar ContactLogistics ContactManager ContactNotification ContactOperations ContactOrder ContactPackaging EngineerProduct Management ContactProduct Recall Notification ContactPurchasing ContactQuality Coordinator ContactRecall Support ContactResponsible Person For Computer Data ProcessingReturn Authority ContactSales AdministrationSales Representative or Department ContactShipping ContactTarget Market Information ProviderTechnical SupportTest ContactTransport Contact</value>
      <webElementGuid>f6549ed1-7282-424c-9816-0a8f3c279bd9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactTypeId&quot;)</value>
      <webElementGuid>1732cac8-8d40-4fe3-a493-8e9bc57dfb47</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='ContactTypeId']</value>
      <webElementGuid>992b0aca-b69b-4797-8c60-cd678bf6a853</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div/div[3]/select</value>
      <webElementGuid>08f200f3-4a35-45f5-aae7-a92f8c752419</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Type'])[2]/following::select[1]</value>
      <webElementGuid>195b0e84-589a-444a-972a-812ad26884a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Id'])[2]/following::select[1]</value>
      <webElementGuid>0699dd13-6cd2-40de-a4b2-c962b8bef203</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Status'])[4]/preceding::select[1]</value>
      <webElementGuid>3970b4df-d7fb-483b-a3ec-1c6ef3c7c95e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Active'])[2]/preceding::select[1]</value>
      <webElementGuid>873e9fec-7939-4adf-a23e-63c5be5ee837</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/select</value>
      <webElementGuid>fa645cde-ecf4-441d-ab1b-411fdcf14388</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'ContactTypeId' and @name = 'ContactTypeId' and (text() = 'Select Contact TypeAccounting ContactAccounts Payable ContactAccounts Receivable ContactAdministrative ContactAfter Business Hours ContactAgent ContactClaims ContactConsumer Support ContactCustomer RelationsCustomer Support ContactDangerous Goods ContactDelivery ContactDepartment Or Person Responsible for Processing Purchase OrderDepartment/Employee to Execute Export ProceduresDepartment/Employee to Execute Import ProceduresEmergency Dangerous Goods ContactFinancial ContactGDS ContactGoods Receiving ContactInformation ContactInsurance ContactLicensee Registrar ContactLogistics ContactManager ContactNotification ContactOperations ContactOrder ContactPackaging EngineerProduct Management ContactProduct Recall Notification ContactPurchasing ContactQuality Coordinator ContactRecall Support ContactResponsible Person For Computer Data ProcessingReturn Authority ContactSales AdministrationSales Representative or Department ContactShipping ContactTarget Market Information ProviderTechnical SupportTest ContactTransport Contact' or . = 'Select Contact TypeAccounting ContactAccounts Payable ContactAccounts Receivable ContactAdministrative ContactAfter Business Hours ContactAgent ContactClaims ContactConsumer Support ContactCustomer RelationsCustomer Support ContactDangerous Goods ContactDelivery ContactDepartment Or Person Responsible for Processing Purchase OrderDepartment/Employee to Execute Export ProceduresDepartment/Employee to Execute Import ProceduresEmergency Dangerous Goods ContactFinancial ContactGDS ContactGoods Receiving ContactInformation ContactInsurance ContactLicensee Registrar ContactLogistics ContactManager ContactNotification ContactOperations ContactOrder ContactPackaging EngineerProduct Management ContactProduct Recall Notification ContactPurchasing ContactQuality Coordinator ContactRecall Support ContactResponsible Person For Computer Data ProcessingReturn Authority ContactSales AdministrationSales Representative or Department ContactShipping ContactTarget Market Information ProviderTechnical SupportTest ContactTransport Contact')]</value>
      <webElementGuid>c08a260b-e839-48bc-8c13-8411bc69a76f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
