<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>ContactName</name>
   <tag></tag>
   <elementGuidId>07c3e32a-ef03-441f-846f-1f4c3a2f0843</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#ContactName</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='ContactName']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>77f7a8e0-a583-44b1-86e1-1d4000e6b4fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ContactName</value>
      <webElementGuid>9ffd7a73-8943-4739-9b6f-0eab638b3418</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row modal-input</value>
      <webElementGuid>ea100c72-62af-492c-bba5-bbe01c0065da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ContactName</value>
      <webElementGuid>e1c12dee-cd92-4c29-a64c-ce5ec3777641</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Contact Name</value>
      <webElementGuid>37abd6b3-2b27-4991-86f9-44bf42c5e985</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>d8661f78-b739-41d2-9cb1-9634ba65f8f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>clearspanmsg()</value>
      <webElementGuid>91d71bb2-c127-47eb-ad58-f5ea24e0bbb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a5ecff38-830f-43c4-8aee-bdf594fef79a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ContactName&quot;)</value>
      <webElementGuid>ffb0b63f-9eca-47c0-b11d-571072dd76dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='ContactName']</value>
      <webElementGuid>85edc030-3683-41ff-8bac-c32ce47443f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div[2]/div/input</value>
      <webElementGuid>c7501595-08dc-4a2d-ab97-501046f9130b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/input</value>
      <webElementGuid>fb7ca8f4-5cd2-4923-b6b3-a8baa20c05b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'ContactName' and @name = 'ContactName' and @placeholder = 'Enter Contact Name' and @type = 'text']</value>
      <webElementGuid>7caa4ed1-8e58-4f51-bcff-a92c9cc3e43c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
