<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Department</name>
   <tag></tag>
   <elementGuidId>9dc89702-93c8-4b9c-9de6-b3ac61be74aa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Department</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Department']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>145a8121-8c37-43f7-9936-0e244ddc1d61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Department</value>
      <webElementGuid>b65e3912-f7eb-47d4-98b5-aeb06d1ceb2b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row modal-input</value>
      <webElementGuid>7561f3d4-11b9-48d1-923f-a9d91a8c4ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Department Name</value>
      <webElementGuid>4d5dd460-dfbe-46f2-921a-c4183b352af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>a22fdbfc-b2e4-49da-b7fc-8510709cb29c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>clearspanmsg()</value>
      <webElementGuid>8933426b-1857-4108-9e0b-307be1b03a05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>4885b44a-c02b-4de9-bff8-d497434ab7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Department</value>
      <webElementGuid>5262b947-3900-4aee-a1ac-236a1269d289</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Department&quot;)</value>
      <webElementGuid>d3e18532-1fbb-4b5e-abad-7d8ebf16356c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Department']</value>
      <webElementGuid>97d8c097-1204-422f-801c-40bcc2079240</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div[2]/div[2]/input</value>
      <webElementGuid>4c818434-f461-45d2-88a9-75b30016c626</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div[2]/input</value>
      <webElementGuid>bafcc1e6-e38c-4d69-b05f-fd780de2b822</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Department' and @placeholder = 'Enter Department Name' and @type = 'text' and @name = 'Department']</value>
      <webElementGuid>9ed6e67e-6e9f-451d-9119-1de592df5bfe</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
