<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>FaxNumber</name>
   <tag></tag>
   <elementGuidId>a9005071-e985-4438-a58b-7533578109e9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#faxInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='faxInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d502af74-2def-41be-8b0d-90fa17e95260</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>faxInput</value>
      <webElementGuid>f27c2118-34e2-47f5-a3e7-becb98ed6fdf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>validateFaxNumber(event)</value>
      <webElementGuid>6cd72de2-cbd5-4b5f-b09c-b0544b196c96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row modal-input</value>
      <webElementGuid>ddd35595-6bb9-4ec1-9a47-82f0136914da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>a63d062a-7aec-4fc2-83b7-20be7d10142d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Fax Number</value>
      <webElementGuid>96034495-2db8-4f54-ac69-df7c3645b104</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0e7f1d85-7935-4455-b47f-5b316db2279d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>FaxNumber</value>
      <webElementGuid>91647f62-543e-43c1-865c-9918357c623f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;faxInput&quot;)</value>
      <webElementGuid>c1ca267a-0c5c-4e5b-960f-9f9fd4dd4dce</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='faxInput']</value>
      <webElementGuid>2ee896e0-7fc2-4fd6-8ff8-19f8fce36d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div[4]/div[2]/input</value>
      <webElementGuid>07b18645-f220-4e8d-9e9b-93cfd7a3a73d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div[2]/input</value>
      <webElementGuid>7f8f02f5-c9a3-4575-b54d-74397cc6c93e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'faxInput' and @placeholder = 'Enter Fax Number' and @type = 'text' and @name = 'FaxNumber']</value>
      <webElementGuid>2726e190-abf0-4432-a9e0-65a4a0fdc510</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
