<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>JobTitle</name>
   <tag></tag>
   <elementGuidId>819d92e4-d346-4128-8665-34e2e5c40bd8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#JobTitle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='JobTitle']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71028215-cd00-44e0-8ebf-deb19cf6bed7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>JobTitle</value>
      <webElementGuid>10b01254-483c-4160-ae75-904fc6189dd3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row modal-input</value>
      <webElementGuid>ada86762-3655-4c4e-8140-4c37265f1eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Job Title</value>
      <webElementGuid>e7bf4aa7-9db3-4957-9ac0-b1a046a2a4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>89c3edb3-d9c2-421c-97ba-d7ba2f07eed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>5fd92b6c-cc32-42b1-afe7-48ff1f8e99ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>JobTitle</value>
      <webElementGuid>9c2a345e-92b7-456c-b9e4-73f39b26f6ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;JobTitle&quot;)</value>
      <webElementGuid>4fd3ea16-6687-4035-b48d-d5b52bae86b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='JobTitle']</value>
      <webElementGuid>a2df08be-deaa-487e-bdab-f821f171cfb9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div[3]/div/input</value>
      <webElementGuid>e5b0d6d0-196d-4de4-9194-f36c4d9a5e21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>338a8751-53b8-4987-8b5e-acf6d3f0e2cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'JobTitle' and @placeholder = 'Enter Job Title' and @type = 'text' and @name = 'JobTitle']</value>
      <webElementGuid>1ede7cc4-4827-4018-8713-7a90867f2698</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
