<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>PhoneNumber</name>
   <tag></tag>
   <elementGuidId>a7f9e708-16e9-41c0-9628-e7b651e2c54a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#phoneNumberInput</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='phoneNumberInput']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ff1b7913-2f94-4956-aba0-438e8aa92d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row modal-input</value>
      <webElementGuid>29458b95-2085-4389-854f-7c93b78531ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>phoneNumberInput</value>
      <webElementGuid>86213191-c659-480a-aaef-f7a3e9e8d2c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>formatPhoneNumber()</value>
      <webElementGuid>20354086-e7f1-4d32-a84d-256d869180b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>33</value>
      <webElementGuid>257227e9-40bf-49d1-8654-cf11bdd56458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Phone Number</value>
      <webElementGuid>2157cacd-72b5-4346-b2a8-bf5e209a986f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27799872-4383-4232-b2ee-30fb396281ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PhoneNumber</value>
      <webElementGuid>a609fcc0-e43f-4371-b166-e63e012599bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;phoneNumberInput&quot;)</value>
      <webElementGuid>10198f36-2895-4c87-9202-56633f0a7c63</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='phoneNumberInput']</value>
      <webElementGuid>5844ecc4-d013-4de0-9d31-44727ba04b82</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div[4]/div/input</value>
      <webElementGuid>71b806ad-8bbb-4a27-b2d4-7909f2c061a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[4]/div/input</value>
      <webElementGuid>778c4c92-8833-4275-96cb-190838d73492</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'phoneNumberInput' and @placeholder = 'Enter Phone Number' and @type = 'text' and @name = 'PhoneNumber']</value>
      <webElementGuid>73d1a290-0e82-4c1e-8fc7-335e71aba271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
