<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Responsibility</name>
   <tag></tag>
   <elementGuidId>cc7d76bd-080e-47a6-9618-9424d3888771</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Responsibility</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Responsibility']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1395df5f-5d37-4bcf-b2a9-43737c5c5313</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Responsibility</value>
      <webElementGuid>4f7ce807-c316-470a-a84e-d60275ba49f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row modal-input</value>
      <webElementGuid>3a056c16-477e-4fda-82bb-0991e6ff02af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Responsibility</value>
      <webElementGuid>f0dbbceb-9fa3-4cdd-b972-2ea8dfd51aae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>70</value>
      <webElementGuid>e16eb56c-9ae4-4f2f-aeb0-053b985c8023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>7fb5317d-5f67-45fc-a5c0-e932ed4d5d47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Responsibility</value>
      <webElementGuid>4ed224bc-9367-45bc-b5eb-63bbbcefe884</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Responsibility&quot;)</value>
      <webElementGuid>4c121750-65aa-4faa-bb0e-bd1a873babb3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Responsibility']</value>
      <webElementGuid>e216f003-36b9-4c21-8d83-a796fe6237c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div[3]/div[2]/input</value>
      <webElementGuid>2c7e48d6-a2d1-442d-a70f-7d1fd2244eda</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/input</value>
      <webElementGuid>d7c1ba1b-d489-4604-8353-f2406acce6d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'Responsibility' and @placeholder = 'Enter Responsibility' and @type = 'text' and @name = 'Responsibility']</value>
      <webElementGuid>eb1c9dd3-78e3-415c-819b-dac7bd55f0c0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
