<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusInactive</name>
   <tag></tag>
   <elementGuidId>45d9bab6-42ce-4773-a031-6e4a8b8d72db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contactInactive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contactInactive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>367ad9d9-98c2-4d25-ada5-d266a7972b08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactInactive</value>
      <webElementGuid>4940e186-2225-40d7-aa50-5b0dd2232f7d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>2bdfbc1d-59e4-48cc-9883-e116edd132e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>2cd75974-b2e2-4b73-9a9e-e5b0476e4377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactStatus</value>
      <webElementGuid>3840cfab-c08c-4cdd-9d33-de58b090de71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>5a934b1d-2937-4da0-a10d-6c44963e42da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactInactive&quot;)</value>
      <webElementGuid>99f4b03c-b91e-4d7b-b9b7-b38e14f15293</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contactInactive']</value>
      <webElementGuid>a78eb18d-fb17-4371-9d81-9ffda434e650</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div/div[4]/div/div[2]/input</value>
      <webElementGuid>20cd20cb-d4f2-40d2-ab8b-971f84323338</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div[2]/input</value>
      <webElementGuid>09ee13f3-1c58-4d55-893e-f66972d463aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contactInactive' and @type = 'radio' and @name = 'contactStatus']</value>
      <webElementGuid>8e6676a4-6053-488f-a896-fd02efd5495f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
