<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>StatusActive</name>
   <tag></tag>
   <elementGuidId>78cc12d1-7407-4623-98bf-8d4bca6f5208</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#contactActive</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='contactActive']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bbca41ad-4de7-4500-8211-e79bca1a669b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>d048e20a-3bf0-4e3f-88b0-a8f468d91a7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>contactActive</value>
      <webElementGuid>a683964c-ed19-4836-858b-84ff4d33ee6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>7e2cb7a4-ec12-4016-9c3e-db069b311fef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contactStatus</value>
      <webElementGuid>7f2c38f9-ef1e-433b-8872-7b3ed7119dbc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>42aa2af5-009a-4e16-bd95-cea1c912901b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7184ea41-8da6-4632-88c8-4954af943336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The Active field is required.</value>
      <webElementGuid>6a8c6106-b92a-4ee8-9071-6dede3a04b09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;contactActive&quot;)</value>
      <webElementGuid>42c75f38-107f-49c4-bad6-3e49ab7aa592</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='contactActive']</value>
      <webElementGuid>0020e459-eff4-4629-a339-6a45750821fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div/div[4]/div/div/input</value>
      <webElementGuid>c8b4fe23-6a30-4ab6-a74c-b9ff6cf3e69b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/div/input</value>
      <webElementGuid>8dd5ce15-08c1-473f-8700-2594e94755df</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'contactActive' and @type = 'radio' and @name = 'contactStatus']</value>
      <webElementGuid>a7b1c91c-ed7a-45a6-a875-aa2c306c86fb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
