<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Account Details</name>
   <tag></tag>
   <elementGuidId>55a19a7e-f502-4b28-9b25-e0fd8f5c0724</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#account-fig</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='account-fig']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7fc8f381-7cf5-4f58-a2fe-954692c8de9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>account-fig</value>
      <webElementGuid>c9a549e9-57de-4c6a-b8a3-70de9b85df06</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dropdown-toggle text-decoration-none text-orange</value>
      <webElementGuid>8739d0eb-3bdf-4276-a7aa-372f6e1eb78b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>1491380a-b368-4e88-9a16-178780337604</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>cd678491-3817-4522-949a-7a5c3969c476</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>cd0ba053-5763-4690-9915-5c9b8b8c3d6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;navbar&quot;)/nav[@class=&quot;navbar navbar-light navbar-expand-md container&quot;]/div[@class=&quot;container-fluid p-0&quot;]/div[@id=&quot;navcol-1&quot;]/ul[@class=&quot;navbar-nav ml-auto header-links&quot;]/li[@class=&quot;nav-item mr-3 d-none d-md-block text-nowrap&quot;]/div[@class=&quot;dropdown&quot;]/a[@id=&quot;account-fig&quot;]</value>
      <webElementGuid>30b24c1e-d148-4bc5-9744-ef383b60b3ee</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='account-fig']</value>
      <webElementGuid>f72aff2b-5228-46a1-b7fb-30e39be86f4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='navcol-1']/ul/li[8]/div/a</value>
      <webElementGuid>29e8af60-5a92-4256-b2aa-c576b801a31d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, Test!'])[1]/following::a[1]</value>
      <webElementGuid>f0cb5999-67d4-4d81-982b-6113003f7a1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Us'])[1]/following::a[2]</value>
      <webElementGuid>0f505145-16a7-4bf5-9620-fa6d47ba8415</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Details'])[1]/preceding::a[1]</value>
      <webElementGuid>e051c5c9-4416-43e5-a621-a5c6985a51ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[1]/preceding::a[2]</value>
      <webElementGuid>b37c2daf-aafe-43c3-a304-31f2e7c05344</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#')]</value>
      <webElementGuid>b1de28f9-05e5-43ea-b927-ffbceaa6d5fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[8]/div/a</value>
      <webElementGuid>036939ce-efbf-43ac-bf35-fcef25501842</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'account-fig' and @href = '#']</value>
      <webElementGuid>bc9c51ee-f5b2-4112-aaae-eb28494e4478</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
