<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SaveConfirmPop-up</name>
   <tag></tag>
   <elementGuidId>36b73a11-b763-470e-8d1b-b38a1a3e617a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#modal-GetConfirmation > div.modal-dialog.modal-sl.modal-messageBox > div.modal-content</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='modal-GetConfirmation']/div/div</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>d5059ec9-1e49-401a-b973-abe9da99ee5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>modal-content</value>
      <webElementGuid>9441365c-14d4-4b75-87d5-519605038b3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> The Serial number source and Serial Number Template cannot be modified, after saving the serialization Profile.Do you want to continue?Cancel Confirm</value>
      <webElementGuid>11d760d6-bd55-4568-a1e2-0db973186971</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;modal-GetConfirmation&quot;)/div[@class=&quot;modal-dialog modal-sl modal-messageBox&quot;]/div[@class=&quot;modal-content&quot;]</value>
      <webElementGuid>0208b6e1-791f-42b9-9150-5cec9fdee2b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-GetConfirmation']/div/div</value>
      <webElementGuid>f7e9fd58-80a4-4256-aa44-5f0348ba9c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[3]/following::div[3]</value>
      <webElementGuid>350f2da6-7071-42fa-ae4e-dd26468f52d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='OK'])[2]/following::div[11]</value>
      <webElementGuid>d86136b5-420f-4c7c-b1bb-e5dfb4bef915</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[4]/div/div</value>
      <webElementGuid>529edc51-3589-43e6-ae9b-9b1603c1ca98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = ' The Serial number source and Serial Number Template cannot be modified, after saving the serialization Profile.Do you want to continue?Cancel Confirm' or . = ' The Serial number source and Serial Number Template cannot be modified, after saving the serialization Profile.Do you want to continue?Cancel Confirm')]</value>
      <webElementGuid>59f33737-8128-490b-ba16-c45f6bb85b13</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
