<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address PostalCode</name>
   <tag></tag>
   <elementGuidId>ebfe886f-0816-40e2-a73d-bb062465aa2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partyAddress.PostalCode[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4af1be80-4f9f-43e2-9351-a15f8804a70b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partyAddress.PostalCode[0]</value>
      <webElementGuid>c085f851-35d7-4e30-a117-be1d56e92969</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>allowNumericInput(event)</value>
      <webElementGuid>9a0619d1-5eb3-40a6-b0ef-0895222540fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-sss ml-2 partypostal</value>
      <webElementGuid>62075aad-8d7a-4008-93d3-93c9e1c174e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Postal Code</value>
      <webElementGuid>374f4f35-bdd8-41bd-801a-1ec109cae839</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>e8fc35f0-6387-4c6e-aaa3-182c4fc0b790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>47076bfa-84ba-4738-a7ec-50201ac64779</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.PartyAddress.PostalCode</value>
      <webElementGuid>b5cca0be-5b67-40ac-af62-d1452da2b35a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partyAddress.PostalCode[0]&quot;)</value>
      <webElementGuid>561f40a6-b958-470c-880b-2f8d51c7ee77</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partyAddress.PostalCode[0]']</value>
      <webElementGuid>fa9a10ee-29b1-4181-8b21-39d59410dca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basedonclassificationhidediv']/div[2]/div[5]/div[2]/div/div[2]/input</value>
      <webElementGuid>287872da-3b77-46e4-90aa-071ec64883e0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div[2]/div/div[2]/input</value>
      <webElementGuid>0560f0c8-e411-4dee-b0a6-680d47011497</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partyAddress.PostalCode[0]' and @placeholder = 'Enter Postal Code' and @type = 'text' and @name = 'item.PartyAddress.PostalCode']</value>
      <webElementGuid>ad617174-2f30-47a4-83ce-5ad668a3a51a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
