<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address Country</name>
   <tag></tag>
   <elementGuidId>ab6c4a43-e886-40b4-999f-c1bcffcc1d2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name = 'item.PartyAddress.CountryId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>1b3728c4-897d-4b46-b8f3-504a23722816</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partyAddress.countryDropdown[0]</value>
      <webElementGuid>6e5e584b-e05b-4332-87c7-82c17895a115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms partybasicinfoinput</value>
      <webElementGuid>73a98d1c-c972-4851-af17-9f1d9ae656da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trigger</name>
      <type>Main</type>
      <value>partyAddress.stateDropdown[0]</value>
      <webElementGuid>132b8e56-16e1-487d-8105-890995dd2288</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>#states-loading-progress</value>
      <webElementGuid>5cab2d7e-7202-49f9-857e-45bc3de61c31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>aa88e7a3-9229-41b3-bc13-10fe189f3354</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The CountryId field is required.</value>
      <webElementGuid>d21268b2-716b-494a-98dc-af2201c269ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.PartyAddress.CountryId</value>
      <webElementGuid>71b00c2d-834e-4153-9d45-37cc5e0beb17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a countryUS - United States of AmericaAF - AfghanistanAX - Åland IslandsAL - AlbaniaDZ - AlgeriaAS - American SamoaAD - AndorraAO - AngolaAI - AnguillaAQ - AntarcticaAG - Antigua and BarbudaAR - ArgentinaAM - ArmeniaAW - ArubaAU - AustraliaAT - AustriaAZ - AzerbaijanBS - BahamasBH - BahrainBD - BangladeshBB - BarbadosBY - BelarusBE - BelgiumBZ - BelizeBJ - BeninBM - BermudaBT - BhutanBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBA - Bosnia and HerzegovinaBW - BotswanaBV - Bouvet IslandBR - BrazilIO - British Indian Ocean TerritoryBN - Brunei DarussalamBG - BulgariaBF - Burkina FasoBI - BurundiCV - Cabo VerdeKH - CambodiaCM - CameroonCA - CanadaKY - Cayman IslandsCF - Central African RepublicTD - ChadCL - ChileCN - ChinaCX - Christmas IslandCC - Cocos (Keeling) IslandsCO - ColombiaKM - ComorosCG - CongoCD - Congo (Democratic Republic of the)CK - Cook IslandsCR - Costa RicaCI - Côte d'IvoireHR - CroatiaCU - CubaCW - CuraçaoCY - CyprusCZ - CzechiaDK - DenmarkDJ - DjiboutiDM - DominicaDO - Dominican RepublicEC - EcuadorEG - EgyptSV - El SalvadorGQ - Equatorial GuineaER - EritreaEE - EstoniaSZ - EswatiniET - EthiopiaFK - Falkland Islands (Malvinas)FO - Faroe IslandsFJ - FijiFI - FinlandFR - FranceGF - French GuianaPF - French PolynesiaTF - French Southern TerritoriesGA - GabonGM - GambiaGE - GeorgiaDE - GermanyGH - GhanaGI - GibraltarGR - GreeceGL - GreenlandGD - GrenadaGP - GuadeloupeGU - GuamGT - GuatemalaGG - GuernseyGN - GuineaGW - Guinea-BissauGY - GuyanaHT - HaitiHM - Heard Island and McDonald IslandsVA - Holy SeeHN - HondurasHK - Hong KongHU - HungaryIS - IcelandIN - IndiaID - IndonesiaIR - Iran (Islamic Republic of)IQ - IraqIE - IrelandIM - Isle of ManIL - IsraelIT - ItalyJM - JamaicaJP - JapanJE - JerseyJO - JordanKZ - KazakhstanKE - KenyaKI - KiribatiKP - Korea (Democratic People's Republic of)KR - Korea (Republic of)KW - KuwaitKG - KyrgyzstanLA - Lao People's Democratic RepublicLV - LatviaLB - LebanonLS - LesothoLR - LiberiaLY - LibyaLI - LiechtensteinLT - LithuaniaLU - LuxembourgMO - MacaoMG - MadagascarMW - MalawiMY - MalaysiaMV - MaldivesML - MaliMT - MaltaMH - Marshall IslandsMQ - MartiniqueMR - MauritaniaMU - MauritiusYT - MayotteMX - MexicoFM - Micronesia (Federated States of)MD - Moldova (Republic of)MC - MonacoMN - MongoliaME - MontenegroMS - MontserratMA - MoroccoMZ - MozambiqueMM - MyanmarNA - NamibiaNR - NauruNP - NepalNL - NetherlandsNC - New CaledoniaNZ - New ZealandNI - NicaraguaNE - NigerNG - NigeriaNU - NiueNF - Norfolk IslandMK - North MacedoniaMP - Northern Mariana IslandsNO - NorwayOM - OmanPK - PakistanPW - PalauPS - Palestine, State ofPA - PanamaPG - Papua New GuineaPY - ParaguayPE - PeruPH - PhilippinesPN - PitcairnPL - PolandPT - PortugalPR - Puerto RicoQA - QatarRE - RéunionRO - RomaniaRU - Russian FederationRW - RwandaBL - Saint BarthélemySH - Saint Helena, Ascension and Tristan da CunhaKN - Saint Kitts and NevisLC - Saint LuciaMF - Saint Martin (French part)PM - Saint Pierre and MiquelonVC - Saint Vincent and the GrenadinesWS - SamoaSP - San MarinoST - Sao Tome and PrincipeSA - Saudi ArabiaSN - SenegalRS - SerbiaSC - SeychellesSL - Sierra LeoneSG - SingaporeSX - Sint Maarten (Dutch part)SK - SlovakiaSI - SloveniaSB - Solomon IslandsSO - SomaliaZA - South AfricaGS - South Georgia and the South Sandwich IslandsSS - South SudanES - SpainLK - Sri LankaSD - SudanSR - SurinameSJ - Svalbard and Jan MayenSE - SwedenCH - SwitzerlandSY - Syrian Arab RepublicTW - Taiwan, Province of ChinaTJ - TajikistanTZ - Tanzania, United Republic ofTH - ThailandTL - Timor-LesteTG - TogoTK - TokelauTO - TongaTT - Trinidad and TobagoTN - TunisiaTR - TurkeyTM - TurkmenistanTC - Turks and Caicos IslandsTV - TuvaluUG - UgandaUA - UkraineAE - United Arab EmiratesGB - United Kingdom of Great Britain and Northern IrelandUM - United States Minor Outlying IslandsUY - UruguayUZ - UzbekistanVU - VanuatuVE - Venezuela (Bolivarian Republic of)VN - VietnamVG - Virgin Islands (British)VI - Virgin Islands (U.S.)WF - Wallis and FutunaEH - Western SaharaYE - YemenZM - ZambiaZW - Zimbabwe</value>
      <webElementGuid>dc8f2605-aee0-417b-8c98-259dcb41409e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partyAddress.countryDropdown[0]&quot;)</value>
      <webElementGuid>4e464a76-fcfe-4d7a-a4b0-9e627178b950</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='partyAddress.countryDropdown[0]']</value>
      <webElementGuid>ccd714fd-cdde-4c62-a52a-0f1556d63318</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basedonclassificationhidediv']/div[2]/div[2]/div/select</value>
      <webElementGuid>e9093f12-796b-481d-93b8-5c350b2d6724</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[1]</value>
      <webElementGuid>08a846e1-07d3-4ee8-b9e1-b08c3f53c394</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::select[1]</value>
      <webElementGuid>c8d5a1f8-b30c-40d6-b8f2-efd282184f7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 1'])[1]/preceding::select[1]</value>
      <webElementGuid>a88381dd-a8f1-490b-9998-8a7a264c54f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 2'])[1]/preceding::select[1]</value>
      <webElementGuid>0531cf23-456a-4132-9231-04e8da3fb9e2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/select</value>
      <webElementGuid>6603f73f-40bb-420e-b717-be729f6865d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'partyAddress.countryDropdown[0]' and @name = 'item.PartyAddress.CountryId' and (text() = concat(&quot;Select a countryUS - United States of AmericaAF - AfghanistanAX - Åland IslandsAL - AlbaniaDZ - AlgeriaAS - American SamoaAD - AndorraAO - AngolaAI - AnguillaAQ - AntarcticaAG - Antigua and BarbudaAR - ArgentinaAM - ArmeniaAW - ArubaAU - AustraliaAT - AustriaAZ - AzerbaijanBS - BahamasBH - BahrainBD - BangladeshBB - BarbadosBY - BelarusBE - BelgiumBZ - BelizeBJ - BeninBM - BermudaBT - BhutanBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBA - Bosnia and HerzegovinaBW - BotswanaBV - Bouvet IslandBR - BrazilIO - British Indian Ocean TerritoryBN - Brunei DarussalamBG - BulgariaBF - Burkina FasoBI - BurundiCV - Cabo VerdeKH - CambodiaCM - CameroonCA - CanadaKY - Cayman IslandsCF - Central African RepublicTD - ChadCL - ChileCN - ChinaCX - Christmas IslandCC - Cocos (Keeling) IslandsCO - ColombiaKM - ComorosCG - CongoCD - Congo (Democratic Republic of the)CK - Cook IslandsCR - Costa RicaCI - Côte d&quot; , &quot;'&quot; , &quot;IvoireHR - CroatiaCU - CubaCW - CuraçaoCY - CyprusCZ - CzechiaDK - DenmarkDJ - DjiboutiDM - DominicaDO - Dominican RepublicEC - EcuadorEG - EgyptSV - El SalvadorGQ - Equatorial GuineaER - EritreaEE - EstoniaSZ - EswatiniET - EthiopiaFK - Falkland Islands (Malvinas)FO - Faroe IslandsFJ - FijiFI - FinlandFR - FranceGF - French GuianaPF - French PolynesiaTF - French Southern TerritoriesGA - GabonGM - GambiaGE - GeorgiaDE - GermanyGH - GhanaGI - GibraltarGR - GreeceGL - GreenlandGD - GrenadaGP - GuadeloupeGU - GuamGT - GuatemalaGG - GuernseyGN - GuineaGW - Guinea-BissauGY - GuyanaHT - HaitiHM - Heard Island and McDonald IslandsVA - Holy SeeHN - HondurasHK - Hong KongHU - HungaryIS - IcelandIN - IndiaID - IndonesiaIR - Iran (Islamic Republic of)IQ - IraqIE - IrelandIM - Isle of ManIL - IsraelIT - ItalyJM - JamaicaJP - JapanJE - JerseyJO - JordanKZ - KazakhstanKE - KenyaKI - KiribatiKP - Korea (Democratic People&quot; , &quot;'&quot; , &quot;s Republic of)KR - Korea (Republic of)KW - KuwaitKG - KyrgyzstanLA - Lao People&quot; , &quot;'&quot; , &quot;s Democratic RepublicLV - LatviaLB - LebanonLS - LesothoLR - LiberiaLY - LibyaLI - LiechtensteinLT - LithuaniaLU - LuxembourgMO - MacaoMG - MadagascarMW - MalawiMY - MalaysiaMV - MaldivesML - MaliMT - MaltaMH - Marshall IslandsMQ - MartiniqueMR - MauritaniaMU - MauritiusYT - MayotteMX - MexicoFM - Micronesia (Federated States of)MD - Moldova (Republic of)MC - MonacoMN - MongoliaME - MontenegroMS - MontserratMA - MoroccoMZ - MozambiqueMM - MyanmarNA - NamibiaNR - NauruNP - NepalNL - NetherlandsNC - New CaledoniaNZ - New ZealandNI - NicaraguaNE - NigerNG - NigeriaNU - NiueNF - Norfolk IslandMK - North MacedoniaMP - Northern Mariana IslandsNO - NorwayOM - OmanPK - PakistanPW - PalauPS - Palestine, State ofPA - PanamaPG - Papua New GuineaPY - ParaguayPE - PeruPH - PhilippinesPN - PitcairnPL - PolandPT - PortugalPR - Puerto RicoQA - QatarRE - RéunionRO - RomaniaRU - Russian FederationRW - RwandaBL - Saint BarthélemySH - Saint Helena, Ascension and Tristan da CunhaKN - Saint Kitts and NevisLC - Saint LuciaMF - Saint Martin (French part)PM - Saint Pierre and MiquelonVC - Saint Vincent and the GrenadinesWS - SamoaSP - San MarinoST - Sao Tome and PrincipeSA - Saudi ArabiaSN - SenegalRS - SerbiaSC - SeychellesSL - Sierra LeoneSG - SingaporeSX - Sint Maarten (Dutch part)SK - SlovakiaSI - SloveniaSB - Solomon IslandsSO - SomaliaZA - South AfricaGS - South Georgia and the South Sandwich IslandsSS - South SudanES - SpainLK - Sri LankaSD - SudanSR - SurinameSJ - Svalbard and Jan MayenSE - SwedenCH - SwitzerlandSY - Syrian Arab RepublicTW - Taiwan, Province of ChinaTJ - TajikistanTZ - Tanzania, United Republic ofTH - ThailandTL - Timor-LesteTG - TogoTK - TokelauTO - TongaTT - Trinidad and TobagoTN - TunisiaTR - TurkeyTM - TurkmenistanTC - Turks and Caicos IslandsTV - TuvaluUG - UgandaUA - UkraineAE - United Arab EmiratesGB - United Kingdom of Great Britain and Northern IrelandUM - United States Minor Outlying IslandsUY - UruguayUZ - UzbekistanVU - VanuatuVE - Venezuela (Bolivarian Republic of)VN - VietnamVG - Virgin Islands (British)VI - Virgin Islands (U.S.)WF - Wallis and FutunaEH - Western SaharaYE - YemenZM - ZambiaZW - Zimbabwe&quot;) or . = concat(&quot;Select a countryUS - United States of AmericaAF - AfghanistanAX - Åland IslandsAL - AlbaniaDZ - AlgeriaAS - American SamoaAD - AndorraAO - AngolaAI - AnguillaAQ - AntarcticaAG - Antigua and BarbudaAR - ArgentinaAM - ArmeniaAW - ArubaAU - AustraliaAT - AustriaAZ - AzerbaijanBS - BahamasBH - BahrainBD - BangladeshBB - BarbadosBY - BelarusBE - BelgiumBZ - BelizeBJ - BeninBM - BermudaBT - BhutanBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBA - Bosnia and HerzegovinaBW - BotswanaBV - Bouvet IslandBR - BrazilIO - British Indian Ocean TerritoryBN - Brunei DarussalamBG - BulgariaBF - Burkina FasoBI - BurundiCV - Cabo VerdeKH - CambodiaCM - CameroonCA - CanadaKY - Cayman IslandsCF - Central African RepublicTD - ChadCL - ChileCN - ChinaCX - Christmas IslandCC - Cocos (Keeling) IslandsCO - ColombiaKM - ComorosCG - CongoCD - Congo (Democratic Republic of the)CK - Cook IslandsCR - Costa RicaCI - Côte d&quot; , &quot;'&quot; , &quot;IvoireHR - CroatiaCU - CubaCW - CuraçaoCY - CyprusCZ - CzechiaDK - DenmarkDJ - DjiboutiDM - DominicaDO - Dominican RepublicEC - EcuadorEG - EgyptSV - El SalvadorGQ - Equatorial GuineaER - EritreaEE - EstoniaSZ - EswatiniET - EthiopiaFK - Falkland Islands (Malvinas)FO - Faroe IslandsFJ - FijiFI - FinlandFR - FranceGF - French GuianaPF - French PolynesiaTF - French Southern TerritoriesGA - GabonGM - GambiaGE - GeorgiaDE - GermanyGH - GhanaGI - GibraltarGR - GreeceGL - GreenlandGD - GrenadaGP - GuadeloupeGU - GuamGT - GuatemalaGG - GuernseyGN - GuineaGW - Guinea-BissauGY - GuyanaHT - HaitiHM - Heard Island and McDonald IslandsVA - Holy SeeHN - HondurasHK - Hong KongHU - HungaryIS - IcelandIN - IndiaID - IndonesiaIR - Iran (Islamic Republic of)IQ - IraqIE - IrelandIM - Isle of ManIL - IsraelIT - ItalyJM - JamaicaJP - JapanJE - JerseyJO - JordanKZ - KazakhstanKE - KenyaKI - KiribatiKP - Korea (Democratic People&quot; , &quot;'&quot; , &quot;s Republic of)KR - Korea (Republic of)KW - KuwaitKG - KyrgyzstanLA - Lao People&quot; , &quot;'&quot; , &quot;s Democratic RepublicLV - LatviaLB - LebanonLS - LesothoLR - LiberiaLY - LibyaLI - LiechtensteinLT - LithuaniaLU - LuxembourgMO - MacaoMG - MadagascarMW - MalawiMY - MalaysiaMV - MaldivesML - MaliMT - MaltaMH - Marshall IslandsMQ - MartiniqueMR - MauritaniaMU - MauritiusYT - MayotteMX - MexicoFM - Micronesia (Federated States of)MD - Moldova (Republic of)MC - MonacoMN - MongoliaME - MontenegroMS - MontserratMA - MoroccoMZ - MozambiqueMM - MyanmarNA - NamibiaNR - NauruNP - NepalNL - NetherlandsNC - New CaledoniaNZ - New ZealandNI - NicaraguaNE - NigerNG - NigeriaNU - NiueNF - Norfolk IslandMK - North MacedoniaMP - Northern Mariana IslandsNO - NorwayOM - OmanPK - PakistanPW - PalauPS - Palestine, State ofPA - PanamaPG - Papua New GuineaPY - ParaguayPE - PeruPH - PhilippinesPN - PitcairnPL - PolandPT - PortugalPR - Puerto RicoQA - QatarRE - RéunionRO - RomaniaRU - Russian FederationRW - RwandaBL - Saint BarthélemySH - Saint Helena, Ascension and Tristan da CunhaKN - Saint Kitts and NevisLC - Saint LuciaMF - Saint Martin (French part)PM - Saint Pierre and MiquelonVC - Saint Vincent and the GrenadinesWS - SamoaSP - San MarinoST - Sao Tome and PrincipeSA - Saudi ArabiaSN - SenegalRS - SerbiaSC - SeychellesSL - Sierra LeoneSG - SingaporeSX - Sint Maarten (Dutch part)SK - SlovakiaSI - SloveniaSB - Solomon IslandsSO - SomaliaZA - South AfricaGS - South Georgia and the South Sandwich IslandsSS - South SudanES - SpainLK - Sri LankaSD - SudanSR - SurinameSJ - Svalbard and Jan MayenSE - SwedenCH - SwitzerlandSY - Syrian Arab RepublicTW - Taiwan, Province of ChinaTJ - TajikistanTZ - Tanzania, United Republic ofTH - ThailandTL - Timor-LesteTG - TogoTK - TokelauTO - TongaTT - Trinidad and TobagoTN - TunisiaTR - TurkeyTM - TurkmenistanTC - Turks and Caicos IslandsTV - TuvaluUG - UgandaUA - UkraineAE - United Arab EmiratesGB - United Kingdom of Great Britain and Northern IrelandUM - United States Minor Outlying IslandsUY - UruguayUZ - UzbekistanVU - VanuatuVE - Venezuela (Bolivarian Republic of)VN - VietnamVG - Virgin Islands (British)VI - Virgin Islands (U.S.)WF - Wallis and FutunaEH - Western SaharaYE - YemenZM - ZambiaZW - Zimbabwe&quot;))]</value>
      <webElementGuid>64f6156d-3fc9-42aa-82cc-78d2ddb88218</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
