<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address Line 1</name>
   <tag></tag>
   <elementGuidId>b35304d8-dd19-47b9-9607-5906e9391fa7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@id,'AddressLine1')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0a979ad0-e184-4342-b232-323d3468fe61</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partyAddress.AddressLine1[0]</value>
      <webElementGuid>dc32dff0-1a37-434f-b52e-c656a083d05a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ls</value>
      <webElementGuid>25f63a02-ffd2-4577-85a5-adf646e02e4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Address Line 1</value>
      <webElementGuid>28fb94ef-f0ee-42db-b19e-7b70762b2f6d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>bf49c878-a0f8-4317-88b8-6ab10b050fab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>27c167e1-5b1b-423a-b08d-82745a659c03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.PartyAddress.AddressLine1</value>
      <webElementGuid>446fb7c5-7b2f-4a67-a860-a7ce2a5edaa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partyAddress.AddressLine1[0]&quot;)</value>
      <webElementGuid>8961fb49-bc0e-4d61-9dd8-bff1c552d72b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partyAddress.AddressLine1[0]']</value>
      <webElementGuid>b1f60e84-f0cd-45d1-8a11-7c6d90c66742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basedonclassificationhidediv']/div[2]/div[3]/div/input</value>
      <webElementGuid>82b9f34a-d786-4ac5-960d-6e349d277b51</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[3]/div/input</value>
      <webElementGuid>6c9aecd4-c978-4e0c-8ca0-72d9429d2596</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partyAddress.AddressLine1[0]' and @placeholder = 'Enter Address Line 1' and @type = 'text' and @name = 'item.PartyAddress.AddressLine1']</value>
      <webElementGuid>357c7308-911f-4c1d-aa47-2156f18c00ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
