<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address Line 2</name>
   <tag></tag>
   <elementGuidId>4cd68cb7-6f33-4dc5-bca3-d6aec4156fe5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[contains(@name,'AddressLine2')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>342b0c7a-dae7-41d4-b1b5-422ad104d6a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partyAddress.AdderssLine2[0]</value>
      <webElementGuid>5b63e0d1-2f3d-46f9-8156-0ff43bf8f6d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms partybasicinfoinput</value>
      <webElementGuid>fd753b7f-dd0f-43ed-b222-bfc258988b39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Address Line 2</value>
      <webElementGuid>d88ddb05-dfd1-4e84-b93c-6ca894bb9b62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>80</value>
      <webElementGuid>a86970c4-71d0-4a1c-a662-e76304431230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>16a00817-1d39-40d2-9c8c-ad9b6912f010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.PartyAddress.AddressLine2</value>
      <webElementGuid>3c36393e-98ba-4176-9e0f-0134f5e89da9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partyAddress.AdderssLine2[0]&quot;)</value>
      <webElementGuid>a476995e-595e-4b6a-99fb-8f9b05a06f5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partyAddress.AdderssLine2[0]']</value>
      <webElementGuid>b9531d76-e1c5-4651-918b-863d242d13e8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basedonclassificationhidediv']/div[2]/div[4]/div/input</value>
      <webElementGuid>3ec7a915-b147-4ac2-bb13-ab8cbfca28b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[4]/div/input</value>
      <webElementGuid>908d2d23-825c-4bad-acec-356b69bb374e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partyAddress.AdderssLine2[0]' and @placeholder = 'Enter Address Line 2' and @type = 'text' and @name = 'item.PartyAddress.AddressLine2']</value>
      <webElementGuid>bfc33659-20cd-48e8-a0f4-45ed54cccff7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
