<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address State</name>
   <tag></tag>
   <elementGuidId>ad14796f-6dcb-462c-bd4c-8b80a81e3dd5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name = 'item.PartyAddress.StateId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>49ca33cb-3dab-43e9-9b7b-dc5bdb8a4581</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partyAddress.stateDropdown[0]</value>
      <webElementGuid>7a9d2e06-d37c-4b5a-80e7-73ab8b2c8ebb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ss ml-0</value>
      <webElementGuid>b98851c7-9492-4875-9f49-d4af0231d74c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trigger</name>
      <type>Main</type>
      <value>state-select</value>
      <webElementGuid>f9589633-551e-4688-8259-de31ee53fdd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>44707191-8462-40fd-ac06-86f9d938e41f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The StateId field is required.</value>
      <webElementGuid>bd4d9d4f-bffd-49a6-b2c0-23a21b395690</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.PartyAddress.StateId</value>
      <webElementGuid>2589f59c-f326-4c98-9667-4c8275eedb8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select StateAA - AA (Armed Forces Americas)AE - AE (Armed Forces Europe)AL - AlabamaAK - AlaskaAS - American SamoaAP - AP (Armed Forces Pacific)AZ - ArizonaAR - ArkansasCA - CaliforniaCO - ColoradoCT - ConnecticutDE - DelawareDC - District of ColumbiaFM - Federated States of MicronesiaFL - FloridaGA - GeorgiaGU - GuamHI - HawaiiID - IdahoIL - IllinoisIN - IndianaIA - IowaKS - KansasKY - KentuckyLA - LouisianaME - MaineMH - Marshall IslandsMD - MarylandMA - MassachusettsMI - MichiganMN - MinnesotaMS - MississippiMO - MissouriMT - MontanaNE - NebraskaNV - NevadaNH - New HampshireNJ - New JerseyNM - New MexicoNY - New YorkNC - North CarolinaND - North DakotaMP - Northern Mariana IslandsOH - OhioOK - OklahomaOR - OregonPW - PalauPA - PennsylvaniaPR - Puerto RicoRI - Rhode IslandSC - South CarolinaSD - South DakotaTN - TennesseeTX - TexasUT - UtahVT - VermontVI - Virgin IslandsVA - VirginiaWA - WashingtonWV - West VirginiaWI - WisconsinWY - Wyoming</value>
      <webElementGuid>8707c4f5-8921-401f-8dc2-3e3be1402ca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partyAddress.stateDropdown[0]&quot;)</value>
      <webElementGuid>47949f18-cbc4-48be-a7f0-bbcc4ae55b92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='partyAddress.stateDropdown[0]']</value>
      <webElementGuid>18af5f1f-313d-4f10-8fe8-12c4012dc97f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='basedonclassificationhidediv']/div[2]/div[5]/div[2]/div/div/select</value>
      <webElementGuid>d057e47b-7660-4cd8-82ab-0c219768a516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='State/Region'])[1]/following::select[1]</value>
      <webElementGuid>01535599-995b-4246-abbb-542ad5e6f3d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='City'])[1]/following::select[1]</value>
      <webElementGuid>646bae03-1db0-4512-a2b3-b60ac861c97a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Postal Code'])[1]/preceding::select[1]</value>
      <webElementGuid>57495759-5c78-48ae-b4a9-8ef3789598ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Additional Address Details'])[1]/preceding::select[1]</value>
      <webElementGuid>2d2891b2-03e2-4b63-8fe2-a167b056d365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[5]/div[2]/div/div/select</value>
      <webElementGuid>6fb86de1-f1fe-473f-9c93-6473d5dd3fba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'partyAddress.stateDropdown[0]' and @name = 'item.PartyAddress.StateId' and (text() = 'Select StateAA - AA (Armed Forces Americas)AE - AE (Armed Forces Europe)AL - AlabamaAK - AlaskaAS - American SamoaAP - AP (Armed Forces Pacific)AZ - ArizonaAR - ArkansasCA - CaliforniaCO - ColoradoCT - ConnecticutDE - DelawareDC - District of ColumbiaFM - Federated States of MicronesiaFL - FloridaGA - GeorgiaGU - GuamHI - HawaiiID - IdahoIL - IllinoisIN - IndianaIA - IowaKS - KansasKY - KentuckyLA - LouisianaME - MaineMH - Marshall IslandsMD - MarylandMA - MassachusettsMI - MichiganMN - MinnesotaMS - MississippiMO - MissouriMT - MontanaNE - NebraskaNV - NevadaNH - New HampshireNJ - New JerseyNM - New MexicoNY - New YorkNC - North CarolinaND - North DakotaMP - Northern Mariana IslandsOH - OhioOK - OklahomaOR - OregonPW - PalauPA - PennsylvaniaPR - Puerto RicoRI - Rhode IslandSC - South CarolinaSD - South DakotaTN - TennesseeTX - TexasUT - UtahVT - VermontVI - Virgin IslandsVA - VirginiaWA - WashingtonWV - West VirginiaWI - WisconsinWY - Wyoming' or . = 'Select StateAA - AA (Armed Forces Americas)AE - AE (Armed Forces Europe)AL - AlabamaAK - AlaskaAS - American SamoaAP - AP (Armed Forces Pacific)AZ - ArizonaAR - ArkansasCA - CaliforniaCO - ColoradoCT - ConnecticutDE - DelawareDC - District of ColumbiaFM - Federated States of MicronesiaFL - FloridaGA - GeorgiaGU - GuamHI - HawaiiID - IdahoIL - IllinoisIN - IndianaIA - IowaKS - KansasKY - KentuckyLA - LouisianaME - MaineMH - Marshall IslandsMD - MarylandMA - MassachusettsMI - MichiganMN - MinnesotaMS - MississippiMO - MissouriMT - MontanaNE - NebraskaNV - NevadaNH - New HampshireNJ - New JerseyNM - New MexicoNY - New YorkNC - North CarolinaND - North DakotaMP - Northern Mariana IslandsOH - OhioOK - OklahomaOR - OregonPW - PalauPA - PennsylvaniaPR - Puerto RicoRI - Rhode IslandSC - South CarolinaSD - South DakotaTN - TennesseeTX - TexasUT - UtahVT - VermontVI - Virgin IslandsVA - VirginiaWA - WashingtonWV - West VirginiaWI - WisconsinWY - Wyoming')]</value>
      <webElementGuid>61522180-b08d-4bde-8237-bf740cef7236</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
