<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Digital Address</name>
   <tag></tag>
   <elementGuidId>c6e988ba-76e8-45f8-8375-aa7a20a630f2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='digitaladdress']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#digitaladdress</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>483393d7-d433-4fc0-86c8-8be5e3987d4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>digitaladdress</value>
      <webElementGuid>a0dc0135-f3d4-4f7d-91a8-df601ac43588</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>199e6273-d9a5-42ee-b6dd-7afed544ed3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Digital Address</value>
      <webElementGuid>0715ab22-a619-4683-9a75-e45a31f5f4ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>42f1d759-4a6e-4216-95c3-7c9bd29b218c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>b27a32bb-fa23-425d-a4be-46ac0456cb67</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocationBasicInfo.DigitalAddress</value>
      <webElementGuid>ffe93f20-4962-4bac-a019-bc00c880661e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;digitaladdress&quot;)</value>
      <webElementGuid>e5e8a1d4-d3ff-4bb4-8183-06b4981ae0b0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='digitaladdress']</value>
      <webElementGuid>f7837de4-f0ca-4eb4-bb2a-d8440f2e0c23</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='digitlhidediv']/div/input</value>
      <webElementGuid>6aaf5e6a-b3f1-4a1a-8563-cf592adc5d45</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>7e04199b-9579-4a91-b9d5-756e6cd1c9c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'digitaladdress' and @placeholder = 'Enter Digital Address' and @type = 'text' and @name = 'LocationBasicInfo.DigitalAddress']</value>
      <webElementGuid>c77f5305-302e-410d-a07b-6131e70dc23f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
