<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GCP Length</name>
   <tag></tag>
   <elementGuidId>3dd5641b-88a1-42f0-b453-c179aa5c7be8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@name = 'PartyGLN.GS1CompanyPrefixLength']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#gscompanyprefixlengthddl</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>2cc0746d-31ac-4c01-a3e8-a8af088b4184</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>gscompanyprefixlengthddl</value>
      <webElementGuid>38a0aef6-43f6-4d86-bf70-40be3f9d6a28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms ml-0</value>
      <webElementGuid>dae4c5e5-8ff4-47e6-b7d3-2ab986dc6385</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>gcplengthbasesgln()</value>
      <webElementGuid>c2a8487c-0d8e-4e59-9aba-7095931482a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5f10d834-eb30-4f99-88b6-cd546818f0f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The GS1CompanyPrefixLength field is required.</value>
      <webElementGuid>85361527-f834-4132-ab3b-c9d66af5d073</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyGLN.GS1CompanyPrefixLength</value>
      <webElementGuid>3e51ab37-b52e-49d2-a354-6df150552865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select GCP Length4567891011</value>
      <webElementGuid>20a38c66-6cf7-47a3-a9a1-562efff1beba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gscompanyprefixlengthddl&quot;)</value>
      <webElementGuid>2a7cf7aa-d29e-4bd1-a8d3-7cebc645431e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='gscompanyprefixlengthddl']</value>
      <webElementGuid>10099af9-f0e7-4182-b384-9b9679c52b54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='glnModel']/div/div[2]/select</value>
      <webElementGuid>334029aa-7778-48ce-8da9-3703d6f5941e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GS1 Company Prefix Length'])[1]/following::select[1]</value>
      <webElementGuid>8eb42508-512d-448e-b346-fd90cef9719a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLN should be 13 digits'])[1]/following::select[1]</value>
      <webElementGuid>a94a7796-4576-455b-b8e3-d0d089034d30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='GLN Extension'])[1]/preceding::select[1]</value>
      <webElementGuid>dcc005b2-5cd8-488f-b834-df5d99f59e54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SGLN'])[1]/preceding::select[1]</value>
      <webElementGuid>ef6068c5-724d-4b81-964e-2945c302961b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>0c26d0a1-8ea6-4e74-9e73-9a12787f1001</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'gscompanyprefixlengthddl' and @name = 'PartyGLN.GS1CompanyPrefixLength' and (text() = 'Select GCP Length4567891011' or . = 'Select GCP Length4567891011')]</value>
      <webElementGuid>27da4e1b-b099-446e-a04b-9610127faa34</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
