<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>GLN Extension</name>
   <tag></tag>
   <elementGuidId>49b41e2c-95cb-4aa0-a93f-ba62572bcca4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='PartyGLN_GLNExtension']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PartyGLN_GLNExtension</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>8a8c173b-090c-40ef-a083-6a4fe34b01f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PartyGLN_GLNExtension</value>
      <webElementGuid>4485eb6e-8a7f-4ce7-8eee-a4a3afecc905</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>08ca3608-9eda-4da5-bc38-4dfd92829bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter GLN Extension</value>
      <webElementGuid>4426b673-d1f2-43e2-be25-1d16227cc116</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>sglnsystemgenerated()</value>
      <webElementGuid>d7617df8-7c6f-4034-b7be-8d9d2eca2ea2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>896a9840-73d8-4beb-86db-1fe469706d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>9654238b-d784-4ce1-985d-00c49a930336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>80e62721-501d-4ab3-bfa3-b792d408d68e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>GLN Extension is required</value>
      <webElementGuid>c5c7d7af-4013-4fa3-bc1f-de1d23ccb0d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyGLN.GLNExtension</value>
      <webElementGuid>3e61f8b2-a102-42ac-ae7b-8128b2001aff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>68cd537a-b581-4da8-9acb-64b8e39a28fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PartyGLN_GLNExtension&quot;)</value>
      <webElementGuid>7ef46dd2-7cee-4c76-83da-de46a92470fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='PartyGLN_GLNExtension']</value>
      <webElementGuid>144310f3-da25-401b-a4e9-8ed610d32706</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='glnModel']/div[2]/div/input</value>
      <webElementGuid>5dc5ceb4-fcb5-4711-9bfc-e8b859ca68e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/input</value>
      <webElementGuid>509e7314-5750-4db2-9eb5-bd70a639d94a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'PartyGLN_GLNExtension' and @placeholder = 'Enter GLN Extension' and @type = 'text' and @name = 'PartyGLN.GLNExtension']</value>
      <webElementGuid>0cac59c6-3a9d-4a81-b9c0-811ebff0e379</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
