<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Location Details Tab</name>
   <tag></tag>
   <elementGuidId>1859c363-1ce1-4d0f-bdcc-23295c4fbb83</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_locDetail']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_locDetail</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>543f0619-4d08-4399-b833-594f3585120a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_locDetail</value>
      <webElementGuid>d538c2eb-371c-4d8c-9662-19d463d1ca0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab tab-inactive</value>
      <webElementGuid>7892ca1d-157a-4111-bcf6-2b4b7325483d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Location Details  </value>
      <webElementGuid>8e927728-d2aa-4e2b-87a9-dfb97ad22eac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_locDetail&quot;)</value>
      <webElementGuid>3056c58d-e387-4d6e-b3ea-46016e211d34</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_locDetail']</value>
      <webElementGuid>87d2687d-273a-44ec-b14b-923d6227ff92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Role :'])[1]/following::button[1]</value>
      <webElementGuid>2940409c-11b4-49bc-af3e-738327c57c46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party GLN :'])[1]/following::button[1]</value>
      <webElementGuid>9ac17995-dfb7-4811-996d-8b55f9c7d78d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Identifiers'])[1]/preceding::button[1]</value>
      <webElementGuid>4ad8aa8f-c26f-4598-9329-5e6da3e3e53f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub-Locations'])[1]/preceding::button[2]</value>
      <webElementGuid>fb4e1973-e146-428c-895f-e76e12bbb330</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Location Details']/parent::*</value>
      <webElementGuid>c3a1dd70-50b6-4cc0-a5c4-d00f29d66a88</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/button</value>
      <webElementGuid>8b16d3ed-77c4-4ca0-b99d-815b396a2657</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_locDetail' and (text() = ' Location Details  ' or . = ' Location Details  ')]</value>
      <webElementGuid>cf4340bb-ea32-48a4-b9b8-d03dcdc88cad</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
