<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Location Parent Name</name>
   <tag></tag>
   <elementGuidId>f52128c3-2072-4ff2-b342-0cf7f0db5260</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='ParentId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PartyLocationTypeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>3712392c-d97a-4bde-b53a-45d25231c8c4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PartyLocationTypeId</value>
      <webElementGuid>2940dcd7-bc86-4cad-ab74-1edb6b0e63f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>060fdc1b-616a-4a38-8f0e-0506a76de894</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4e567455-cb55-4d44-acfa-b95e193de8a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PartyLocationTypeId field is required.</value>
      <webElementGuid>db73dc7d-1447-4ecd-9780-f31a91fa0464</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocationBasicInfo.PartyLocationTypeId</value>
      <webElementGuid>9fc3a319-9e6e-4401-affa-180145746345</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Location TypeAccounts DepartmentAssemblyBackroomCargo TerminalContainer DeckControlled Substance AreaConveyor BeltCustomer Pick-Up AreaDispenserDistribution centreDrugstoreElectronics AreaEnd Cap AreaEntrance GateExit GateFixed ReaderGateGovernment Department AgencyHead OfficeImprest LocationInbound And Outbound DockInbound DockLay-Away Main ReceptionManufacturing PlantMobile ReaderOfficeOutbound DockPackaging AreaPackhousePallet WrapperPicking AreaPoint Of SalePrinting RoomProduction AreaProduction LinePromotion AreaPublic WarehouseQuality ControlQuarantine Read Point Verification SpotRecalled Product  AreaReceiving AreaReceiving LocationResearch FacilityRetail PharmacyReturnable Asset Service CentreReturns AreaSales Floor Sales Floor Transition Area Sales YardSecurity AreaShelf Shipping AreaStagingStocking locationStorage AreaStorage LocationStoreTRADE_ITEM_RETURN_LOCATIONVendor Leased SpaceVisiting AddressWardWarehouse and/or DepotYard </value>
      <webElementGuid>dc28c4af-f76b-42fc-a655-ffee60bcae22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PartyLocationTypeId&quot;)</value>
      <webElementGuid>16e1607d-c2a9-425a-aa3a-bec74dec6f32</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PartyLocationTypeId']</value>
      <webElementGuid>5ed7c966-2685-4927-88e7-aa62c2c23bd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div/div/div/div/div[3]/div/select</value>
      <webElementGuid>c4fb74f7-f355-4c49-9412-2a6382210476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Type'])[1]/following::select[1]</value>
      <webElementGuid>8ad14ff5-0a4e-4bc5-a518-2485d04e0f57</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason For Status Change'])[1]/following::select[1]</value>
      <webElementGuid>138297e7-5a1c-479b-b242-bffd05a62e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sub-Site Attributes'])[1]/preceding::select[1]</value>
      <webElementGuid>ebfc0b25-c5a2-49d3-856c-ef5f670c282c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Assembly'])[3]/preceding::select[2]</value>
      <webElementGuid>cfa98529-e49d-49ad-bde1-995283cbbe8d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/select</value>
      <webElementGuid>df47b971-f033-40de-8863-8dfb5f27e486</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PartyLocationTypeId' and @name = 'LocationBasicInfo.PartyLocationTypeId' and (text() = 'Select Location TypeAccounts DepartmentAssemblyBackroomCargo TerminalContainer DeckControlled Substance AreaConveyor BeltCustomer Pick-Up AreaDispenserDistribution centreDrugstoreElectronics AreaEnd Cap AreaEntrance GateExit GateFixed ReaderGateGovernment Department AgencyHead OfficeImprest LocationInbound And Outbound DockInbound DockLay-Away Main ReceptionManufacturing PlantMobile ReaderOfficeOutbound DockPackaging AreaPackhousePallet WrapperPicking AreaPoint Of SalePrinting RoomProduction AreaProduction LinePromotion AreaPublic WarehouseQuality ControlQuarantine Read Point Verification SpotRecalled Product  AreaReceiving AreaReceiving LocationResearch FacilityRetail PharmacyReturnable Asset Service CentreReturns AreaSales Floor Sales Floor Transition Area Sales YardSecurity AreaShelf Shipping AreaStagingStocking locationStorage AreaStorage LocationStoreTRADE_ITEM_RETURN_LOCATIONVendor Leased SpaceVisiting AddressWardWarehouse and/or DepotYard ' or . = 'Select Location TypeAccounts DepartmentAssemblyBackroomCargo TerminalContainer DeckControlled Substance AreaConveyor BeltCustomer Pick-Up AreaDispenserDistribution centreDrugstoreElectronics AreaEnd Cap AreaEntrance GateExit GateFixed ReaderGateGovernment Department AgencyHead OfficeImprest LocationInbound And Outbound DockInbound DockLay-Away Main ReceptionManufacturing PlantMobile ReaderOfficeOutbound DockPackaging AreaPackhousePallet WrapperPicking AreaPoint Of SalePrinting RoomProduction AreaProduction LinePromotion AreaPublic WarehouseQuality ControlQuarantine Read Point Verification SpotRecalled Product  AreaReceiving AreaReceiving LocationResearch FacilityRetail PharmacyReturnable Asset Service CentreReturns AreaSales Floor Sales Floor Transition Area Sales YardSecurity AreaShelf Shipping AreaStagingStocking locationStorage AreaStorage LocationStoreTRADE_ITEM_RETURN_LOCATIONVendor Leased SpaceVisiting AddressWardWarehouse and/or DepotYard ')]</value>
      <webElementGuid>268e3845-b189-4ec1-bf92-d3b1eda60804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
