<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Location Classification</name>
   <tag></tag>
   <elementGuidId>484ff1c1-507b-44fc-af73-4597c92bb127</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locationcassificationddl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='locationcassificationddl']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>a074f9c4-9951-4517-a8b3-6a37d8d46eb5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms</value>
      <webElementGuid>1b07c1e6-cc6e-4bf7-b780-b81ac84ecc1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locationcassificationddl</value>
      <webElementGuid>6c7c46b5-a4b7-47f0-bb8d-b3ee0f39d0ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>subsitehideandshow()</value>
      <webElementGuid>7696bf9d-7abf-417b-a174-5370a4056d49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b3bfe3e8-d71c-4f9d-8a14-fd9a7c419049</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The LocationClassification field is required.</value>
      <webElementGuid>a22a3977-14f6-48d4-a7d2-467a034c09ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>LocationBasicInfo.LocationClassification</value>
      <webElementGuid>025a5cb8-567f-40fd-8a63-1ae7e1a8d250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LocationSub-site LocationDigital LocationFunction</value>
      <webElementGuid>76fa5839-c3aa-4adb-b888-2989b9af59ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locationcassificationddl&quot;)</value>
      <webElementGuid>55ab556b-a5f5-41d5-b07a-074354a9de81</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='locationcassificationddl']</value>
      <webElementGuid>af0a204e-b96e-4fce-a85e-cea674b3a501</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Detail']/div/div/div/div/div/div[2]/div/select</value>
      <webElementGuid>0c73c8a5-afab-4c47-a952-2008c86bf9bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Classification'])[1]/following::select[1]</value>
      <webElementGuid>f03e2788-178e-4982-b1cb-c78ed93d151f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Inactive'])[1]/following::select[1]</value>
      <webElementGuid>c59b3e82-b65a-4619-9193-3e152e13324b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reason For Status Change'])[1]/preceding::select[1]</value>
      <webElementGuid>97d626d1-9933-4345-951c-7f553eda61ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Location Type'])[1]/preceding::select[1]</value>
      <webElementGuid>1181f871-10b6-4df3-98ed-01b597a13990</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/select</value>
      <webElementGuid>83c117ef-46d6-4dd2-b15b-e91ff6106a83</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'locationcassificationddl' and @name = 'LocationBasicInfo.LocationClassification' and (text() = 'LocationSub-site LocationDigital LocationFunction' or . = 'LocationSub-site LocationDigital LocationFunction')]</value>
      <webElementGuid>67a5aa8a-47f6-4158-aada-66539ea4a6ce</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
