<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Sub-Site Attributes_searchResult</name>
   <tag></tag>
   <elementGuidId>3df37c3b-d1cd-4d94-9e19-734dbdce11d2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//li[text()='${RoleString}']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='subsiteattributediv']/div/div[2]/ul/li</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>3ac3e0ff-0d79-4434-b9ac-256c52dbb36b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>a2052ba5-1f99-4b8b-99b4-42f0961d6404</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${RoleString}</value>
      <webElementGuid>2054ce13-6c39-450f-b956-f8c3d80b8cd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[text()='${RoleString}']</value>
      <webElementGuid>704d2c00-33e7-464d-91f1-44680f018497</webElementGuid>
   </webElementProperties>
</WebElementEntity>
