<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>bt_SaveContact</name>
   <tag></tag>
   <elementGuidId>9bfdc6dc-4eed-4418-9dd4-1fbd454f30ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_Submit_AddContact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_Submit_AddContact</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>93668158-7c81-4b4b-be99-4153bf3be1e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>9ddc18a5-7632-408a-a9b4-fd506f2b5c93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_Submit_AddContact</value>
      <webElementGuid>4329d649-928c-4ac1-bfb9-c489c7f37d7c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-save ml-2 mt-3</value>
      <webElementGuid>a99f1c25-6fa0-4090-886f-69f2b9e4521d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>7e3bde1d-89be-4fe8-94bc-a7bfacad54e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_Submit_AddContact&quot;)</value>
      <webElementGuid>10ad6dea-b965-4536-976c-12460d780eb6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_Submit_AddContact']</value>
      <webElementGuid>8ccd8639-4be5-4b4d-b390-ea22f1f48081</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='modal-AddContact']/div/div/div[3]/button[2]</value>
      <webElementGuid>8dade6d8-3682-48db-bc8c-022b3751c44a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[5]/following::button[1]</value>
      <webElementGuid>37acd02c-cfcb-4b69-9f3f-f1f4611feef2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[2]/following::button[2]</value>
      <webElementGuid>145c7b63-20c6-499b-bc6d-adc8588c5f4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete Confirmation'])[2]/preceding::button[1]</value>
      <webElementGuid>7e1c56ff-75bb-400c-9bcb-cc78e39ea119</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Confirm'])[3]/preceding::button[2]</value>
      <webElementGuid>e6f685af-0330-491c-84d9-eac694ec232c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form[2]/div/div/div/div[3]/button[2]</value>
      <webElementGuid>da1d5e8b-8778-4d69-89f8-6af1a8033160</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn_Submit_AddContact' and (text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>2550adb2-8313-40bd-8852-ba54d00bbb41</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
