<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Department Name</name>
   <tag></tag>
   <elementGuidId>5da05f6f-da2e-477b-808b-2b102fe6c6be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Department']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#Department</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b4d941e1-f54e-4756-a715-89bf1ea03c50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row modal-input</value>
      <webElementGuid>9def097e-4f87-4d1f-beba-0852de1f6b96</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Department Name</value>
      <webElementGuid>a84906e2-1ce6-4f69-84a4-68fe81a086e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>13</value>
      <webElementGuid>738d982f-fbcb-40bd-ac8d-8a1feb17d2c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>clearspandeptmsg()</value>
      <webElementGuid>22cc4541-5119-4ad8-9ba8-5a7e9b7d50aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>6e306498-de4f-4442-9bfb-87fc9f9a44a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Department</value>
      <webElementGuid>ae8e0250-a1fe-4ad4-96e9-5df9dd71e043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>Department</value>
      <webElementGuid>95ff7417-373f-439c-ada0-a31f8f7fc553</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Department&quot;)</value>
      <webElementGuid>b4e38df6-2bf4-4d51-abcc-4c591a83cb4a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Department']</value>
      <webElementGuid>dbf53e78-cfc3-4ddd-bc38-14521b73fda5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddContact']/div/div[3]/div/input</value>
      <webElementGuid>1bd4144b-2cec-48cc-8e0a-bbdafcc4c955</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[3]/div/input</value>
      <webElementGuid>7df56858-1cb9-47d9-9d98-c33220d0dc7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'Enter Department Name' and @type = 'text' and @id = 'Department' and @name = 'Department']</value>
      <webElementGuid>8aa186fd-68b8-45a4-bacf-b85b5bdf03a4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
