<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delivery Mode</name>
   <tag></tag>
   <elementGuidId>9fb76cdf-16f0-4834-bf60-5f333b738710</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DeliveryModeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DeliveryModeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>48dcafe9-c6d8-4eef-9cf9-3d5fb194ea84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DeliveryModeId</value>
      <webElementGuid>fa29d0fb-17b7-42f1-8492-baca8a6628cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profile</value>
      <webElementGuid>451efec2-97d3-497c-993f-d5872957eca9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>33950482-340c-4e3f-a247-8b9ec853132b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The DeliveryModeId field is required.</value>
      <webElementGuid>7c98e12c-e74a-44b4-9a7f-55b389becdaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DeliveryModeId</value>
      <webElementGuid>a6f9631c-40a4-41f7-af4a-f0b6fd116249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RangeList</value>
      <webElementGuid>d02192aa-7767-4522-bf5e-fd2375042e0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DeliveryModeId&quot;)</value>
      <webElementGuid>80d1b5d4-c88a-4f6a-9ae4-c2ed148f7193</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DeliveryModeId']</value>
      <webElementGuid>1cc83158-7d77-42ab-bd30-5d4c5a0c83c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div[3]/div[2]/select</value>
      <webElementGuid>7e842caf-8dfe-4dbe-ae06-9599f7d89ff2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Mode'])[1]/following::select[1]</value>
      <webElementGuid>1eef1694-08e2-40a9-8a7f-980f2089010e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Request Quantity'])[1]/following::select[1]</value>
      <webElementGuid>80afc6ff-bfbb-4546-a245-90edf698dcd0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding Format'])[1]/preceding::select[1]</value>
      <webElementGuid>62a3f6bf-0ef0-41fe-b257-9296e5c65b91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding Prefix'])[1]/preceding::select[2]</value>
      <webElementGuid>101cccdd-d510-4caa-bba1-5244467c1533</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>7eb2ef2c-26ae-4f16-b22f-e1c825d4dd37</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DeliveryModeId' and @name = 'DeliveryModeId' and (text() = 'RangeList' or . = 'RangeList')]</value>
      <webElementGuid>8d0266f6-d1c9-4b43-83d9-1cb79742e550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
