<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Encoding Format</name>
   <tag></tag>
   <elementGuidId>fab5fccd-c6d8-4839-9c09-2428cd263ce0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OutputFormatTypeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DeliveryModeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>506b8dc7-4a84-4d5d-896e-989d0f70dd9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DeliveryModeId</value>
      <webElementGuid>421fad67-fffe-443d-949a-03de1b8a4a56</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profile</value>
      <webElementGuid>57e7a02a-429e-4cf2-938c-bf52f61240c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a0e2b435-4ae4-4bd3-b700-e39d10187fd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The DeliveryModeId field is required.</value>
      <webElementGuid>8bdf4bce-2acf-4170-8e05-ae9289a46048</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DeliveryModeId</value>
      <webElementGuid>030bf113-bdeb-4735-a197-ec255c14a577</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RangeList</value>
      <webElementGuid>6ad9b513-9bc8-4bda-b40d-978b027182a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DeliveryModeId&quot;)</value>
      <webElementGuid>b0817fb2-b831-4c2b-b594-aaaabc2ed669</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DeliveryModeId']</value>
      <webElementGuid>0e8e39f7-645b-42ef-a1cf-aeefb42c03a3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div[3]/div[2]/select</value>
      <webElementGuid>d410f6e3-ece7-462c-968c-a98cee794411</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Mode'])[1]/following::select[1]</value>
      <webElementGuid>6fe71d68-b5ee-471e-bff0-b648a549dc98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Request Quantity'])[1]/following::select[1]</value>
      <webElementGuid>e5489ca0-f6de-4912-9507-eee14c2b15f1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding Format'])[1]/preceding::select[1]</value>
      <webElementGuid>d0ce5269-edb5-4bdc-833d-a15505fafc29</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding Prefix'])[1]/preceding::select[2]</value>
      <webElementGuid>426689fd-aba6-4fdc-a1b7-5f6cc1fdf66c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>8b783dec-f45d-439f-b5f2-925eaa7f1f5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DeliveryModeId' and @name = 'DeliveryModeId' and (text() = 'RangeList' or . = 'RangeList')]</value>
      <webElementGuid>83521358-0a30-4b2f-b939-caddb76a1792</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
