<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Party Name</name>
   <tag></tag>
   <elementGuidId>63270a86-bf72-480d-95c6-9cc670a00d3f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PartyId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PartyId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>686a0cf1-3e14-4381-b3c1-593ebf8070fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PartyId</value>
      <webElementGuid>d3300b89-ec40-4523-ac33-d839b8f87e1b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profile</value>
      <webElementGuid>e9e5f8d9-a849-4300-8763-76ec7c8a6665</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>systemPartyChange(this)</value>
      <webElementGuid>b1812535-79aa-4d4f-a630-58d42bee1d5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0c9d7c64-9c18-477f-b5a9-3654fecddd08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PartyId field is required.</value>
      <webElementGuid>82aafb32-cdad-4fa3-bfa7-ecc9e6839123</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyId</value>
      <webElementGuid>8ebdeca3-7df2-403b-9746-c2272092f50e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827</value>
      <webElementGuid>2eaee235-65d5-451b-842f-da7c2d84d202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PartyId&quot;)</value>
      <webElementGuid>044f444a-d2f4-4e81-85ee-7a432d58ab65</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PartyId']</value>
      <webElementGuid>aea9b5ac-0439-41df-9e7d-5aebccff8a3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div/div/select</value>
      <webElementGuid>2f295b27-7513-437e-ac43-6e568f10acef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Name'])[2]/following::select[1]</value>
      <webElementGuid>37702fda-3532-4766-8202-4f52d2596f7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New System'])[1]/following::select[1]</value>
      <webElementGuid>e4014ac0-bd52-4902-9fc1-ac0b28f7f190</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Name'])[1]/preceding::select[1]</value>
      <webElementGuid>611ccb12-6692-4ac7-a3c8-33b9f8728816</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Range'])[1]/preceding::select[2]</value>
      <webElementGuid>ceaaf9dd-dd2d-458c-8f20-857a6b128f46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/select</value>
      <webElementGuid>4d161924-b3a9-47ae-b3ce-a48491cbf66b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PartyId' and @name = 'PartyId' and (text() = 'Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827' or . = 'Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827')]</value>
      <webElementGuid>c67a93b9-9200-4881-95f6-a20833e264af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
