<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RFID Filter</name>
   <tag></tag>
   <elementGuidId>60e955c2-d46d-4567-8489-0e8c9285f31a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='FilterValue']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#FilterValue</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>776a02c1-262a-4ed1-b807-0c0419e7b3fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ss</value>
      <webElementGuid>6306d734-a099-4e50-af45-0c4354a3125d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>FilterValue</value>
      <webElementGuid>053a8d29-5497-495e-a53c-189a734515ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>PopulateDescription()</value>
      <webElementGuid>779f227d-40dd-46b0-a278-d1510efb6750</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onblur</name>
      <type>Main</type>
      <value>profileDescriptiongenerated()</value>
      <webElementGuid>bc23fc03-149d-4232-8944-d628e63ca0e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fca586de-a261-456b-826a-01422d133598</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The FilterValue field is required.</value>
      <webElementGuid>c80c3980-85e1-48b0-a3e9-f87d6a42c961</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>BasicInfo.FilterValue</value>
      <webElementGuid>ba070add-ca95-41bf-83ac-49433cb0a035</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select01234567</value>
      <webElementGuid>2d40ac1e-0584-4c15-abfa-0fc402b24f48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;FilterValue&quot;)</value>
      <webElementGuid>0e737cb6-8a24-482c-9cdc-cdeb1caa5f02</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='FilterValue']</value>
      <webElementGuid>79d3a6e0-ca22-4206-88fb-b062e48164ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_Ssccserializationprofile']/div/div[2]/div[2]/div/div[2]/select</value>
      <webElementGuid>2eebcc23-7748-4898-b79c-e17bb6f3f06b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RFID Filter Value'])[1]/following::select[1]</value>
      <webElementGuid>93ec3383-b439-4852-b0f7-85845048ea26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Extension Digit'])[1]/following::select[2]</value>
      <webElementGuid>6687dd11-9661-4b6e-b7c7-c219d463c500</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SSCC Profile'])[4]/preceding::select[1]</value>
      <webElementGuid>dffc1eeb-b118-45ba-bc21-d3373ab7038d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SSCC Profile Description'])[1]/preceding::select[1]</value>
      <webElementGuid>3e865cb4-e807-4135-b7f4-a1612fc2c24b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/select</value>
      <webElementGuid>f910d168-d551-4cf6-815e-d21b9c5b4a9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'FilterValue' and @name = 'BasicInfo.FilterValue' and (text() = 'Select01234567' or . = 'Select01234567')]</value>
      <webElementGuid>c0dcbdf7-5478-40c6-9305-384ba78c355c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
