<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Separate Prefix</name>
   <tag></tag>
   <elementGuidId>425fc567-8d71-4bbe-9de5-c07a499e4646</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SeperatePrefix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SeperatePrefix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b520f418-1642-441c-b44a-20f5afdea262</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SeperatePrefix</value>
      <webElementGuid>5b8ed95c-b52f-4b3b-8951-a3ccb02bd8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profilesm sgtinSeperatePre</value>
      <webElementGuid>32cc1ba7-1618-4e7c-90df-93114acb0e95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Separate Prefix</value>
      <webElementGuid>5a05164b-7394-47cb-8ea8-1e4f989da48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>db21ab1c-19be-4b2e-930b-723dd4b1c5ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9f74deaf-b2f9-4567-9a84-68a1aaef88fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SeperatePrefix field is required.</value>
      <webElementGuid>77fe88e5-cf42-407e-bd43-a4e5cc0340f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SeperatePrefix</value>
      <webElementGuid>8819ad82-4ac7-4dbf-82b8-e8cecfb87ba0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7806f76-83c3-4afb-9f41-141a746e614d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SeperatePrefix&quot;)</value>
      <webElementGuid>9c56d330-dce8-4e57-a0cf-1161e0bf2a50</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SeperatePrefix']</value>
      <webElementGuid>92f50054-d424-423d-a9a7-14f205b9f6cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div[4]/div[3]/input</value>
      <webElementGuid>b4359785-08cc-4f15-a09b-7bcb1acadd9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>fbe75d57-976f-4018-8edb-b083e09eb320</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SeperatePrefix' and @placeholder = 'Enter Separate Prefix' and @type = 'checkbox' and @name = 'SeperatePrefix']</value>
      <webElementGuid>51865395-6ab8-46cd-bf89-2e7726c2ded2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
