<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>System Name</name>
   <tag></tag>
   <elementGuidId>f86c284c-eab9-4d4b-adcc-25e62fa47ad0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='SystemId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PartyId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>d503df5e-ad9a-444b-a03b-009790c5df46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PartyId</value>
      <webElementGuid>86082628-62c5-4a6f-93c2-53aa93dd4568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profile</value>
      <webElementGuid>1383cf5d-b641-465f-8fab-b38edade9a59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>systemPartyChange(this)</value>
      <webElementGuid>5a62a5e9-d686-4aea-8a1f-5519da65419c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>e1666496-8913-47e3-a6a2-d3dcdd406614</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PartyId field is required.</value>
      <webElementGuid>cc3a6340-ec4d-4e6a-b8ce-6dbecd116c48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyId</value>
      <webElementGuid>2848e64b-30ce-4f45-b0ad-51ef14303dfd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827</value>
      <webElementGuid>094084aa-cfba-43b5-9799-a3e00c1eed0c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PartyId&quot;)</value>
      <webElementGuid>f2d3f767-07ec-4fc1-b41a-19558ea90205</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PartyId']</value>
      <webElementGuid>54f4d4bd-e9ac-4a4d-8759-79ec149961c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div/div/select</value>
      <webElementGuid>d06a5f4e-8b5f-4587-ac6e-17e5601dfdea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Name'])[2]/following::select[1]</value>
      <webElementGuid>61b9b58a-7ddc-41be-8ee4-f2740a6869a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New System'])[1]/following::select[1]</value>
      <webElementGuid>c3cd32ee-f97c-4167-8165-d650b597c923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Name'])[1]/preceding::select[1]</value>
      <webElementGuid>72062d97-8a5e-42be-b050-d25474539f0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Range'])[1]/preceding::select[2]</value>
      <webElementGuid>f5d3f556-6278-4fe9-89ad-5918bbf7cdb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/select</value>
      <webElementGuid>427fcef2-b701-4acd-9c29-224552c9c972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PartyId' and @name = 'PartyId' and (text() = 'Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827' or . = 'Select Party NameParty 667301Party 101Party 672204Party 305941RK Pharma IncMcKessonParty 340240Party 37965Party 829097Party 613797Party 86889Party 415199DE-PartyParty 564408Party 828205Party 539401Party 354827')]</value>
      <webElementGuid>2616e839-f02e-4659-9b47-f414447ceacc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
