<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>IsDefault slider_DO</name>
   <tag></tag>
   <elementGuidId>4db1aa20-4622-4772-8983-b66572e42957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//table[@id='ownerTable']/tbody/tr[2]/td[4]/label/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>tr:nth-of-type(2) > td.defaultCell > label.toggle.switch.ml-1 > span.slider</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f48476e2-4018-4996-b049-9d937c41ed0e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>slider</value>
      <webElementGuid>26cd1827-95e2-452c-a0e8-9805da59176c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ownerTable&quot;)/tbody[1]/tr[2]/td[@class=&quot;defaultCell&quot;]/label[@class=&quot;toggle switch ml-1&quot;]/span[@class=&quot;slider&quot;]</value>
      <webElementGuid>9318769b-ff80-474a-beb0-05ea4378efab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='ownerTable']/tbody/tr[2]/td[4]/label/span</value>
      <webElementGuid>b9c97e02-79a2-4ebe-865c-34ac4c0355d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[2]/td[4]/label/span</value>
      <webElementGuid>891c03b8-0706-4e27-9120-e86b65fb2f21</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
