<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Contact</name>
   <tag></tag>
   <elementGuidId>3f653ba0-f90c-4d92-be99-2acdee8bc1ff</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_AddContact']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#btn_AddContact</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4d90f5b8-53cd-4660-8551-5b349e3d6851</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_AddContact</value>
      <webElementGuid>c2be9a73-e8fe-40b5-aed6-860d6f41a277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-primary btn-ls mt-neg-fourty mr-5</value>
      <webElementGuid>bb138655-da4b-4da4-bc0e-3306e4cb9ef8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-toggle</name>
      <type>Main</type>
      <value>ajax-modal</value>
      <webElementGuid>b57ebdbe-5930-4873-aecd-0a0f48f991d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bs-target</name>
      <type>Main</type>
      <value>#modal-AddContact</value>
      <webElementGuid>4b97cbdf-2813-4683-a814-7de0f0000e08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Contact</value>
      <webElementGuid>695bbbee-b0bb-430a-b6e2-d7632a6ea33b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_AddContact&quot;)</value>
      <webElementGuid>530a95d8-cc27-4724-a4fb-4827f8b380b8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_AddContact']</value>
      <webElementGuid>2eb5555b-77a0-48ac-bfb6-7c760c7f7859</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='party-contact-points-847e4440cf8c']/div/div/button</value>
      <webElementGuid>f269d32c-d41d-43c8-be7f-14113faa9efe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Points'])[1]/following::button[1]</value>
      <webElementGuid>be421288-5bbf-44b4-90dd-f28f876dacb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Geo Fence'])[1]/following::button[1]</value>
      <webElementGuid>141e8fbb-f07b-41a3-b93a-f7aa3aea3438</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='ContactId'])[1]/preceding::button[1]</value>
      <webElementGuid>799b0882-80e4-454d-a6f1-3547d7368a69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Contact Type'])[1]/preceding::button[1]</value>
      <webElementGuid>79b8764f-6b02-4771-ab3c-aa22b2a98f26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Contact']/parent::*</value>
      <webElementGuid>ff045b64-162f-4a57-ad93-d0b71998183d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/button</value>
      <webElementGuid>f3759190-df3c-4ef7-88ed-870a130259e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_AddContact' and (text() = 'Add Contact' or . = 'Add Contact')]</value>
      <webElementGuid>691f93da-0aca-4566-b7b7-d163193b099f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
