<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Add Language Tab</name>
   <tag></tag>
   <elementGuidId>dc06724b-4dcc-4d85-9c0c-a43104827582</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@onclick='addlanguage()']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.img-add.ml-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>baaad656-e213-4715-995a-bf41f402b3dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>img-add ml-2</value>
      <webElementGuid>c2254ab9-614d-4910-97dd-66c2a88b7e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>addlanguage()</value>
      <webElementGuid>5b449701-89ed-43b0-8fb5-2f858fcc389d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;party-information-81f4932652ca&quot;)/div[@class=&quot;col&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;d-flex sm-tab px-0 mc&quot;]/div[@class=&quot;custom-tooltip-container&quot;]/div[@class=&quot;img-add ml-2&quot;]</value>
      <webElementGuid>c01ee21f-3326-4a17-aeb8-f078afd7c9db</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@onclick='addlanguage()']</value>
      <webElementGuid>94ef61d4-1ac1-40dd-8f37-0710c1647028</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='party-information-81f4932652ca']/div/div[2]/div/div/div</value>
      <webElementGuid>68522463-1229-4bba-9b29-b03784d3d528</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div[2]/div/div/div</value>
      <webElementGuid>da669cc1-ba3c-435f-a13f-7e69d6f292fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
