<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address.PostalCode</name>
   <tag></tag>
   <elementGuidId>d9f248bf-4f5a-43d9-89f0-841c5f6374b2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partyAddress.PostalCode[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4061a5dd-75bf-40fc-8873-a7dd8fe624cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partyAddress.PostalCode[0]</value>
      <webElementGuid>fa8147fd-367b-4a56-a7c6-eba8265736e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>oninput</name>
      <type>Main</type>
      <value>allowNumericInput(event)</value>
      <webElementGuid>b6ff4f49-1559-4040-8624-250685130eae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-sss ml-2 partypostal</value>
      <webElementGuid>a3e70185-7ff4-4360-8cb5-b60f28ed1835</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Postal Code</value>
      <webElementGuid>7804ca4f-55d7-418f-9c56-ae8abcb1dda9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>20</value>
      <webElementGuid>1901a826-efcb-4407-9d4d-6bb1b6af5bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>40241d06-9ff1-4376-ad11-c95ef575bdd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.PartyAddress.PostalCode</value>
      <webElementGuid>3358d1f2-d702-4bda-8631-830042412658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partyAddress.PostalCode[0]&quot;)</value>
      <webElementGuid>972998b2-4bec-4e98-947f-b535b5abfa89</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partyAddress.PostalCode[0]']</value>
      <webElementGuid>8c4ade58-1f07-46dc-87d1-9a60f16f8c4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_AddLanguage']/div/div[6]/div[5]/div[2]/div/div[2]/input</value>
      <webElementGuid>d59523e9-e63b-4e37-90e7-8e858a06dbdb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div[2]/input</value>
      <webElementGuid>28101e52-2a9f-40af-8edf-3b70bf20a72c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'partyAddress.PostalCode[0]' and @placeholder = 'Enter Postal Code' and @type = 'text' and @name = 'item.PartyAddress.PostalCode']</value>
      <webElementGuid>1e7944b2-e083-4e3f-8e0f-648b7686e9be</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
