<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Address.Country</name>
   <tag></tag>
   <elementGuidId>fbee7414-991c-42ee-ac55-81d2d625a3b6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='partyAddress.countryDropdown[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>7bf9800f-6c31-4aa5-8ed1-4a5fe9f2d764</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partyAddress.countryDropdown[0]</value>
      <webElementGuid>02368888-76f1-4d21-8f11-d94dc12dbb73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms partybasicinfoinput</value>
      <webElementGuid>a89cd1d2-f3c0-4538-88c2-b441319e9814</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-trigger</name>
      <type>Main</type>
      <value>partyAddress.stateDropdown[0]</value>
      <webElementGuid>361d6a93-e0ea-4b48-aea6-f421c8d2ffff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-loading</name>
      <type>Main</type>
      <value>#states-loading-progress</value>
      <webElementGuid>f927c28c-56fc-473e-9a85-bb69bb78dc18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>87cd3756-de48-484e-8e5f-0bd400807a99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The CountryId field is required.</value>
      <webElementGuid>1774b707-4fa1-4e4c-9290-2d8a8db107c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.PartyAddress.CountryId</value>
      <webElementGuid>5ed144e2-82a4-43a4-ab5c-3caaca1f4b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select a countryUS - United States of AmericaAF - AfghanistanAX - Åland IslandsAL - AlbaniaDZ - AlgeriaAS - American SamoaAD - AndorraAO - AngolaAI - AnguillaAQ - AntarcticaAG - Antigua and BarbudaAR - ArgentinaAM - ArmeniaAW - ArubaAU - AustraliaAT - AustriaAZ - AzerbaijanBS - BahamasBH - BahrainBD - BangladeshBB - BarbadosBY - BelarusBE - BelgiumBZ - BelizeBJ - BeninBM - BermudaBT - BhutanBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBA - Bosnia and HerzegovinaBW - BotswanaBV - Bouvet IslandBR - BrazilIO - British Indian Ocean TerritoryBN - Brunei DarussalamBG - BulgariaBF - Burkina FasoBI - BurundiCV - Cabo VerdeKH - CambodiaCM - CameroonCA - CanadaKY - Cayman IslandsCF - Central African RepublicTD - ChadCL - ChileCN - ChinaCX - Christmas IslandCC - Cocos (Keeling) IslandsCO - ColombiaKM - ComorosCG - CongoCD - Congo (Democratic Republic of the)CK - Cook IslandsCR - Costa RicaCI - Côte d'IvoireHR - CroatiaCU - CubaCW - CuraçaoCY - CyprusCZ - CzechiaDK - DenmarkDJ - DjiboutiDM - DominicaDO - Dominican RepublicEC - EcuadorEG - EgyptSV - El SalvadorGQ - Equatorial GuineaER - EritreaEE - EstoniaSZ - EswatiniET - EthiopiaFK - Falkland Islands (Malvinas)FO - Faroe IslandsFJ - FijiFI - FinlandFR - FranceGF - French GuianaPF - French PolynesiaTF - French Southern TerritoriesGA - GabonGM - GambiaGE - GeorgiaDE - GermanyGH - GhanaGI - GibraltarGR - GreeceGL - GreenlandGD - GrenadaGP - GuadeloupeGU - GuamGT - GuatemalaGG - GuernseyGN - GuineaGW - Guinea-BissauGY - GuyanaHT - HaitiHM - Heard Island and McDonald IslandsVA - Holy SeeHN - HondurasHK - Hong KongHU - HungaryIS - IcelandIN - IndiaID - IndonesiaIR - Iran (Islamic Republic of)IQ - IraqIE - IrelandIM - Isle of ManIL - IsraelIT - ItalyJM - JamaicaJP - JapanJE - JerseyJO - JordanKZ - KazakhstanKE - KenyaKI - KiribatiKP - Korea (Democratic People's Republic of)KR - Korea (Republic of)KW - KuwaitKG - KyrgyzstanLA - Lao People's Democratic RepublicLV - LatviaLB - LebanonLS - LesothoLR - LiberiaLY - LibyaLI - LiechtensteinLT - LithuaniaLU - LuxembourgMO - MacaoMG - MadagascarMW - MalawiMY - MalaysiaMV - MaldivesML - MaliMT - MaltaMH - Marshall IslandsMQ - MartiniqueMR - MauritaniaMU - MauritiusYT - MayotteMX - MexicoFM - Micronesia (Federated States of)MD - Moldova (Republic of)MC - MonacoMN - MongoliaME - MontenegroMS - MontserratMA - MoroccoMZ - MozambiqueMM - MyanmarNA - NamibiaNR - NauruNP - NepalNL - NetherlandsNC - New CaledoniaNZ - New ZealandNI - NicaraguaNE - NigerNG - NigeriaNU - NiueNF - Norfolk IslandMK - North MacedoniaMP - Northern Mariana IslandsNO - NorwayOM - OmanPK - PakistanPW - PalauPS - Palestine, State ofPA - PanamaPG - Papua New GuineaPY - ParaguayPE - PeruPH - PhilippinesPN - PitcairnPL - PolandPT - PortugalPR - Puerto RicoQA - QatarRE - RéunionRO - RomaniaRU - Russian FederationRW - RwandaBL - Saint BarthélemySH - Saint Helena, Ascension and Tristan da CunhaKN - Saint Kitts and NevisLC - Saint LuciaMF - Saint Martin (French part)PM - Saint Pierre and MiquelonVC - Saint Vincent and the GrenadinesWS - SamoaSP - San MarinoST - Sao Tome and PrincipeSA - Saudi ArabiaSN - SenegalRS - SerbiaSC - SeychellesSL - Sierra LeoneSG - SingaporeSX - Sint Maarten (Dutch part)SK - SlovakiaSI - SloveniaSB - Solomon IslandsSO - SomaliaZA - South AfricaGS - South Georgia and the South Sandwich IslandsSS - South SudanES - SpainLK - Sri LankaSD - SudanSR - SurinameSJ - Svalbard and Jan MayenSE - SwedenCH - SwitzerlandSY - Syrian Arab RepublicTW - Taiwan, Province of ChinaTJ - TajikistanTZ - Tanzania, United Republic ofTH - ThailandTL - Timor-LesteTG - TogoTK - TokelauTO - TongaTT - Trinidad and TobagoTN - TunisiaTR - TurkeyTM - TurkmenistanTC - Turks and Caicos IslandsTV - TuvaluUG - UgandaUA - UkraineAE - United Arab EmiratesGB - United Kingdom of Great Britain and Northern IrelandUM - United States Minor Outlying IslandsUY - UruguayUZ - UzbekistanVU - VanuatuVE - Venezuela (Bolivarian Republic of)VN - VietnamVG - Virgin Islands (British)VI - Virgin Islands (U.S.)WF - Wallis and FutunaEH - Western SaharaYE - YemenZM - ZambiaZW - Zimbabwe</value>
      <webElementGuid>3f95178f-4654-460d-8595-65a38a6810ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partyAddress.countryDropdown[0]&quot;)</value>
      <webElementGuid>a8fe1b07-b12f-4da2-9b5c-c101dcdd792f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='partyAddress.countryDropdown[0]']</value>
      <webElementGuid>ee27bbd7-6a16-4dac-b5a0-324aaebc5187</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_AddLanguage']/div/div[6]/div[2]/div/select</value>
      <webElementGuid>5a37ab78-97d1-475f-b9dd-68c4e2d1f9ec</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Country'])[1]/following::select[1]</value>
      <webElementGuid>7b4d024b-e2fe-47f3-b551-3593df185d2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address'])[1]/following::select[1]</value>
      <webElementGuid>486131d4-f65d-4099-87a0-6dc59b3dbe5b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 1'])[1]/preceding::select[1]</value>
      <webElementGuid>8dcffa76-2543-494f-b123-df5840a04940</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Address Line 2'])[1]/preceding::select[1]</value>
      <webElementGuid>1129aa39-f2cc-4df0-948a-c5411fb88417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/select</value>
      <webElementGuid>fafd1d3a-728b-4d44-a097-77d7eda04a08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'partyAddress.countryDropdown[0]' and @name = 'item.PartyAddress.CountryId' and (text() = concat(&quot;Select a countryUS - United States of AmericaAF - AfghanistanAX - Åland IslandsAL - AlbaniaDZ - AlgeriaAS - American SamoaAD - AndorraAO - AngolaAI - AnguillaAQ - AntarcticaAG - Antigua and BarbudaAR - ArgentinaAM - ArmeniaAW - ArubaAU - AustraliaAT - AustriaAZ - AzerbaijanBS - BahamasBH - BahrainBD - BangladeshBB - BarbadosBY - BelarusBE - BelgiumBZ - BelizeBJ - BeninBM - BermudaBT - BhutanBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBA - Bosnia and HerzegovinaBW - BotswanaBV - Bouvet IslandBR - BrazilIO - British Indian Ocean TerritoryBN - Brunei DarussalamBG - BulgariaBF - Burkina FasoBI - BurundiCV - Cabo VerdeKH - CambodiaCM - CameroonCA - CanadaKY - Cayman IslandsCF - Central African RepublicTD - ChadCL - ChileCN - ChinaCX - Christmas IslandCC - Cocos (Keeling) IslandsCO - ColombiaKM - ComorosCG - CongoCD - Congo (Democratic Republic of the)CK - Cook IslandsCR - Costa RicaCI - Côte d&quot; , &quot;'&quot; , &quot;IvoireHR - CroatiaCU - CubaCW - CuraçaoCY - CyprusCZ - CzechiaDK - DenmarkDJ - DjiboutiDM - DominicaDO - Dominican RepublicEC - EcuadorEG - EgyptSV - El SalvadorGQ - Equatorial GuineaER - EritreaEE - EstoniaSZ - EswatiniET - EthiopiaFK - Falkland Islands (Malvinas)FO - Faroe IslandsFJ - FijiFI - FinlandFR - FranceGF - French GuianaPF - French PolynesiaTF - French Southern TerritoriesGA - GabonGM - GambiaGE - GeorgiaDE - GermanyGH - GhanaGI - GibraltarGR - GreeceGL - GreenlandGD - GrenadaGP - GuadeloupeGU - GuamGT - GuatemalaGG - GuernseyGN - GuineaGW - Guinea-BissauGY - GuyanaHT - HaitiHM - Heard Island and McDonald IslandsVA - Holy SeeHN - HondurasHK - Hong KongHU - HungaryIS - IcelandIN - IndiaID - IndonesiaIR - Iran (Islamic Republic of)IQ - IraqIE - IrelandIM - Isle of ManIL - IsraelIT - ItalyJM - JamaicaJP - JapanJE - JerseyJO - JordanKZ - KazakhstanKE - KenyaKI - KiribatiKP - Korea (Democratic People&quot; , &quot;'&quot; , &quot;s Republic of)KR - Korea (Republic of)KW - KuwaitKG - KyrgyzstanLA - Lao People&quot; , &quot;'&quot; , &quot;s Democratic RepublicLV - LatviaLB - LebanonLS - LesothoLR - LiberiaLY - LibyaLI - LiechtensteinLT - LithuaniaLU - LuxembourgMO - MacaoMG - MadagascarMW - MalawiMY - MalaysiaMV - MaldivesML - MaliMT - MaltaMH - Marshall IslandsMQ - MartiniqueMR - MauritaniaMU - MauritiusYT - MayotteMX - MexicoFM - Micronesia (Federated States of)MD - Moldova (Republic of)MC - MonacoMN - MongoliaME - MontenegroMS - MontserratMA - MoroccoMZ - MozambiqueMM - MyanmarNA - NamibiaNR - NauruNP - NepalNL - NetherlandsNC - New CaledoniaNZ - New ZealandNI - NicaraguaNE - NigerNG - NigeriaNU - NiueNF - Norfolk IslandMK - North MacedoniaMP - Northern Mariana IslandsNO - NorwayOM - OmanPK - PakistanPW - PalauPS - Palestine, State ofPA - PanamaPG - Papua New GuineaPY - ParaguayPE - PeruPH - PhilippinesPN - PitcairnPL - PolandPT - PortugalPR - Puerto RicoQA - QatarRE - RéunionRO - RomaniaRU - Russian FederationRW - RwandaBL - Saint BarthélemySH - Saint Helena, Ascension and Tristan da CunhaKN - Saint Kitts and NevisLC - Saint LuciaMF - Saint Martin (French part)PM - Saint Pierre and MiquelonVC - Saint Vincent and the GrenadinesWS - SamoaSP - San MarinoST - Sao Tome and PrincipeSA - Saudi ArabiaSN - SenegalRS - SerbiaSC - SeychellesSL - Sierra LeoneSG - SingaporeSX - Sint Maarten (Dutch part)SK - SlovakiaSI - SloveniaSB - Solomon IslandsSO - SomaliaZA - South AfricaGS - South Georgia and the South Sandwich IslandsSS - South SudanES - SpainLK - Sri LankaSD - SudanSR - SurinameSJ - Svalbard and Jan MayenSE - SwedenCH - SwitzerlandSY - Syrian Arab RepublicTW - Taiwan, Province of ChinaTJ - TajikistanTZ - Tanzania, United Republic ofTH - ThailandTL - Timor-LesteTG - TogoTK - TokelauTO - TongaTT - Trinidad and TobagoTN - TunisiaTR - TurkeyTM - TurkmenistanTC - Turks and Caicos IslandsTV - TuvaluUG - UgandaUA - UkraineAE - United Arab EmiratesGB - United Kingdom of Great Britain and Northern IrelandUM - United States Minor Outlying IslandsUY - UruguayUZ - UzbekistanVU - VanuatuVE - Venezuela (Bolivarian Republic of)VN - VietnamVG - Virgin Islands (British)VI - Virgin Islands (U.S.)WF - Wallis and FutunaEH - Western SaharaYE - YemenZM - ZambiaZW - Zimbabwe&quot;) or . = concat(&quot;Select a countryUS - United States of AmericaAF - AfghanistanAX - Åland IslandsAL - AlbaniaDZ - AlgeriaAS - American SamoaAD - AndorraAO - AngolaAI - AnguillaAQ - AntarcticaAG - Antigua and BarbudaAR - ArgentinaAM - ArmeniaAW - ArubaAU - AustraliaAT - AustriaAZ - AzerbaijanBS - BahamasBH - BahrainBD - BangladeshBB - BarbadosBY - BelarusBE - BelgiumBZ - BelizeBJ - BeninBM - BermudaBT - BhutanBO - Bolivia (Plurinational State of)BQ - Bonaire, Sint Eustatius and SabaBA - Bosnia and HerzegovinaBW - BotswanaBV - Bouvet IslandBR - BrazilIO - British Indian Ocean TerritoryBN - Brunei DarussalamBG - BulgariaBF - Burkina FasoBI - BurundiCV - Cabo VerdeKH - CambodiaCM - CameroonCA - CanadaKY - Cayman IslandsCF - Central African RepublicTD - ChadCL - ChileCN - ChinaCX - Christmas IslandCC - Cocos (Keeling) IslandsCO - ColombiaKM - ComorosCG - CongoCD - Congo (Democratic Republic of the)CK - Cook IslandsCR - Costa RicaCI - Côte d&quot; , &quot;'&quot; , &quot;IvoireHR - CroatiaCU - CubaCW - CuraçaoCY - CyprusCZ - CzechiaDK - DenmarkDJ - DjiboutiDM - DominicaDO - Dominican RepublicEC - EcuadorEG - EgyptSV - El SalvadorGQ - Equatorial GuineaER - EritreaEE - EstoniaSZ - EswatiniET - EthiopiaFK - Falkland Islands (Malvinas)FO - Faroe IslandsFJ - FijiFI - FinlandFR - FranceGF - French GuianaPF - French PolynesiaTF - French Southern TerritoriesGA - GabonGM - GambiaGE - GeorgiaDE - GermanyGH - GhanaGI - GibraltarGR - GreeceGL - GreenlandGD - GrenadaGP - GuadeloupeGU - GuamGT - GuatemalaGG - GuernseyGN - GuineaGW - Guinea-BissauGY - GuyanaHT - HaitiHM - Heard Island and McDonald IslandsVA - Holy SeeHN - HondurasHK - Hong KongHU - HungaryIS - IcelandIN - IndiaID - IndonesiaIR - Iran (Islamic Republic of)IQ - IraqIE - IrelandIM - Isle of ManIL - IsraelIT - ItalyJM - JamaicaJP - JapanJE - JerseyJO - JordanKZ - KazakhstanKE - KenyaKI - KiribatiKP - Korea (Democratic People&quot; , &quot;'&quot; , &quot;s Republic of)KR - Korea (Republic of)KW - KuwaitKG - KyrgyzstanLA - Lao People&quot; , &quot;'&quot; , &quot;s Democratic RepublicLV - LatviaLB - LebanonLS - LesothoLR - LiberiaLY - LibyaLI - LiechtensteinLT - LithuaniaLU - LuxembourgMO - MacaoMG - MadagascarMW - MalawiMY - MalaysiaMV - MaldivesML - MaliMT - MaltaMH - Marshall IslandsMQ - MartiniqueMR - MauritaniaMU - MauritiusYT - MayotteMX - MexicoFM - Micronesia (Federated States of)MD - Moldova (Republic of)MC - MonacoMN - MongoliaME - MontenegroMS - MontserratMA - MoroccoMZ - MozambiqueMM - MyanmarNA - NamibiaNR - NauruNP - NepalNL - NetherlandsNC - New CaledoniaNZ - New ZealandNI - NicaraguaNE - NigerNG - NigeriaNU - NiueNF - Norfolk IslandMK - North MacedoniaMP - Northern Mariana IslandsNO - NorwayOM - OmanPK - PakistanPW - PalauPS - Palestine, State ofPA - PanamaPG - Papua New GuineaPY - ParaguayPE - PeruPH - PhilippinesPN - PitcairnPL - PolandPT - PortugalPR - Puerto RicoQA - QatarRE - RéunionRO - RomaniaRU - Russian FederationRW - RwandaBL - Saint BarthélemySH - Saint Helena, Ascension and Tristan da CunhaKN - Saint Kitts and NevisLC - Saint LuciaMF - Saint Martin (French part)PM - Saint Pierre and MiquelonVC - Saint Vincent and the GrenadinesWS - SamoaSP - San MarinoST - Sao Tome and PrincipeSA - Saudi ArabiaSN - SenegalRS - SerbiaSC - SeychellesSL - Sierra LeoneSG - SingaporeSX - Sint Maarten (Dutch part)SK - SlovakiaSI - SloveniaSB - Solomon IslandsSO - SomaliaZA - South AfricaGS - South Georgia and the South Sandwich IslandsSS - South SudanES - SpainLK - Sri LankaSD - SudanSR - SurinameSJ - Svalbard and Jan MayenSE - SwedenCH - SwitzerlandSY - Syrian Arab RepublicTW - Taiwan, Province of ChinaTJ - TajikistanTZ - Tanzania, United Republic ofTH - ThailandTL - Timor-LesteTG - TogoTK - TokelauTO - TongaTT - Trinidad and TobagoTN - TunisiaTR - TurkeyTM - TurkmenistanTC - Turks and Caicos IslandsTV - TuvaluUG - UgandaUA - UkraineAE - United Arab EmiratesGB - United Kingdom of Great Britain and Northern IrelandUM - United States Minor Outlying IslandsUY - UruguayUZ - UzbekistanVU - VanuatuVE - Venezuela (Bolivarian Republic of)VN - VietnamVG - Virgin Islands (British)VI - Virgin Islands (U.S.)WF - Wallis and FutunaEH - Western SaharaYE - YemenZM - ZambiaZW - Zimbabwe&quot;))]</value>
      <webElementGuid>8fe9233b-dbe9-42a1-be9b-e955134fc28b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
