<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Business Role(s) option</name>
   <tag></tag>
   <elementGuidId>d1ca7c88-9c35-4ba3-9209-2ca5528eb342</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//li[text()='${RoleString}']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>eb4d80cc-a5b1-46fe-b0f3-7fb7c80203a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-value</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>6d67434e-e012-41d8-b86d-f53fa2bb90c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>${RoleString}</value>
      <webElementGuid>b3fc7555-24f1-4c00-bf4f-e5ca3a5b3219</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//li[text()='${RoleString}']</value>
      <webElementGuid>cae1233f-cb33-4f2d-83d8-da902946f979</webElementGuid>
   </webElementProperties>
</WebElementEntity>
