<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Business Role(s)</name>
   <tag></tag>
   <elementGuidId>5494f2f5-ad33-4b70-aa79-93bea014825c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='businessddl']/div/div/div/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.input-container</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>210d52ba-cbf6-4dbb-96c7-bd6c53e87c08</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-container</value>
      <webElementGuid>b5adbb0e-0902-4d1c-9345-01571811c60d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;businessddl&quot;)/div[@class=&quot;mult-select-tag select-multi&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;body&quot;]/div[@class=&quot;input-container&quot;]</value>
      <webElementGuid>7e0c6402-6e3d-40ff-a23e-cb07950b2951</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='businessddl']/div/div/div/div</value>
      <webElementGuid>07f51b14-46b7-4a02-aa28-c0b710f1d6a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/div/div[2]/div/div/div/div/div/div</value>
      <webElementGuid>d8d6a42a-1d7f-4de2-b573-08b357a1822e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
