<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Party Alternate Name</name>
   <tag></tag>
   <elementGuidId>4b1541e8-530c-49e9-b6cd-78843ab832ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='additionalName.AlternateName[0]']</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4b3d70a3-2bae-4f07-863b-730c2aa6d40c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-ms partybasicinfoinput</value>
      <webElementGuid>150e5312-85b0-4d96-a3c6-4a9b17c0ba1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>additionalName.AlternateName[0]</value>
      <webElementGuid>5269d10c-b855-4be7-8cb0-5720eefefb0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Alternate Name</value>
      <webElementGuid>dbc0ce36-c45e-4264-b1c3-e2218d91cb5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>200</value>
      <webElementGuid>0e29afa2-4d38-4138-8421-ef341682bc76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>623280e4-446c-4ee8-a8b3-be9f216e3f31</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>item.AlternateName</value>
      <webElementGuid>435a2a6e-3896-471c-8c89-a8ac6a1b40f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;additionalName.AlternateName[0]&quot;)</value>
      <webElementGuid>2b5b4ddd-b52e-44ed-8a7d-b64e0b334747</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='additionalName.AlternateName[0]']</value>
      <webElementGuid>9f7fc0ff-11ba-40e3-af76-e10a8cc20cb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='Div_AddLanguage']/div/div[4]/div/input</value>
      <webElementGuid>fb3bb82e-7c67-46ff-bb64-a658d1e1f748</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/input</value>
      <webElementGuid>e725fe86-435c-4b1c-babc-6fe04e9dcc2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'additionalName.AlternateName[0]' and @placeholder = 'Enter Alternate Name' and @type = 'text' and @name = 'item.AlternateName']</value>
      <webElementGuid>dcae2bd3-bbc5-4015-9b92-8a546b3d561f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
