<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_Inactive</name>
   <tag></tag>
   <elementGuidId>5e4fa6a4-458f-45e0-857f-7920c13455b7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#draft-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='inactive-status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0636b59d-4e25-40a4-bc89-ed6bb5d2090d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>draft-status</value>
      <webElementGuid>35b3904b-3f89-4529-9232-6ccee4c85aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>41332bde-b2bc-42d4-9cd1-3d8514418bd8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>193eb23b-39ee-4d29-bb89-f67da390e356</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>45828f09-10d8-4e2e-a5f3-96a26b3825dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleReasonDiv(1,1)</value>
      <webElementGuid>27809e3a-912d-45ad-b953-670b5196d71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f85ebe7f-8cda-4da1-b062-b745d3945ba2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The StatusId field is required.</value>
      <webElementGuid>c4dfb9f8-de32-43cd-8427-8895c8284ccb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyBasicInfo.StatusId</value>
      <webElementGuid>0e4b6a9d-b2d0-4162-9e45-ad994fc08406</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;draft-status&quot;)</value>
      <webElementGuid>24d982de-b28c-42ef-8122-2f09d67e001f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='draft-status']</value>
      <webElementGuid>1ac2fc6d-6a6d-458a-9196-1a60f94815e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='party-information-87bce1f6ffad']/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>fceb54d2-2b88-46d0-ad5a-8cd024dd7088</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>d68aab8c-be34-4a06-aceb-2e2cd87507eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'draft-status' and @type = 'radio' and @name = 'PartyBasicInfo.StatusId']</value>
      <webElementGuid>643cb60a-a6ff-4eb9-90db-3f62039dc608</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
