<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Status_Active</name>
   <tag></tag>
   <elementGuidId>f1ff2283-3290-489f-af45-604eddc993f9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#draft-status</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='active-status']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2710d1b4-d8ab-43d3-bdf5-d1b0caa2766b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>draft-status</value>
      <webElementGuid>0099fd28-4b8b-4e43-b3ea-b233f3573992</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-check-input</value>
      <webElementGuid>a4080ffe-ff48-4c41-9313-73906a2d4ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>9e2cda39-4e69-4d6f-8a97-2ce785e8c5f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>aa1fda2a-6843-48cd-8738-1d3e1a0b0dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>toggleReasonDiv(1,1)</value>
      <webElementGuid>6d91058a-9c59-47a9-8bca-aae2f262a73c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>429000c7-9aff-4967-9816-8cd919b70967</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The StatusId field is required.</value>
      <webElementGuid>5f186b39-7c64-4519-b55c-192b34195bc5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyBasicInfo.StatusId</value>
      <webElementGuid>4b4da8c7-492a-4621-aed9-eb80a33796f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;draft-status&quot;)</value>
      <webElementGuid>419496e1-6fc1-4f97-9c4b-b0b2be75cab6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='draft-status']</value>
      <webElementGuid>747f691c-dd61-4ae2-861e-d3698e320643</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='party-information-87bce1f6ffad']/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>a5e9aa78-dfaf-40e7-b9dc-58650839304a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div/div/div[2]/div/div/input</value>
      <webElementGuid>ec92979f-7abb-4e2d-bcf3-e0ccff11830d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'draft-status' and @type = 'radio' and @name = 'PartyBasicInfo.StatusId']</value>
      <webElementGuid>8e96f117-03f8-421c-8cb8-f90fe4df669d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
