<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Delivery Mode</name>
   <tag></tag>
   <elementGuidId>a134a029-e459-4513-8426-aad4168e86c0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='DeliveryModeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#DeliveryModeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>589bde3d-a8cb-4b66-b740-49695f4f6191</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>DeliveryModeId</value>
      <webElementGuid>85133d80-fa57-45a7-9c42-7b5f4080f8b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profile</value>
      <webElementGuid>9fa91d42-495e-495e-ba45-dba7c4eaf13a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>1de96182-158c-4760-9b04-54f5a729a16c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The DeliveryModeId field is required.</value>
      <webElementGuid>1ae9d2b6-fdac-49c8-8aa7-09f540b86fca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>DeliveryModeId</value>
      <webElementGuid>a4b75b2b-4771-470f-bb8b-6bcde730644d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>RangeList</value>
      <webElementGuid>07b64566-2f61-4558-88f2-2a1bb60f5265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;DeliveryModeId&quot;)</value>
      <webElementGuid>6582a92a-8f86-4593-b167-a7d2ab157763</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='DeliveryModeId']</value>
      <webElementGuid>1567aa9f-3f39-4ee9-a7ef-c2ca6c1662dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div[3]/div[2]/select</value>
      <webElementGuid>0b575f8d-42da-4871-85b3-7e9b81fc8267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Mode'])[1]/following::select[1]</value>
      <webElementGuid>94fe1a12-46a7-49af-a64e-5f03ac4031c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum Request Quantity'])[1]/following::select[1]</value>
      <webElementGuid>886d3be8-ba12-4832-8253-1ed8ba10c0fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding Format'])[1]/preceding::select[1]</value>
      <webElementGuid>55ec5bf7-192d-46eb-94bc-b0818230ded4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding Prefix'])[1]/preceding::select[2]</value>
      <webElementGuid>1d380e78-f3e2-4a4f-a9e9-048db3eb061a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/select</value>
      <webElementGuid>f8dc2c90-693d-4076-ad77-8f7be9fb9624</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'DeliveryModeId' and @name = 'DeliveryModeId' and (text() = 'RangeList' or . = 'RangeList')]</value>
      <webElementGuid>9a7b541c-7f06-4e5c-87d3-0f5f74d6aa69</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
