<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Encoding Format</name>
   <tag></tag>
   <elementGuidId>14821684-7fd3-46a5-bf83-018c8e7974ba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='OutputFormatTypeId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#OutputFormatTypeId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>dd31dc88-72c4-43a5-b227-08606f7bf1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>OutputFormatTypeId</value>
      <webElementGuid>723b0551-2b1b-4246-824a-fc09a40ff399</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profile</value>
      <webElementGuid>eef2a8f1-0810-4d91-bb28-8afaf617ebe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>outputFormatChange()</value>
      <webElementGuid>c19ea352-4aa0-4730-8305-1127ce82b2fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>97624d62-f0c3-41b5-8a03-46a47f4db277</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The OutputFormatTypeId field is required.</value>
      <webElementGuid>37b9c272-b742-4e66-8c10-788965d87d44</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>OutputFormatTypeId</value>
      <webElementGuid>a9c1134f-2f02-4202-bba6-98866795c84f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>PLAIN_KEYELEMENT_STRINGPURE_IDENTITYTAG_ENCODINGLegacy_AI</value>
      <webElementGuid>d2d4a029-c56a-4710-9e74-e846628c7f5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;OutputFormatTypeId&quot;)</value>
      <webElementGuid>a4352019-c9f5-4d25-95ef-4108b33a962b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='OutputFormatTypeId']</value>
      <webElementGuid>ceaebf2b-5375-4ca3-b112-7df9ab712ce5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div[4]/div/select</value>
      <webElementGuid>532a0d4f-720b-4569-b7a2-48ad410e4bff</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding Format'])[1]/following::select[1]</value>
      <webElementGuid>eb12d037-cac5-4fd3-89b9-398d1d8f59ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delivery Mode'])[1]/following::select[2]</value>
      <webElementGuid>e65a2b12-6e36-403d-930e-05fe422e124c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Encoding Prefix'])[1]/preceding::select[1]</value>
      <webElementGuid>ac8ed899-474c-4650-b785-3cebfd0bc270</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Separate Prefix'])[1]/preceding::select[2]</value>
      <webElementGuid>426f73c3-7150-402e-83c2-869c79242cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div/select</value>
      <webElementGuid>5bf4fc13-1a62-4b43-a874-f0b02f1c85f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'OutputFormatTypeId' and @name = 'OutputFormatTypeId' and (text() = 'PLAIN_KEYELEMENT_STRINGPURE_IDENTITYTAG_ENCODINGLegacy_AI' or . = 'PLAIN_KEYELEMENT_STRINGPURE_IDENTITYTAG_ENCODINGLegacy_AI')]</value>
      <webElementGuid>455eaf45-dfb6-47c5-81b0-3c9e451e0e3e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
