<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Party Name</name>
   <tag></tag>
   <elementGuidId>02a6e548-173c-4725-9aa5-6e451db6301e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='PartyId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#PartyId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
      <webElementGuid>fa28a610-2f30-42e1-bcb4-a44af8f1a3ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>PartyId</value>
      <webElementGuid>7a03be94-faec-4956-9969-062fbe9d889b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profile</value>
      <webElementGuid>18bac2b0-50af-4f52-a5ea-adabe8a8ac63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>systemPartyChange(this)</value>
      <webElementGuid>99da5ae5-872e-47ea-ac58-0601ca7867fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>5b716c88-8cd6-432e-a705-fec8eddef9f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The PartyId field is required.</value>
      <webElementGuid>ee02b935-4f1e-4125-879d-10bff1c4e557</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>PartyId</value>
      <webElementGuid>fcf1d869-cc42-4b1c-bf90-41cd57138f68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Select Party NameRK-Pharmarte_impnorthstarNew RKParty 1_ImportedParty 2_ImportedParty 3_ImportParty 4_ImportParty 101Party 102Party 103Party 1202Party 105Party 201Party 201Party 201Party 201DdkjiwcygjcnettjfzohepfmyrluhbcKtfcqilenuherwaljtwwmkmfvrgkanmCdupqqfrzdbxpqxeygzuqxmdmqglcqxParty 201Party 202Party 201Party 202New partyParty 907Party 091Party 664Party 543Party 124Party 101Demo Party NameDemo Party Name 2Party 437Party 201Spanish nameParty 114StridesParty 110Party 101Test partyTest PartyParty 101onebetaDemo Party nameDemo Party nameParty 57Party 34Party 29Party 69Party 81Party 91Mylan Inc.NorthStar Healthcare Unlimited CompanyAppco Pharma LLCPharmaceutics International IncMcKessonnew_cal56Party Test 101Rk_1Rk_1Rk_2Rk_2Automation Party 479Party Automation 883Party Automation 372Party Automation 823Party Automation 859</value>
      <webElementGuid>86fa54dd-eba5-4ac6-b5af-f15aab817d41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;PartyId&quot;)</value>
      <webElementGuid>45a29047-650a-44d3-ab6a-63a6a6953040</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='PartyId']</value>
      <webElementGuid>40ac71f1-76b9-46a3-8b53-9a5014a07874</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div/div/select</value>
      <webElementGuid>918a28d7-cfbd-4143-a9ea-1830f7ad7993</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Name'])[1]/following::select[1]</value>
      <webElementGuid>1f7cc271-192c-49dd-8ca7-31cbfa332b4f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add New System'])[1]/following::select[1]</value>
      <webElementGuid>db73115e-503d-4090-a5e9-4d6ef11b9d5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='System Name'])[1]/preceding::select[1]</value>
      <webElementGuid>9b6349d0-f2f4-4e46-9164-22acb0cb69cf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Range'])[1]/preceding::select[2]</value>
      <webElementGuid>25388969-a5f8-43f0-bca3-469e70ddbb7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/select</value>
      <webElementGuid>062d3f97-10f2-4807-a89a-743750998331</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//select[@id = 'PartyId' and @name = 'PartyId' and (text() = 'Select Party NameRK-Pharmarte_impnorthstarNew RKParty 1_ImportedParty 2_ImportedParty 3_ImportParty 4_ImportParty 101Party 102Party 103Party 1202Party 105Party 201Party 201Party 201Party 201DdkjiwcygjcnettjfzohepfmyrluhbcKtfcqilenuherwaljtwwmkmfvrgkanmCdupqqfrzdbxpqxeygzuqxmdmqglcqxParty 201Party 202Party 201Party 202New partyParty 907Party 091Party 664Party 543Party 124Party 101Demo Party NameDemo Party Name 2Party 437Party 201Spanish nameParty 114StridesParty 110Party 101Test partyTest PartyParty 101onebetaDemo Party nameDemo Party nameParty 57Party 34Party 29Party 69Party 81Party 91Mylan Inc.NorthStar Healthcare Unlimited CompanyAppco Pharma LLCPharmaceutics International IncMcKessonnew_cal56Party Test 101Rk_1Rk_1Rk_2Rk_2Automation Party 479Party Automation 883Party Automation 372Party Automation 823Party Automation 859' or . = 'Select Party NameRK-Pharmarte_impnorthstarNew RKParty 1_ImportedParty 2_ImportedParty 3_ImportParty 4_ImportParty 101Party 102Party 103Party 1202Party 105Party 201Party 201Party 201Party 201DdkjiwcygjcnettjfzohepfmyrluhbcKtfcqilenuherwaljtwwmkmfvrgkanmCdupqqfrzdbxpqxeygzuqxmdmqglcqxParty 201Party 202Party 201Party 202New partyParty 907Party 091Party 664Party 543Party 124Party 101Demo Party NameDemo Party Name 2Party 437Party 201Spanish nameParty 114StridesParty 110Party 101Test partyTest PartyParty 101onebetaDemo Party nameDemo Party nameParty 57Party 34Party 29Party 69Party 81Party 91Mylan Inc.NorthStar Healthcare Unlimited CompanyAppco Pharma LLCPharmaceutics International IncMcKessonnew_cal56Party Test 101Rk_1Rk_1Rk_2Rk_2Automation Party 479Party Automation 883Party Automation 372Party Automation 823Party Automation 859')]</value>
      <webElementGuid>285bb332-6ad1-4af4-b908-4364152fbeec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
