<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Separate Prefix_checkbox</name>
   <tag></tag>
   <elementGuidId>febf97e8-3131-4874-ace0-129e7876013f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='SeperatePrefix']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#SeperatePrefix</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3ed19014-1d29-4de0-89d7-5d33837b1202</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>SeperatePrefix</value>
      <webElementGuid>11ac2255-164e-4be5-9f24-0b8f0d5c6010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>row input-profilesm sgtinSeperatePre</value>
      <webElementGuid>444c4c73-6207-4698-8a25-56de02e7545d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter Separate Prefix</value>
      <webElementGuid>61efe47d-b6d4-466c-b469-65d7e136907b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>d3f0d691-b32e-4554-8de9-48a5babe6d62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a7a2621d-8b16-42d6-905f-dfb20f6e8759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-val-required</name>
      <type>Main</type>
      <value>The SeperatePrefix field is required.</value>
      <webElementGuid>ccf1cf46-eece-4209-9dcf-b220c6beda49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>SeperatePrefix</value>
      <webElementGuid>c85f0e24-7143-4f96-98f6-ee5503ba1457</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>de363446-a49c-49dd-91cc-9e998a900add</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;SeperatePrefix&quot;)</value>
      <webElementGuid>b8afe774-70ec-453c-bf66-75548b11bc3c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='SeperatePrefix']</value>
      <webElementGuid>33b06148-757d-4b1b-a5f1-7f975bea9fce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='forAddSystem']/div/div[4]/div[3]/input</value>
      <webElementGuid>35d5e65d-321f-4a21-a64c-993600c925ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[3]/input</value>
      <webElementGuid>35f5c1a6-5422-4372-b922-09eb6e04889b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'SeperatePrefix' and @placeholder = 'Enter Separate Prefix' and @type = 'checkbox' and @name = 'SeperatePrefix']</value>
      <webElementGuid>ea0bf0c4-dc99-4163-87e6-becc78f2f2a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
