<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Audit Trail Tab</name>
   <tag></tag>
   <elementGuidId>7d8a6d54-4d87-423b-9216-76e7e567dc89</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_partHistory</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_partHistory']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>66b84ae7-6bfe-46d3-a8b0-f9aa343c80d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_partHistory</value>
      <webElementGuid>d4f9037b-6b97-4c07-91bc-df762c91d519</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab tab-active</value>
      <webElementGuid>69b3854c-ccbf-4421-9ffa-5a4da4f71ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Audit Trail</value>
      <webElementGuid>e7d1487e-7592-43f5-9222-2850e2001045</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_partHistory&quot;)</value>
      <webElementGuid>82ad63bb-d0a4-4268-9b9a-c285652790d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_partHistory']</value>
      <webElementGuid>600990dd-e880-43fc-b121-eeb3da4f4310</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Locations'])[1]/following::button[1]</value>
      <webElementGuid>53f6e330-ca1a-4fce-9746-3cc4cada10fe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SN Template'])[1]/following::button[2]</value>
      <webElementGuid>672632ba-e0c3-4955-a9f9-42d1f8302ca5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[3]/preceding::button[1]</value>
      <webElementGuid>8ed56e76-a514-42f4-ba01-86e43d484df4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Save'])[1]/preceding::button[2]</value>
      <webElementGuid>a5425ed0-6c8b-4530-956b-d701b18b5d4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Audit Trail']/parent::*</value>
      <webElementGuid>ed7d6f59-869e-4527-8cec-d84c323fc85c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[5]</value>
      <webElementGuid>ba99c379-cbe3-467c-8a05-2a36d0cce74a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_partHistory' and (text() = 'Audit Trail' or . = 'Audit Trail')]</value>
      <webElementGuid>eaa04276-a4dd-4891-8978-c3b41c3c11d9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
