<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Party Details</name>
   <tag></tag>
   <elementGuidId>dab0942f-e138-4675-8f88-3fe9c82437be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_partDetail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_partDetail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>767380aa-40f3-4afa-bea6-bf9a14e80739</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_partDetail</value>
      <webElementGuid>d069fadd-abfe-4757-b6d5-2d4a7e8c86ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab tab-active</value>
      <webElementGuid>b07af0b0-66b5-421b-b774-3163fd251bd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Party Details  </value>
      <webElementGuid>152c99b7-0fa9-49f5-a7c1-97b8f3c83892</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_partDetail&quot;)</value>
      <webElementGuid>8e88bf2d-d66e-4166-bdf3-3d4284bd95bf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_partDetail']</value>
      <webElementGuid>aa7a5ef3-e760-424c-8d2f-3c39e7fe1795</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Business Role :'])[1]/following::button[1]</value>
      <webElementGuid>9c11b1a3-b37f-47d1-95cc-8d547bf3c8a2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party GLN :'])[1]/following::button[1]</value>
      <webElementGuid>de462278-2cee-4777-b34e-da53cd4fde5e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Party Identifiers'])[1]/preceding::button[1]</value>
      <webElementGuid>93600a89-6ad8-4674-9db2-25b84067c49c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='SN Template'])[1]/preceding::button[2]</value>
      <webElementGuid>ca56bc38-e1e3-4a16-84ba-84a2d61e314c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Party Details']/parent::*</value>
      <webElementGuid>b5674cbf-dcc5-42c0-a5af-8c7a4c638f40</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/button</value>
      <webElementGuid>2c35195e-1cfd-4287-b64f-64187415a442</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'btn_partDetail' and (text() = ' Party Details  ' or . = ' Party Details  ')]</value>
      <webElementGuid>4869e4c2-91af-40c2-be22-13bc5684bfa4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
